### ISSUE TITLE
monorepo support: sass

### ISSUE THREAD

**Issue by sthuck** [wix/yoshi#1003]
# 🙋 Feature Request

### 😯 Current Behavior
When working with a monorepo, some packages might be hoisted to root folder. If you try to import a sass file from a package that was hoisted, build will fail.

Bonus part: why don't I just use `nohoist` and leave you guys alone? 
If I use `nohoise` than indeed I can work, but now some `scss` files will be duplicated and imported multiple times. I end up with a 12mb css bundle... it works but now I can't reliably track the size of my css bundle, debugging is harder, browser is slower etc...

### 🤔 Expected Behavior
when importing `.scss` file it should be resolved similar to a `.js` file, first in `node_modules`, then in `'../node_modules'` etc.

### 💁 Possible Solution 
I see two ways to solve this - 

1. The clean way - using `node-sass-tilde-importer`, or some other node-sass custom importer.
This requires change also in haste, as you can't pass the importer (it's a function) as part of the options to the child process.

Cons: users migrating to monorepo would need to change all their `@import 'packgeFoo/file.scss'` to `@import '~packageFoo/file.scss'`.

2. The ugly way - just add another include path of `['../node_modules', '../../node_modules']`. It would solve 99.9% of use cases. But it's obviously an ugly solution.

Willing to do the PR, let me know what you guys prefer.

(I actually think the ugly way is preferable, at least in the short run. if nothing else just to avoid adding another dependency. Since as npm history shows, dependencies that aren't maintained by some well known organisation are a security risk.
Maybe writing our own node-sass importer is the way to go.)

**Comment by ruhulwebdev** [comment]
why is this issue closed 😡

**Comment by keerthiprasads** [comment]
Any progress on this issue?

**Comment by ranyitz** [comment]
Adding a repro from @GabiGrin which should ease the reproduction of this case and hopefully solving it.

https://github.com/wix-a/scss-test

**Comment by GabiGrin** [comment]
@ranyitz  thanks for reopening
my next step would be testing it using create-react-app to see if it's a webpack/sass-loader issue or indeed a Yoshi config, but ran out of time to deal with that
