### ISSUE TITLE
Ease migration to the app flow

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1068]
# 🙋 Feature Request

### 😯 Current Behavior

When migrating a project to the new "app" flow (`projectType: "app"`) I always forget to change `--entry-point` into `server`, and I get an error that `--entry-point` is not supported.

### 🤔 Expected Behavior

* Give a nicer migration so it will just work for me or will give me a way to solve this problem.

### 💁 Possible Solution

1. Support both options for a short while and give a warning for using the deprecated option. (`--entry-point`) suggesting to replace it to `--server`
2. Not necessarily support both options, but at least give an indicative error that `--entry-point` is not supported anymore, please use `--server` instead, so the user won't need to go back to the documentation and search for solutions.

**Comment by ronami** [comment]
Good feedback, thanks. Done in #1073.

**Comment by ranyitz** [comment]
Thanks @ronami this is a great solution to this problem.
