### ISSUE TITLE
Howto. Incremental migration from JS to TS?

### ISSUE THREAD

**Issue by skyiea** [wix/yoshi#108]
Hey.
I'm trying to introduce TS into an existent JS project, but prefer to do it incrementally, rather than big-bang. This means that I don't want to touch any *.js* files until the time when I'll need to modify them.
_What would be the right approach to do this?_

As far as I understand, *haste* looks for `tsconfig.json` to understand whether it is TS project or no (JS). I've assumed that adding it (config) and setting `allowJs` is what I needed, but within *haste*'s webpack rules/loaders I see that *.js* is always transpiled by Babel and *.ts* by TSC, no matter if it is TS project or no.

Here is the thread in Slack: https://wix.slack.com/archives/C0NJPS8N5/p1513265445000502

**Comment by ranyitz** [comment]
@skyiea @shahata

It seems that the documentation points that `ts-loader` should work great with `babel-loader` - https://github.com/TypeStrong/ts-loader#babel.

There are also exmaples:

https://github.com/TypeStrong/ts-loader/blob/master/examples/react-babel-karma-gulp/webpack.config.base.js

https://github.com/TypeStrong/ts-loader/tree/master/examples/react-babel-allowjs

There is also an option for vanilla ts - https://github.com/TypeStrong/ts-loader/tree/master/examples/react-babel-allowjs

I'm not sure what it will solve to go from one method to the other.
Let me know if i missed anything here.
