### ISSUE TITLE
On "yoshi start" open the browser window on a custom url/route

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1082]
# 🙋 Feature Request

### 😯 Current Behavior

When running `yoshi start` it opens the browser on `localhost:${PORT}/`

### 🤔 Expected Behavior

The user could configure what is the route which opens every time that `yoshi start runs`.

### 💁 Possible Solution

Add a CLI option (e.g. `--default-route=my-route`) that will cause yoshi to open the browser on `http://localhost:3000/my-route`.

I thought about `route` but we can also go with `--default-url` and give completely custom behavior to the first route that opens when running `yoshi start`.

### 🔦 Context

I work on a fullstack app that serves multiple routes, the route that I work on is not always `/` and I would love to configure a different route for every command.

For example `npm run start:bizmgr` should open a specific route.

**Comment by ronami** [comment]
Good point. I like `--url` for simplicity, seeing `npx yoshi start --url=http://localhost:1234/hello` makes me understand that it would open this URL. Wdyt?

**Comment by ronami** [comment]
Closed at #1084.
