### ISSUE TITLE
Migrate client/fullstack generators to use app-flow

### ISSUE THREAD

**Issue by ronami** [wix/yoshi#1109]
### Summary

We're considering app flow as stable and recommend users to start working with it. We should migrate client, fullstack to use it (along with their TypeScript versions).

_____

- [x] fullstack (#1123)
- [x] client
- [ ] server
- [x] business-manager-module

**Comment by ronami** [comment]
Some progress: #1123.

**Comment by ranyitz** [comment]
Server would have a specific flow, BM moved to use app flow. closing
