### ISSUE TITLE
Inconsistent versions between yoshi and jest-yoshi-preset

### ISSUE THREAD

**Issue by netanelgilad** [wix/yoshi#1117]
# 🐛 Bug Report

### 😯 Current Behavior

Currently, since `jest-yoshi-preset` needs to be installed alongside `yoshi`, they may be installed with different major versions and thus cause incompatibilities.

### 🤔 Expected Behavior

`yoshi` should ensure it's running alongside a compatible `jest-yoshi-preset`.

### 🔦 Context 

An example is when migrating from `yoshi@3` to `yoshi@4` and forgetting to update `jest-yoshi-preset`.

### 💁 Possible Solution 

We can either validate the version at runtime, or maybe some solution with peerDeps?

**Comment by ronami** [comment]
Closed in #1119.
