### ISSUE TITLE
Verify that versions of Yoshi and related packages match

### ISSUE THREAD

**Issue by ronami** [wix/yoshi#1119]
### Summary

Sometimes Yoshi is installed in one version and some of its related packages (`jest-yoshi-preset`, `yoshi-style-dependencies` and `yoshi-angular-dependencies`) are installed in a different version. This can happen to a lot of users when we bump a major version and they need to remember to change all of them. If the versions don't match it can cause bugs that are hard to detect.

To help detect these problems easier, we can check that Yoshi and those packages are on the same version and fail with a clear error otherwise. We can do this check in every command (`start`, `build`, `test`).

**Comment by rudnitskih** [comment]
@ronami @yavorsky What is the reason to have all these related packages as separate projects?
`yoshi-style-dependencies` and `yoshi-angular-dependecies` just install additional packages. Is this just for performance reason don't waste half a second to load angular deps for react project or some more interesting?

**Comment by ronami** [comment]
This is a good point. Yes, it was done to make the installation faster for projects that don't require some of the heavier dependencies. I think we shouldn't ask users to install many different dependencies (and match their dependencies). I want it to be simple, just install Yoshi.

I plan on changing it for the next version of Yoshi: I want to remove support for Angular projects (protractor, karma, mocha) and install `jest-yoshi-preset` already with Yoshi. It would be nice to also install `node-sass` and related dependencies so we'll be able to remove `yoshi-style-dependencies`. I think it will make it simpler for most projects.

Until then though, I think showing a clear error if the versions of those dependencies don't match will save developers time in debugging.
