### ISSUE TITLE
Running jest in watch mode on a new machine fails

### ISSUE THREAD

**Issue by shlomitc** [wix/yoshi#1124]
# 🐛 Bug Report

### 😯 Current Behavior

starting `jest` in watch-mode throws an error
![image](https://user-images.githubusercontent.com/6093192/54488545-994bcd00-48ab-11e9-9c83-c2d5b4adb045.png)

### 🤔 Expected Behavior

To run the test as expected

### 🔦 Context 

Running tests in watch mode locally on a new machine

### 💁 Possible Solution 

`brew install watchman`

### 👣 Steps to Reproduce 

`npx yoshi test --jest --watch`

### 💻 Code Sample

...

### 🌍 Your Environment

```
 System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v10.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: Not Found
    Firefox: 65.0
    Safari: 12.0.3
  npmPackages:
    @storybook/core:  4.1.14
    @storybook/react: ^4.1.11 => 4.1.14
    babel-preset-yoshi:  4.1.0-alpha.7
    eslint-config-yoshi:  4.1.0-alpha.7
    eslint-config-yoshi-base:  4.1.0-alpha.7
    jest-environment-yoshi-bootstrap:  4.1.0-alpha.7
    jest-environment-yoshi-puppeteer:  4.1.0-alpha.7
    jest-yoshi-preset: ^4.1.0-alpha.1 => 4.1.0-alpha.7
    storybook: Not Found
    tslint-config-yoshi:  4.1.0-alpha.7
    tslint-config-yoshi-base:  3.30.5
    typescript:  2.9.2
    webpack: ^4.29.3 => 4.29.6
    yoshi-config: ^4.1.0-alpha.1 => 4.1.0-alpha.7
    yoshi-helpers: ^4.1.0-alpha.1 => 4.1.0-alpha.7
    yoshi-runtime: ^1.0.42 => 1.0.42

 Yoshi config
{
  "entry": {
    "app": "index.js"
  },
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM",
    "Wix": "Wix"
  },
  "externalUnprocessedModules": [
    "get-own-enumerable-property-symbols",
    "stringify-object"
  ],
  "exports": "wix-style-react"
}
```

**Comment by ronami** [comment]
Is this specific to Yoshi or something related to Jest?

**Comment by shlomitc** [comment]
Didn't try running jest directly, but you're probably right.
Do you think maybe it should be in the FAQ?

**Comment by ranyitz** [comment]
Agree with @ronami 

Googling the error message brings the following results:
https://github.com/facebook/jest/issues/3436
https://github.com/facebook/create-react-app/issues/4540#issuecomment-393310226

I think we can just add this to the installations part [here](https://github.com/wix-private/fed-handbook/blob/master/INSTALLATIONS.md)

**Comment by shlomitc** [comment]
maybe we can identify if watchman is installed, so when `watch` mode is on, we can at least print a message to install it if missing
