### ISSUE TITLE
provide global setup per jest project (jest-yoshi-preset)

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1133]
# 🙋 Feature Request

### 😯 Current Behavior

When we run component tests, Yoshi tells us to run `npm start` while this is not necessary.

### 🤔 Expected Behavior

Yoshi will know that we're running component tests and won't show the error message.

### 💁 Possible Solution

There is a new feature in Jest 24 that enable adding a global setup file for each jest "project" - https://github.com/facebook/jest/pull/6865

We can use this feature in order to use the global-setup only in puppeteer environment (which is the only one which requires it)

Code reference - https://github.com/wix/yoshi/blob/master/packages/jest-yoshi-preset/jest-preset.js#L10

Should be moved to the global setup of the project.

(This could only work on yoshi@4 because it brings Jest@24)

### 🔦 Context

There is a lot of frustration when we try to run component tests and Yoshi tells us to run `npm start` when it's actually not needed.

**Comment by yakirn** [comment]
Hey, @ranyitz I need this feature, and given it is label as "Good first issue" I might want to take this. I see that a year has almost pass since you created this issue, so I just want to make sure it is relevant/no one else is working on this...

**Comment by ranyitz** [comment]
@yakirn This feature is still up for grabs, please take it 🥇

**Comment by yanivefraim** [comment]
Fixed by #1775 1775

**Comment by yanivefraim** [comment]
Fixed by #1775
