### ISSUE TITLE
jest-yoshi-preset config cannot be overridden

### ISSUE THREAD

**Issue by dorduch** [wix/yoshi#1135]
# 🐛 Bug Report

### 😯 Current Behavior

When using `preset: jest-yoshi-preset` and adding more configuration like
```
 "collectCoverage": true,
    "coveragePathIgnorePatterns": [
      "/node_modules/",
      "/src/locale-keys/.*.(ts|tsx)$",
      "/src/.*\\.(spec|driver|testKit|testkit)\\.(ts|tsx)$",
      "/test/.*\\.*\\.*$",
      "/src/icons/.*\\.*\\.*$",
      ".*\\.graphql$"
    ],
    "coverageThreshold": {
      "global": {
        "statements": 100,
        "branches": 100,
        "functions": 100,
        "lines": 100
      }
    },
    "coverageReporters": [
      "html"
    ],
```

it does collect coverage but ignores `coveragePathIgnorePatterns`

### 🤔 Expected Behavior

Any addition jest configuration should override `jest-yoshi-preset` configuration 

### 🔦 Context 

I can't use `jest-yoshi-preset` in a new project because we want to preserve 100% coverage and that cannot be done without `coveragePathIgnorePatterns`

### 💻 Code Sample

https://gist.github.com/dorduch/01158e7cc186a659d71c8fc845c0be69

### 🌍 Your Environment
```
  System:
    OS: macOS 10.14.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 64.0
    Safari: 12.0.3
  npmPackages:
    @storybook/core: Not Found
    @storybook/react: Not Found
    babel-preset-yoshi:  4.1.0-alpha.7 
    eslint-config-yoshi:  4.1.0-alpha.7 
    eslint-config-yoshi-base:  4.1.0-alpha.7 
    jest-environment-yoshi-bootstrap:  3.31.0 
    jest-environment-yoshi-puppeteer:  3.31.0 
    jest-yoshi-preset: ^4.1.0-alpha.1 => 4.1.0-alpha.7 
    storybook: Not Found
    tslint-config-yoshi:  3.30.5 
    tslint-config-yoshi-base:  3.30.5 
    typescript: ^3.3.3333 => 3.3.3333 
    webpack:  4.28.4 
    yoshi-config:  3.31.0 
    yoshi-helpers:  3.31.0 
    yoshi-runtime: Not Found

 Yoshi config
{
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM",
    "axios": "axios",
    "@wix/business-manager-api": "BusinessManagerAPI"
  },
  "separateCss": false,
  "entry": {
    "registerComponent": "./businessManager/registerComponent.entry.ts",
    "app": "../test/client.tsx"
  },
  "servers": {
    "cdn": {
      "ssl": false
    }
  },
  "hmr": "auto"
}
```

**Comment by ranyitz** [comment]
@dorduch create-react-app had a similar issue. I have to say that I agree with [Dan's answer](https://github.com/facebook/create-react-app/issues/2825#issuecomment-316692021).

In CRA they are [intentionally not supporting it](https://github.com/facebook/create-react-app/blob/3be35763044c690458e806c255e100336de0d9a1/packages/react-scripts/scripts/utils/createJestConfig.js#L69-L80).

Running coverage tests using `package.json` configuration will __always__ run the coverage, while there is a penalty in testing time. Currently, you can use Jest's CLI options, which requires you to use a whitelist instead of a blacklist.
