### ISSUE TITLE
Make dist css modules class names shorter

### ISSUE THREAD

**Issue by itaibenda** [wix/yoshi#114]
Goal: reduce bundle size.
It's enough to have only the hash as the class name in production

In sass.js/less.js:
Should allow a configuration for dev:
localIdentName: '[path][name][local][hash:base64:5]'
and for prod:
localIdentName: '[hash:base64:5]'

**Comment by shahata** [comment]
@itaibenda can you plz create pull request for this?

**Comment by itaibenda** [comment]
@shahata will do

**Comment by yanivefraim** [comment]
I'm taking this one...

**Comment by yanivefraim** [comment]
After fixing local min file to be the actual min file (by fixing this commit https://github.com/wix/yoshi/commit/620484c419c5508e95ae350df04231c131c85cf5), we should consider having the short version on all minified versions. This will help us know bundle size locally, which might be important for performance monitoring (when done manually, locally)

@itaibenda

**Comment by yanivefraim** [comment]
https://github.com/wix/yoshi/pull/130

**Comment by yanivefraim** [comment]
Closing this - we'll continue with https://github.com/wix-private/wix-js-stack/issues/463
