### ISSUE TITLE
Combine Jest preset and related packages into 1 package

### ISSUE THREAD

**Issue by ronami** [wix/yoshi#1143]
### Summary

Currently, our Jest preset uses two internal packages: `jest-environment-yoshi-bootstrap` and `jest-environment-yoshi-puppeteer`. There's no real need to separate them into different packages and I think it would be easier to handle common code in one package.

This change shouldn't break any of our users.

**Comment by ranyitz** [comment]
still important

**Comment by ronami** [comment]
This one package should also include the part that loads and verifies its config (currently in `yoshi-config`).

**Comment by ranyitz** [comment]
> This one package should also include the part that loads and verifies its config (currently in yoshi-config).

@ronami Do you want to open another issue for that, or maybe reopen this one?

**Comment by ronami** [comment]
@yanivefraim, want to take this up?
