### ISSUE TITLE
ESLint rule for regexes using features not supported by all browsers

### ISSUE THREAD

**Issue by yurynix** [wix/yoshi#1165]
# 🙋 Feature Request
RegExp in different browsers support different features, for example,
Chrome supports Lookbehind, however, Firefox does not.

### 😯 Current Behavior
We don't warn the developer about the imminent danger

### 🤔 Expected Behavior
Warn the developer it'll break on other browsers, such as Firefox.
![Screen Shot 2019-03-21 at 17 06 57](https://user-images.githubusercontent.com/326402/54761956-cd9cf180-4bfb-11e9-9084-61045a47fdf1.png)

### 💁 Possible Solution 

Using -> https://github.com/DmitrySoshnikov/regexp-tree
```
regexpTree.parse('/(?<=text-align:)([^"]*)/')
    .body
    .expressions
    .some(exp => exp.type === 'Assertion' && exp.kind === 'Lookbehind');
```

**Comment by ronami** [comment]
This is interesting. I think that regexes are only one use-case of writing code that will not work for every browser we target. I think that possibly adding [eslint-plugin-compat](https://github.com/amilajack/eslint-plugin-compat) can help with this.

cc @yavorsky as I think he looked quite a bit into this subject 🙂
