### ISSUE TITLE
pseudo element(:export) doesn't work in node-sass

### ISSUE THREAD

**Issue by roymiloh** [wix/yoshi#117]
_originally written by @etaybarzilay89:_

I'm trying to share variable between scss to js using :export pseudo element.

The reason its not working is that node sass does not support this, but sass loader does.

@itaibenda @roymiloh knows the issue.

**Comment by ranyitz** [comment]
@roymiloh, Is this still relevant?

**Comment by roymiloh** [comment]
I'd ask @etaybarzilay89 - I just transferred this issue to here.

**Comment by ranyitz** [comment]
@etaybarzilay89 Feel free to reopen and explain if it's relevant.

closing.
