### ISSUE TITLE
Upgrade Docusaurus version

### ISSUE THREAD

**Issue by ronami** [wix/yoshi#1172]
### Summary

Currently, we use an old version of [Docusaurus](https://github.com/facebook/docusaurus). It would be nice to update to the latest version and enable some of the recent features it includes.

**Comment by dmfilipenko** [comment]
@ronami Do we want to update the only version of docusaurus or we can introduce some new features:

- Allow modifying/removing docs route in generated url
- Enabled subcategories in sidebar
- [code block](https://github.com/facebook/Docusaurus/pull/1063)

**Comment by dmfilipenko** [comment]
Update version without introducing new featureshttps://github.com/wix/yoshi/pull/1247
