### ISSUE TITLE
Need to refresh jest's watch mode when updating jest-yoshi-config

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1177]
# 🐛 Bug Report

### 😯 Current Behavior

During jest's watch mode, if you make changes in `jest-yoshi.config.js`, you need to exit jest's watch mode and rerun it so the config will be reevaluated.

### 🤔 Expected Behavior

Change's in `jest-yoshi.config.js` will not require a jest rerun.

### 🔦 Context
When working on fullstack/client projects, we find ourselves changing puppeteer `decvtools` options from `false` into `true` in order to debug our code.

![image](https://user-images.githubusercontent.com/11733036/54920558-317d2e00-4f0c-11e9-93e6-64012f2ab61c.png)

While this is just an example, it happens many times and the required refresh to the watch mode slows the work flow.

### 💁 Possible Solution 

Do not cache the config load and call it within `jest-environment-yoshi-puppeteer`'s global setup function:

https://github.com/wix/yoshi/blob/f2b95b83f3628bc51ac0988cfd672b1760b8f56d/packages/jest-environment-yoshi-puppeteer/globalSetup.js#L25

### 👣 Steps to Reproduce

1. Create a new project.
2. Run `npm start`
3. Run the tests in watch mode `npx jest --watch`
4. Change the `devtools` option in `jest-yoshi.config.js` into true.

(The browser would not be opened. After a refresh to the jest process it will be) 

### 🌍 Your Environment
```
yoshi v4.1.0-rc.4
```

**Comment by brumeregan** [comment]
Hi,
I and @vozhekhovskyi are going to resolve this issue at our guild week.

**Comment by ranyitz** [comment]
Thanks @brumeregan and @vozhekhovskyi! Good luck :)

**Comment by brumeregan** [comment]
@ranyitz 
Looks like this can not be resolved easily, because the whole file is invoked once by jest setup, and do not detect any updates. --no-cache and --clearCache didn't help.
Also we didn't find any information that jest allows us to update config in watch mode

**Comment by ranyitz** [comment]
Fixed on #1307
