### ISSUE TITLE
Debugging our app's code in the browser takes too many steps.

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1178]
# 🙋 Feature Request

### 😯 Current Behavior

In order to debug our app's in the browser when working with `jest-yoshi-preset` there are some steps that you need to do:

Looking at [puppeteer debugging tips](https://github.com/GoogleChrome/puppeteer#debugging-tips) and [jest-yoshi.config documentation](https://wix.github.io/yoshi/docs/guides/jest-setup#configuration)

1. Change `jest-yoshi.config.js`'s `puppeteer.devtools` option from `false` to  `true`.
2. Add a debugger statement in your code or using evaluate :`await page.evaluate(() => {debugger;});`
3. Extend jest's timeout: `jest.setTimeout(100000);` so it won't close the jest process.
4. Restart the jest process

### 🤔 Expected Behavior

1. No need to change a configuration for a specific run, the user experience should be better, for example, using jest's watch mode.
2. `jest-yoshi-preset` can assume that when `devtools: true` is used we want to extend jest's timeout, so there is no need to do that manually.
3. No need to restart the jest process (Should be solved on #1177)

### 💁 Possible Solution 

1. Write a new [jest watch plugin](https://jestjs.io/docs/en/watch-plugins#watch-menu-integration) that adds the `'d' (debug/devtools)` option to the jest watch menu. When you press on it, it will change the `devtools` option and will run the tests again, so essentially there is no need for a configuration change.

2. We can extend [jest's timeout](https://jestjs.io/docs/en/jest-object#jestsettimeouttimeout) when the `devtools` option is truthy.

### 🔦 Context

Debugging is important, and when so many steps are required, it makes debugging a hard task. Debugging should be easy, and we can use those simple heuristics in order to improve the workflow for everyone.

**Comment by ronami** [comment]
Can be very helpful. `jest-puppeteer` did something similar: https://github.com/smooth-code/jest-puppeteer#put-in-debug-mode.
