### ISSUE TITLE
Stylable - jest runtime configured differently from Webpack plugin

### ISSUE THREAD

**Issue by NitayRabi** [wix/yoshi#1189]
# 🐛 Bug Report

### 😯 Current Behavior

When running e2e tests
- `yoshi build` produces a bundle with StylableWebpackPlugin with specific configuration.
- `Yoshi test` uses `@stylable/jest` with different configuration producing different namespace and preventing testing of Stylable states using Stylable test utils.
### 🤔 Expected Behavior

- Stylable configuration should be singular per project.
- Using Stylable test utils should work in e2e environment.

### 🔦 Context 

WSR testkit which use Stylable for testing (e.g `Button` components) doesn't work properly
### 💁 Possible Solution 

Stylable issue - 
1. Wait for https://github.com/wix/stylable/issues/567 and configure jest plugin based on single `BaseStylableConfiguration`.
2. Write inline jest processor in [jest.config.js](https://github.com/wix/yoshi/blob/master/packages/yoshi/config/jest.config.js)
3. Same process should be validated in other test runners.

### 💻 Code Sample

- Create yoshi app
- Add <Button> component
- Test button component's disabled prop using testkit in Puppeteer
App.js
```
import React from 'react';
import { translate } from 'react-i18next';
import s from './App.scss';
import PropTypes from 'prop-types';
import Button from 'wix-style-react/Button';

class App extends React.Component {
  static propTypes = {
    t: PropTypes.func,
  };

  render() {
    const { t } = this.props;
    return (
      <div className={s.root}>
        <Button dataHook="wsr-btn" disabled>
          Im A WSR Button
        </Button>
      </div>
    );
  }
}

export default translate()(App);
```

app.e2e.js
```
import { buttonTestkitFactory } from 'wix-style-react/dist/testkit/puppeteer';

describe('E2E', () => {
  let driver;
  beforeEach(async () => {
    await page.goto(app.getUrl('/'));
    driver = await buttonTestkitFactory({ dataHook: 'wsr-btn', page });
  });
  it('Button testkit should validate button exists', async () => {
    expect(await driver.exists()).toBe(true);
  });
  it('should test if button is disabled', async () => {
    expect(await driver.isButtonDisabled()).toEqual(true);
  });
});
```
### 🌍 Your Environment

```
System:
    OS: macOS 10.14.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: Not Found
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
    Watchman: Not Found
  Browsers:
    Chrome: Not Found
    Firefox: 65.0.1
    Safari: 12.0.3
  npmPackages:
    @storybook/core: Not Found
    @storybook/react: Not Found
    babel-preset-yoshi:  4.1.0
    eslint-config-yoshi:  4.1.0
    eslint-config-yoshi-base:  4.1.0
    jest-environment-yoshi-bootstrap:  4.1.0
    jest-environment-yoshi-puppeteer:  4.1.0
    jest-yoshi-preset: ^4.1.0 => 4.1.0
    storybook: Not Found
    tslint-config-yoshi:  4.1.0
    tslint-config-yoshi-base:  4.1.0
    typescript: Not Found
    webpack:  4.28.4
    yoshi-config:  3.31.0
    yoshi-helpers:  4.1.0
    yoshi-runtime: Not Found

 Yoshi config
{
  "projectType": "app",
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM"
  },
  "hmr": "auto"
}
```

**Comment by shlomitc** [comment]
still relevant

**Comment by shlomitc** [comment]
I have a suggestion.
If we don't do any stylesheet imports in our drivers - this won't be an issue.

As an alternative for testing class names or stylable states - let's just put arbitrary data attributes, for example, `data-style-disabled`.

Issues:
1. This is a testing only code that we put in our component. meh... don't think it's such a big thing.
2. We don't test anymore for actual style integration, it's just another attribute. This is a bigger thing, but I think that since we do a lot of visual tests - we're covered. Also, we can also have the style tests in some "private" driver and not expose them to consumers

**Comment by shlomitc** [comment]
still relevant

**Comment by NitayRabi** [comment]
Still relevant! 
@ranyitz @barak007 @tomrav - 
This is another symptom of the issue we saw running the StylableUtil in node env. 
this is caused due to running without loading `*.st.css` files correctly causing one of/or two issues - 
1. Expected results of importing `*.st.css` files is incorrect
2. Using `default` prop returns `undefined`.

**Comment by NitayRabi** [comment]
still relevant
