### ISSUE TITLE
Custom watchers

### ISSUE THREAD

**Issue by MikhailoKhraban** [wix/yoshi#1195]
# 🙋 Feature Request

It will be cool to have custom watchers. On custom folders. Right now I not found the possibility to customize this one.

### 🤔 Expected Behavior

Here I can see you apply it on src and dist and that is all. It will be cool to have some param in yoshi-config like:
```
WATCHERS => [
  {
     src: ['src1', 'src2', ...]
     dist: 'dist1',
  },
  {
     src: ['src3', 'src4', ...],
     dist: 'dist2',
  }
]
```

### 💁 Possible Solution 

Update code here: parse param and add watchers.
```/yoshi/src/commands/start-app.js:57```

### 🔦 Context

For DeviantArt it will help have a shared folder and not rebuild it manually.

**Comment by ranyitz** [comment]
@MikhailoKhraban Can you explain what is the problem that you're trying to solve?
