### ISSUE TITLE
Failed to run protractor tests

### ISSUE THREAD

**Issue by rudnitskih** [wix/yoshi#1214]
# 🐛 Bug Report

### 😯 Current Behavior

Running `yoshi test --protractor` raised the error:

![image](https://user-images.githubusercontent.com/8848858/55555176-4c5e5800-56ed-11e9-861c-358bf9610fb3.png)

### 🤔 Expected Behavior

e2e tests using protractor should pass 

### 💁 Possible Solution

Please Move `yoshi-runtime` from `devDependecies` to `dependecies` 
https://github.com/wix/yoshi/blob/master/packages/yoshi/package.json#L187

### 👣 Steps to Reproduce

I can create a separate branch in my project if you want.

### 🌍 Your Environment

yoshi v4.1.2

**Comment by ronami** [comment]
Thanks for the issue, should be fixed in a bit in #1226.

**Comment by ronami** [comment]
Closed in #1226. I'll release a new version in a bit.
