### ISSUE TITLE
SVG imported as `ReactComponent` don't have `viewBox` attribute

### ISSUE THREAD

**Issue by ipanasenko** [wix/yoshi#1229]
Original SVG:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
  <g transform="translate(4 4)" fill="currentColor">
    <polygon points="16 0 16 5 15 5 15 1.659 10.295 6.364 9.588 5.657 14.245 1 11 1 11 0"/>
    <polygon points="0 16 0 11 1 11 1 14.259 5.657 9.602 6.364 10.31 1.674 15 5 15 5 16"/>
  </g>
</svg>
```

SVG in DOM:
```svg
<svg width="18px" height="18px"><g fill="currentColor"><path d="M20 4v5h-1V5.659l-4.705 4.705-.707-.707L18.245 5H15V4zM4 20v-5h1v3.259l4.657-4.657.707.708L5.674 19H9v1z"></path></g></svg>
```

It should have `viewBox` as defined in original SVG

**Comment by ranyitz** [comment]
@ipanasenko I think that's an [SVGO feature](https://github.com/smooth-code/svgr/issues/142#issuecomment-406825005) 

About the reasoning - https://github.com/svg/svgo/blob/master/plugins/removeViewBox.js

What's the specific problem with removing the `viewBox` when there are `height` & `width`?

**Comment by ipanasenko** [comment]
When rendering inside WSR button, it looks bad and misaligned. Adding viewBox fixes it

**Comment by ipanasenko** [comment]
With viewBox:
![image](https://user-images.githubusercontent.com/576152/55720789-51334c80-5a0a-11e9-92f9-106dcf02f911.png)


Without viewBox:
![image](https://user-images.githubusercontent.com/576152/55720812-5c867800-5a0a-11e9-9bdb-3479a109ea9d.png)
