### ISSUE TITLE
[create-yoshi-app]: add support for .npmrc/.yarnrc in current folder

### ISSUE THREAD

**Issue by ipanasenko** [wix/yoshi#1231]
Hi! I get following error:
```
You should be authenticated to Wix's private registry
Run the following command and try again:

  npm config set registry http://npm.dev.wixpress.com
```

Even though I have .npmrc/.yarnrc in current folder with following content:
```
registry "http://npm.dev.wixpress.com"
"@wix:registry" "http://npm.dev.wixpress.com"
```

**Comment by ranyitz** [comment]
Hey @ipanasenko, this is the code that handles the registry check:

https://github.com/wix/yoshi/blob/10346e6c2fb074190af8ce5b35fc8168811f40bf/packages/create-yoshi-app/src/utils.js#L24-L32

It should have been working but...

![image](https://user-images.githubusercontent.com/11733036/56468375-1979cb00-6434-11e9-8f21-94c97511d106.png)

Looks like an npm bug.

______

The purpose of this check is the verify that you can access the private npm registry, which means that if you run `npm install` and can install internal Wix packages, then you can generate a project.

I agree that the fact that there is an `.npmrc` file there should be sufficient.

We can:
1. Solve this particular issue by checking `.npmrc` parse it or search for the Wix registry in the text there (before running `npm config get registry`)
2. Think about a better solution, similar to `npm ping`. To try access a thin private package, if you succeed, it means that you're authenticated, and it's much better than our current check.

Open for better solutions.
@ipanasenko What do you think?

**Comment by ipanasenko** [comment]
I like option 2 more.

But what if we don't check at all? Just let user install and if it fails - it fails

**Comment by ranyitz** [comment]
@ipanasenko It will waste our user's precious time. because it will fail in a more further step on the generation process.

If we could think of a better way to fail earlier or even not to fail at all, but to wait that the user will change the registry/go under vpn and continue, it would be better.
