### ISSUE TITLE
[create-yoshi-app]: don't install `@types/axios` in server typescript template

### ISSUE THREAD

**Issue by ipanasenko** [wix/yoshi#1232]
`npm WARN deprecated @types/axios@0.14.0: This is a stub types definition for axios (https://github.com/mzabriskie/axios). axios provides its own type definitions, so you don't need @types/axios installed!`

**Comment by ranyitz** [comment]
@ipanasenko I couldn't find any reference to `@types/axios`

![image](https://user-images.githubusercontent.com/11733036/56469178-da9d4280-643e-11e9-847c-0d085374af40.png)


Which probably means there's a transitive dependency somewhere.

I've installed client typescript project, but haven't seen it after running [qnm](https://github.com/ranyitz/qnm)

![image](https://user-images.githubusercontent.com/11733036/56469240-9bbbbc80-643f-11e9-8b60-20f3707ffe74.png)

_______________

Can you please provide a repro?

**Comment by ipanasenko** [comment]
Yeah, sorry, should've been more specific. I was creating a node app:

- `npx create-yoshi-app`
- picked "server"
- I see `@types/axios` in newly generated package.json

**Comment by ranyitz** [comment]
Ok, so it's just about removing it from the `devDependencies`.

PRs welcome :)

**Comment by ipanasenko** [comment]
https://github.com/wix/yoshi/pull/1237 ;)

**Comment by ranyitz** [comment]
Fixed on #1237
