### ISSUE TITLE
Allow provide own certificate for yoshi's CDN

### ISSUE THREAD

**Issue by yurynix** [wix/yoshi#1241]
# 🙋 Feature Request

Consider the following:
1. I don't want to disable security features of the browser
2. I create my own CA (i.e. via `mkcert -install`)
3. I create my own certificate by that CA for `localhost`.
4. I need now to tell yoshi to use that certificate instead of the ones in `yoshi/src/tasks/cdn/assets`

### 😯 Current Behavior

There is no option to provide custom cert for yoshi.

### 🤔 Expected Behavior

Make `yoshi.servers.cdn.ssl` to be either `true` or an `object` with
`cert`, `key`, and `passphrase` properties.

### 💁 Possible Solution 

...

### 🔦 Context 

...

**Comment by ranyitz** [comment]
Maybe we can create a certificate programmatically. We can store it in the cache and reuse it every time.

If this flow is possible it will be much better than requesting users to create their own certificate.

**Comment by ronami** [comment]
I think that in the future we should definitely create a certificate and approve it programmatically, similar to how mkcert does it (via ios' `security` bin). Until that happens, I think that adding Yoshi's certificate to your Keychain is a lot simpler than creating a way for Yoshi to accept custom certificates.

What do you think?

**Comment by yurynix** [comment]
> I think that adding Yoshi's certificate to your Keychain is a lot simpler than creating a way for Yoshi to accept custom certificates.

Thats a great idea!
1. We should change the certificate info to be more clear about where it came from *and* have a proper CN. (like - `subject= /C=IL/ST=Tel Aviv/L=Tel Aviv/O=Wix/OU=Yoshi/CN=localhost/emailAddress=yoshi-team@wix.com`)
2. On CDN startup, if in SSL mode, check if the cert is trusted:
```
➜  form-builder git:(master) ✗ security verify-cert -c ./node_modules/yoshi/src/tasks/cdn/assets/cert.pem
Cert Verify Result: CSSMERR_TP_NOT_TRUSTED
```
if not, prompt user we'll install it:
```
➜  form-builder git:(master) ✗ sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ./node_modules/yoshi/src/tasks/cdn/assets/cert.pem
Password:
```
now it's trusted:
```
➜  form-builder git:(master) ✗ security verify-cert -c ./node_modules/yoshi/src/tasks/cdn/assets/cert.pem                                                             
...certificate verification successful.
```
Our current cert info:
```
➜  form-builder git:(master) openssl x509 -noout -text -in ./node_modules/yoshi/src/tasks/cdn/assets/cert.pem
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 11141971337542326812 (0x9aa03be617cb5a1c)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=AU, ST=Some-State, O=Internet Widgits Pty Ltd
        Validity
            Not Before: Sep  2 13:30:24 2017 GMT
            Not After : Aug 31 13:30:24 2027 GMT
        Subject: C=AU, ST=Some-State, O=Internet Widgits Pty Ltd
...
```

However, even if we do that, apps, like chrome, will still refuse to trust self signed cert.
```
➜  form-builder git:(master) ✗ openssl x509 -subject -issuer -noout -in ./node_modules/yoshi/src/tasks/cdn/assets/cert.pem
subject= /C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
issuer= /C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
```

So for all of that to work we need to mimick `mkcert`:
1. create a root CA
2. create certificate
3. sign the certificate with root CA we created at (1)
4. add root CA to the keychain via `security`


```
# Root CA
OPENSSL_CONF_DIR=`/usr/bin/openssl version -a | grep 'OPENSSLDIR' | awk '{print substr($2,2,length($2)-2)   }'`
cp $OPENSSL_CONF_DIR/openssl.cnf ./openssl.cnf
cat <<EOT >>./openssl.cnf 

[ v3_ca ]
basicConstraints = critical,CA:TRUE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer:always
EOT

openssl req -config openssl.cnf -new -newkey rsa:4096 -x509 -days 1825 -extensions v3_ca -keyout rootCA.key -out rootCA.crt -subj "/C=IL/ST=TLV/O=Yoshi"


# localhost key + CSR
openssl req -new -sha256 -nodes -out localhost.csr -newkey rsa:2048 -keyout localhost.key -config <(
cat <<-EOF
[req]
default_bits = 2048
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn

[ dn ]
C=IL
ST=Tel Aviv
L=Tel Aviv
O=Fed Infra
OU=Yoshi CDN
emailAddress=yoshi-team@wix.com
CN = localhost

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = localhost
DNS.2 = www.localhost
EOF
)


# Sign localhost cert with Root CA
openssl x509 -req -in localhost.csr -CA rootCA.crt -CAkey rootCA.key -CAcreateserial -out localhost.crt -days 500 -sha256


# Add to keychain
sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain rootCA.crt


# Copy keys to CDN
cp localhost.key ../node_modules/yoshi/src/tasks/cdn/assets/key.pem 
cp localhost.crt ../node_modules/yoshi/src/tasks/cdn/assets/cert.pem 
```

**Comment by yurynix** [comment]
Even if we do all that, chrome still complains.
Firefox is the upper one, chrome the bottom one.

![Screen Shot 2019-05-23 at 11 02 19](https://user-images.githubusercontent.com/326402/58236224-1a5f8e80-7d4b-11e9-8cb3-732a8f1c1e39.png)


cURL likes it as well:
![Screen Shot 2019-05-23 at 11 09 14](https://user-images.githubusercontent.com/326402/58236312-5266d180-7d4b-11e9-8715-c60b9a25be65.png)

**Comment by yurynix** [comment]
After my talk with @ronami , 
I realised, that - on my CSR I had Alt SANs, but when I signed it to create the certificate, openssl dropped them, so the Alt SANs wasn’t present on the actual certificate.
I’ve figured a way to do it, and documented the steps here: https://gist.github.com/yurynix/229b2354d1dc15df6463ba5072020ea3
