### ISSUE TITLE
Deprecate `--entry-point` and `--server` on `yoshi start`

### ISSUE THREAD

**Issue by Schniz** [wix/yoshi#1259]
# 🙋 Feature Request (Breaking change! 💥 )

Deprecate `--entry-point=""` and `--server=""` in `yoshi start`, by using a hard-coded value: `index-dev.js`

### 😯 Current Behavior

`client` template now has the `start` calling `yoshi start --server=dist/server.js`:
https://github.com/wix/yoshi/blob/6ac24ae87243a27a18e4c94c6b330cf6c7768c4d/packages/create-yoshi-app/templates/client/javascript/%7B%25packagejson%25%7D#L11

`fullstack` template uses `index-dev.js`

That makes it hard to know which file to execute in order to start the server. We don't see any use case for having it as a configuration, and we'd like to remove ambiguity between templates and projects.

### 🤔 Expected Behavior

All projects will have `index-dev.js` that will be responsible on starting the project with testkits, etc:

* Projects that use plain `yoshi start`, can have `index-dev.js` just require `index.js`
* Client projects can move `dev/server.js` to `index-dev.js`
* Fullstack projects are already okay!

### 🔦 Context 

This is for implementing #914, `yoshi serve`, which is a stripped-down, "production-like" version of `start`.

cc @ranyitz

**Comment by ranyitz** [comment]
Nice!
I want to add some explanation to **why this is needed.**

In general, if an option is **not exclusive to one command** and does **not need to be changed between different runs**, it should be in the config.
______

Specifically here, doing this change will enable us to use `yoshi-config` in order to understand how we should run the server, and it will give us an easy way to figure out how to run `start` in the closest thing to production mode, or `yoshi serve`, without requiring the user to specify another command in his/her `scripts` property.

**Comment by Schniz** [comment]
Do we want to change this issue to `deprecate --server and --entrypoint`?

**Comment by Schniz** [comment]
So `yoshi start` and `yoshi serve` will both (pseudo code):

```js
if (fs.existsSync('<projectRoot>/index-dev.js')) {
  spawn("node index-dev.js");
} else if (fs.existsSync('<projectRoot>/index.js')) {
  console.error("Deprecation warning: The next version of Yoshi won't run `index.js` files automatically. Please add an `index-dev.js` file");
  spawn("node index.js");
} else if (entrypoint || server) {
  console.error("Deprecation warning: --entrypoint and --server will be removed on the next Yoshi version");
  spawn(`node ${entrypoint || server}`);
} else {
  throw new Error("I don't know what to run! Please add an `index-dev.js` file");
}

**Comment by Schniz** [comment]
@ranyitz I have updated this issue

**Comment by ranyitz** [comment]
Great @Schniz, Convention over configuration 🥇

**Comment by ranyitz** [comment]
Let's make this issue about removing the config on yoshi@5, and add a sub issue to deprecate them on version 4. @Gongreg can you take this?
