### ISSUE TITLE
rtl css ignore rtl control directives

### ISSUE THREAD

**Issue by noakorkus** [wix/yoshi#1261]
# 🐛 Bug Report

### 😯 Current Behavior 

Issue : rtl css ignore rtl control directives
1. First Issue : yoshi4
We are using yoshi 4 and loading <bundleName>.rtl.css in case of rtl language.
In some cases we want to change the rtl default outcome so we added  rtl control directives in our css (https://rtlcss.com/learn/usage-guide/control-directives/index.html) like this:

```
/*rtl:ignore*/
.root:alignment(left) {
  text-align: left;
}
```

The default behaviour of the rtl is to change the text-align to right and with the `/*rtl:ignore*/` it should leave it as `text-align:left`

After the CI build the outcome is:
`text-align: right;`

After local build the outcome is: (this is the expected behaviour)
`text-align: left;`

Both minify css and non minify css after CI build has the wrong outcome.
** This is relevant for rtl control directives.

2. Second issue : Yoshi 3
In Yoshi 3 we have the same issue with one difference 
The non minify file after the CI build is created as expected:
`text-align: left;` 

### 🤔 Expected Behavior 

After the CI build the outcome is:
`text-align: left;`

### 🔦 Context 

Support RTL language.
In Wix Bookings settings panel when user choose that text alignment is left we want it to stay left. This is why we added the rtl control directives.

### 💁 Possible Solution 

...

### 💻 Code Sample

https://github.com/wix-private/scheduler/blob/master/statics/viewer/bookings-widget/src/WidgetApp/components/OfferingInfo/OfferingInfo.st.css#L19

### 🌍 Your Environment

Yoshi 4 and Yoshi 3

```
// PASTE HERE
```

**Comment by D0vydas** [comment]
I have similar issue.

This one works (in rtl.css it stays as `text-align: left;`):
```
.left {
    /*!rtl:ignore*/
    text-align: left;
}
```

But this is ignored (it should replace value in rtl.css):
```
.some-class {
    flex-direction: row/*!rtl:row-reverse*/;
}
```
