### ISSUE TITLE
Remove scope packages migration task

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1264]
# 🐛 Bug Report

### 😯 Current Behavior

We have code in yoshi that migrate to scope packages although we've decided to stop doing that :)

### 🤔 Expected Behavior

Do not migrate projects to scope packages.

### 🔦 Context

We once wanted to move every package in Wix to be a scope package (NPM) but it didn't work well. [`@wix`]

### 💁 Possible Solution 

Remove the migration task with its dependencies.

### 💻 Code Sample

https://github.com/wix/yoshi/blob/d439317be2c471dd10d5c3b6b51007aad16cd946/packages/yoshi/src/commands/start.js#L87-L90

https://github.com/wix/yoshi/blob/d439317be2c471dd10d5c3b6b51007aad16cd946/packages/yoshi/src/commands/build.js#L53-L56

____________

@yairhaimo What do you think?

**Comment by yairhaimo** [comment]
Can remove, it was an opt in feature that was undocumented.
All packages are published as scoped in CI anyway.

**Comment by ranyitz** [comment]
@yairhaimo thanks, amazing.

PRs welcome, let's delete some code 🕳
