### ISSUE TITLE
deprecate tslint and move linting TypeScript projects with eslint

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1266]
# 🙋 Feature Request

### 😯 Current Behavior

Yoshi is using `tslint` in order to lint TypeScript projects.

### 🤔 Expected Behavior

Yoshi will use `eslint` in order to lint TypeScript projects.

### 🔦 Context

The [TSlint team announced on deprecating TSlint](https://medium.com/palantir/tslint-in-2019-1a144c2317a9) and move to eslint instead, not long ago, [create-react-app also added TypeScript eslint support](https://github.com/facebook/create-react-app/pull/6513) and you can look at it in order to take some inspiration.

I'm not sure if all the rules are supported, but I'm sure that it's the direction the community chose, and that one tool (instead of 2) will be better for the yoshi team and the users.

This change will need to be part of yoshi's next major version because It's hard to believe that we'll get to feature parity between tslint and eslint configs. There is currently a need for a static [`tslint.json`](https://github.com/wix/yoshi/blob/master/packages/create-yoshi-app/templates/client/typescript/tslint.json) file. We'll need to instruct devs to change it into an `eslint` equivalent.

**Comment by eranshabi** [comment]
here is my suggestion:
when running `yoshi lint`, if typescript project + has .eslintrc file `=>` run eslint on all ts files

it's not a breaking change so only those who migrated to eslint from tslint will get thie new behaviour.

right now we have to run eslint without yoshi but I'm willing to PR a fix if you approve.

**Comment by ranyitz** [comment]
Thanks @eranshabi! It sounds like a great idea.

Inserting non-breaking changes in minor versions when possible is a very good practice.

The migration would be as easy as you describe, just change your `tslint` configuration to `eslint` one, and Yoshi will use the linter that you've chosen.

**Note:** Yoshi is currently using `eslint@5` while the 6th version is already out, we'll upgrade it on the next major version.

@ronami @yavorsky @yanivefraim What do you think?

**Comment by yavorsky** [comment]
I like this idea. Actually I think it's the only way to move to eslint for typescript safe.

:+1:
