### ISSUE TITLE
Improve app-flow kitchensink tests developer experience

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1299]
We have a great `e2e` test suite that helps us verify that we don't break stuff when delivering new features and bug fixes.

While the testing infrastructure is well written and thought of, there are still some things that would improve the developer experience, spare time while debugging problems in those tests and help to add new tests in a correct way.

_________________

- [ ] Adding a readme file that explains what are those tests and how to work with them.
- [ ] Being able to focus on a specific suite or a test. while in each project (JavaScript/TypeScript) we have multiple suites (production-build, local-development, others) it would be nice to be able and focus just one of them. It would also be cool to focus on a specific feature.
- [ ] Separate between `JavaScript` & `TypeScript` runs. It takes a lot of time in the CI, and can be confusing when running locally.
- [ ] It seems that a lot of unrelated tests are failing after only one has fallen. It takes some time to understand. Maybe we can bail from a certain suite as a tradeoff so we won't see irrelevant and confusing errors.

In the following example, the first one is real and the others are not related to the main cause.
![image](https://user-images.githubusercontent.com/11733036/57984120-0244f200-7a61-11e9-93c4-63fd9c9c84ad.png)

**Comment by ranyitz** [comment]
After working on this infra when doing #1377 I want to add some more features that will help to achieve good developer experience in this testing infrastructure.

1. Have a **debug mode**, in this debug mode the following will happen:
	* Prevent yoshi start from deleting the output in the console.
	* Print the directory name of the test for debugging purposes
	* do not delete this directory at the end of the test so the user could go and debug stuff after the tests have been finished.
	* pipe the `stdio` of everything to the console (yoshi start/user server/etc...)
2. Being able to **focus a specific test** is crucial, this is a suggested solution:
	* Pass CLI arguments to inner jest configurations so we could filter a test by its name.
	* Run only the necessary setup for the chosen test (For example, if we chose a test that from the production jest config, run the build, but do not run start)
	* Run only the relevant projects for the chosen test (TypeScript/JavaScript)
3. Run the tests in **debug mode when filtering a test** (be able to undo this using an environment param (`DEBUG=false`) but still configure it as a default) 
4. Put all **app flow tests infra in one directory** (rather than scattered in `scripts`/`test` directories etc...). It's also important the places that we write which tests belong to which configuration will be in the same place. So it would be easy to view them together.

**Comment by yanivefraim** [comment]
I think that we can close this... @ronami @ranyitz , wdyt?

**Comment by ronami** [comment]
Definitely 😁
