### ISSUE TITLE
test:integration is getting really long

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1300]
Relativly to all other test suites, the `test:integration` is getting quite long.

![image](https://user-images.githubusercontent.com/11733036/57984566-b183c800-7a65-11e9-9194-4c0aa2f50d67.png)
![image](https://user-images.githubusercontent.com/11733036/57984569-ba749980-7a65-11e9-8962-6be7f3fc406d.png)

It is also very flaky. We should strive towards removing parts which are no longer necessary or delete the whole suite whatsoever by deprecating the old flow or move tests to the new kitchensink format, which tests better and faster.

________________

The easiest quick win would probably separate the integration into 2 suites, but the changes above seem to be inevitable.

**Comment by ronami** [comment]
Closed in #1402, 8ade92f5c3ba843e9cff9454e4f21ac329e878f5 and b1ceb774f433abba22621c0eaa32050d858002ba.
