### ISSUE TITLE
Have a proper example to dynamically loadable component in templates

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1309]
We want to promote the usage of dynamic import for heavy components.
After the creation of [`yoshi-template-intro`](https://github.com/wix/yoshi/pull/1258) we now have the heavy component we were waiting for 😆 

Currently, we use a [raw dynamic import](https://github.com/wix/yoshi/blob/master/packages/create-yoshi-app/templates/fullstack/javascript/src/components/App/App.js#L20) which works, but doesn't handle things like loading state/failures etc.

There are good solutions for this problem out there, for example:
https://github.com/smooth-code/loadable-components
https://github.com/jamiebuilds/react-loadable

We should find one that works best and modify the templates to use it.

**Comment by yavorsky** [comment]
We can use our `Loadable` component we are using for WSR.
https://github.com/wix/wix-ui/tree/master/packages/wix-ui-core/src/components/loadable

It contains most of the features we can achieve by using loadable components from links above, but also could handle `require`s as a sync action (using same tick to update it. We added it to not break tests which don't expect async flow).
Also, maybe we can proxy it via WSR and don't install additional dependency.
