### ISSUE TITLE
imported stylesheets in puppeteer is not hashed styles

### ISSUE THREAD

**Issue by adicicurel** [wix/yoshi#1329]
# 🙋 Feature Request

### 😯 Current Behavior

I am creating an e2e test using puppeteer, and trying to find if an element has a specific className, the class imported by the test is not the same as generated on the component

### 🤔 Expected Behavior

Importing classes using e2e test should have the same name as the class names in the browser.

### 💁 Possible Solution 

1. Importing classes using e2e test should have the same name as the class names in the browser.
2. Give a help function to generate the hashed classnames within the tests.

**Comment by ranyitz** [comment]
@adi-wix What is the difference between the imported class name (by the test) and the real one? Can you give an example?
