### ISSUE TITLE
windows support - create-yoshi-app

### ISSUE THREAD

**Issue by tzachvw** [wix/yoshi#1335]
# 🙋 Feature Request

### 😯 Current Behavior

On Windows 10, when running:
1. npx create-yoshi-app my-app
2. npm install
3. npm start
3. npx jest --watch

the output is:
"No tests found, exiting with code 1"

although there are tests in the porject.

...

### 🤔 Expected Behavior

tests should be running.

...

### 💁 Possible Solution 

...

### 🔦 Context 

...

**Comment by ranyitz** [comment]
Duplicate of #1345
