### ISSUE TITLE
Create Yoshi App - Wallaby is broken for setup files

### ISSUE THREAD

**Issue by carmelc** [wix/yoshi#1339]
In yoshi 4 preset (create-yoshi-app) I see that the setup files for tests (test-setup.ts) is under __test__ but wallaby only see them in test folder, 

Either configure wallaby to read it from __tests__ folder or generate them in test folder,

**Comment by ranyitz** [comment]
Thanks @carmelc 
PRs welcome for fixing those paths on the wallaby config :)

**Comment by Gongreg** [comment]
@ranyitz, this issue is solved.

**Comment by ranyitz** [comment]
Thanks @Gongreg, closing
