### ISSUE TITLE
CSS duplication in projects using import-once plugins

### ISSUE THREAD

**Issue by mastertheblaster** [wix/yoshi#134]
It happens if we try using https://github.com/wix-private/wix-base-ui
Cause they do use https://github.com/wix-private/wix-base-ui/blob/master/package.json#L71

**Comment by ranyitz** [comment]
@mastertheblaster is this still relevant?

If so, please elaborate

**Comment by mastertheblaster** [comment]
There are projects using `import-once` webpack plugin.
Consider the following project setup:

`common.scss`:
```sass
$width: 100px;
.common-class {}
```

`file1.scss`
```sass
import './common.scss';
.file1 {};
```

`file2.scss`
```sass
import `./common.scss`;
.file2 {}
```

So with a following setup now the classes from the common will be imported twice, and final bundle size will increase dramatically.

**Comment by ranyitz** [comment]
@mastertheblaster I still do not understand if there is a bug with something that we do in yoshi, or something is missing in yoshi, how can i recreate the problem and so on.

Can you use one of the formats - https://github.com/wix/yoshi/issues/new/choose ?

**Comment by mastertheblaster** [comment]
I don't know if this is a bug or feature request. I tend to believe it's a feature request. So will try to fill that template.

**Comment by mastertheblaster** [comment]
I guess this one https://github.com/wix/yoshi/issues/363 is better now.

**Comment by ranyitz** [comment]
Thanks @mastertheblaster Let's continue there
