### ISSUE TITLE
When running yoshi start, resources are not copied to dist dir

### ISSUE THREAD

**Issue by amiryonatan** [wix/yoshi#1352]
# 🐛 Bug Report

### 😯 Current Behavior

If I have an index.vm file in the src directory of a fullstack project, when I execute `yoshi start` the dist directory is removed, and the index.vm won't be copied into the statics directory.
if I put the file in `assets` dir then the entire dir will be copied to the statics dir.

### 🤔 Expected Behavior

static files should be copied to dist/statics.

### 🌍 Your Environment

```
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
    Safari: 12.1.1
  npmPackages:
    @storybook/core: Not Found
    @storybook/react: Not Found
    babel-preset-yoshi: ^4.0.0 => 4.1.0
    eslint-config-yoshi:  4.4.2
    eslint-config-yoshi-base:  4.4.2
    jest-environment-yoshi-bootstrap:  4.7.2
    jest-environment-yoshi-puppeteer:  4.7.2
    jest-yoshi-preset: ^4.0.0 => 4.7.2
    storybook: Not Found
    tslint-config-yoshi:  4.4.3
    tslint-config-yoshi-base:  4.4.3
    typescript: ^3.0.0 => 3.5.1
    webpack:  4.28.4
    yoshi-config:  4.7.2
    yoshi-helpers:  4.7.2
    yoshi-runtime:  1.0.112

 Yoshi config
{
  "projectType": "app",
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM",
    "lodash": "_",
    "@wix/repluggable": "repluggable",
    "@wix/fedops-logger": "fedopsLogger",
    "@sentry/browser": "Sentry"
  },
  "hmr": true,
  "servers": {
    "cdn": {
      "ssl": true,
      "port": 3300
    }
  }
}
```

**Comment by ronami** [comment]
Yoshi copies all assets inside the `src/assets` directory. Does it makes sense to put it inside that directory?

**Comment by amiryonatan** [comment]
I would expect the same behaviour from `yarn build` & `yarn start`.
Don't you think?

**Comment by ranyitz** [comment]
@amiryonatan I think this was discussed in the past. https://github.com/wix/yoshi/pull/1220#issuecomment-493073062

If you do think that it should be copied during start, can you explain some more about the context?

**Comment by amiryonatan** [comment]
we would like to have our `index.vm` under `src` directory.
but when we do that, we're unable to start our application, because in our local server code we run:
```
const vmContent = fs.readFileSync(
    path.resolve(__dirname, './statics/index.vm'),
    'utf8',
  );
```
this forces us to put the file under `assets` so we'll get it to the dist dir.

**Comment by ranyitz** [comment]
@amiryonatan I'll try to specify the pieces of information that are missing to me:

1. Is this a client project?
2. Is the code snippet that loads the `vm` file is used in production?

> we would like to have our index.vm under src directory.

3. Why is that?

> this forces us to put the file under assets so we'll get it to the dist dir.

Not necessarily, if that's a dev server, you could just load the `vm` file from `./src/index.vm` rather than from `./statics/index.vm`.
