### ISSUE TITLE
Add an automatic schema test for all of the config options

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1355]
## The problem

Today it's possible to add new config options without adding them to the [config's schema validation](https://github.com/wix/yoshi/blob/master/packages/yoshi-config/schema/yoshi-config-schema.js)

## Expected behavior

It won't be possible to add a new config option without adding a schema validation to it.

## Optional solution

Add a test that will run in the CI and will validate that all config options do not produce warnings when used.

An example of such a test would be to read [the config](https://github.com/wix/yoshi/blob/master/packages/yoshi-config/loadConfig.js) and generate a default config out of it. We could use this default config in an integration test to validate the config with all of its possible config options. We can fail the test in case there is any warning output, similarly to [this assertion](https://github.com/wix/yoshi/blob/master/packages/create-yoshi-app/scripts/e2e.js#L87-L97).

## Context

I've been working on #1351 and added a new config option. I've realized how easy is to forget adding schema options and break user's behavior.

**Comment by agankarin** [comment]
Is this issue still relevant after the TypsScript migration?
