### ISSUE TITLE
haste-preset-yoshi/debug/mocha.js is not appropriate for typescript projects

### ISSUE THREAD

**Issue by hepiyellow** [wix/yoshi#136]
_The problem:_

In the [debug mocha file](https://github.com/wix-private/wix-haste/blob/master/haste-preset-yoshi/debug/mocha.js), we look only for *.js{,x} files.
This mocha.js file is required by the VS code launch config which is generated by wix-js-stack.
[wix-js-stack's fullstack launch.json](https://github.com/hepiyellow/wix-js-stack/blob/master/generators/generator-wix-fullstack/src/templates/common/_vscode/launch.json) 

It should look for *.ts{,x} files

_Solutions_
The only thing we actually need from [debug mocha file](https://github.com/wix-private/wix-haste/blob/master/haste-preset-yoshi/debug/mocha.js), that we want haste to do for us,
is this mocha argument:
`'--require', './node_modules/haste-preset-yoshi/config/mocha-setup.js'`

All the rest ( file pattern, ENV variables, mocha args like timeouts, etc...) should be left to the user (not to haste).

1. We should create a file `mocha_config.js` and put in it only
`require(./node_modules/haste-preset-yoshi/config/mocha-setup')
This file allows writing a VS code launch config which is more flexible. 
2. Create a mocha_ts.js For those who don't use VS code.
And fix the Fullstack generator to use this file in a TS project.
```
Object.assign(process.env, {NODE_ENV: 'test', SRC_PATH: './src'});
process.argv = ['', '', '{test,src}/**/*.spec.ts{,x}', '--no-timeouts', '--require', './node_modules/haste-preset-yoshi/config/mocha-setup.js'];
require('../../mocha/bin/_mocha');
```

_While we're at it_
the required '[test-setup](https://github.com/wix-private/wix-haste/blob/6c26236a6594a978e22a19c3780c2b0962489cb5/haste-preset-yoshi/config/test-setup.js)' is overwriting the process.env, so there is no point in setting them in the [debug mocha file](https://github.com/wix-private/wix-haste/blob/master/haste-preset-yoshi/debug/mocha.js)

**Comment by ronami** [comment]
@hadar111 was this solved in #264?
