### ISSUE TITLE
Outdated CONTRIBUTING.md.

### ISSUE THREAD

**Issue by AndriiTsarenko** [wix/yoshi#1360]
# 🙋 Feature Request

### 😯 Current Behavior

`npm run test:templates` do not exist anymore. So we need to update CONTRIBUTING.md accordingly.

### 🤔 Expected Behavior

 CONTRIBUTING.md should be up to date.

### 💁 Possible Solution 

Would be great to have a brief explanation of every test script in `package.json` (what is it responsible for).
And what test can be `--watch`ed during developing some module. For quick feedback.
### 🔦 Context 

...

**Comment by ranyitz** [comment]
@AndriiTsarenko Thanks for opening this issue!

**Comment by ranyitz** [comment]
Solved on #1875

**Comment by ranyitz** [comment]
Also separate `package.json` scripts for extra clarity - https://github.com/wix/yoshi/pull/1877/files
