### ISSUE TITLE
angular-ng-annotate fails to annotate import/export

### ISSUE THREAD

**Issue by davydof** [wix/yoshi#1388]
# 🐛 Bug Report

### 😯 Current Behavior

![image](https://user-images.githubusercontent.com/10529679/59701640-b96a8f80-91fe-11e9-81ad-a6715f3dd556.png)

...

### 🤔 Expected Behavior

It works

### 👣 Steps to Reproduce 
`npm start`

### 💻 Code Sample
https://github.com/wix-a/yoshi4-angularjs

...

### 🌍 Your Environment

```
  System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 12.1.0 - ~/.nvm/versions/node/v12.1.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.1.0/bin/npm
    Watchman: Not Found
  Browsers:
    Chrome: Not Found
    Firefox: 66.0.2
    Safari: 12.1.1
  npmPackages:
    @storybook/core: Not Found
    @storybook/react: Not Found
    babel-preset-yoshi:  4.1.0 
    eslint-config-yoshi:  4.4.2 
    eslint-config-yoshi-base:  4.4.2 
    jest-environment-yoshi-bootstrap:  4.9.2 
    jest-environment-yoshi-puppeteer:  4.9.2 
    jest-yoshi-preset: ^4.1.0 => 4.9.2 
    storybook: Not Found
    tslint-config-yoshi:  4.4.3 
    tslint-config-yoshi-base:  4.4.3 
    typescript: Not Found
    webpack:  4.28.4 
    yoshi-config:  4.9.0 
    yoshi-helpers:  4.9.2 
    yoshi-runtime:  1.0.150 

 Yoshi config
{
  "projectType": "app",
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM",
    "@wix/fedops-logger": "fedopsLogger"
  },
  "hmr": "auto"
}
```

**Comment by ronami** [comment]
Thanks for the issue.

We're using `ng-annotate-loader` which uses `ng-annotate`.

`ng-annotate` is a deprecated and un-maintained package, and it uses an old version of Acorn (`2.6.4`). It parses files with the default Acorn options (https://github.com/olov/ng-annotate/blob/master/ng-annotate-main.js#L1077) and it parses files, by default, with `sourceType: "script"` (https://github.com/acornjs/acorn/blob/2.6.4/src/options.js#L14) which forbids EcmaScript modules.

One option is to fork `ng-annotate` and configure Acorn correctly. Another one is to use the equivalent Babel plugin, but then we lose TypeScript support.

**Comment by davydof** [comment]
@ronami 
I thought about to fork `ng-annotate` but this is not a proper solution.
