### ISSUE TITLE
Yoshi for Chrome extension development

### ISSUE THREAD

**Issue by audriuss** [wix/yoshi#1389]
# 🐛 Issue Report

### 😯 Current Behavior

There is no predefined way to use Yoshi for the chrome extension development.

### 🤔 Expected Behavior

Need to find a way how to properly set up Yoshi for the chrome extension development. For example while running `yoshi start`:
1) We need a fast way to get bundled JS and css. 
2) On each save it should rebuild it. 
3) We don't need a server.
4) We need to have `manifest.json` in dist folder
5) We need to generate `index.html` which would have proper script src for bundled JS and CSS
6) We need a proper way to test all scripts. 

### 🔦 Context 

We are starting to develop chrome extension which going to be not very trivial, so searching way how properly set up development environment. Yoshi has no predefined way to do this, so trying to adopt generated client application type project for this. Chrome extension actually is just bunch of JS scripts: background, content and popover for example. It has `manifest.json` where it's defined which script should be loaded and how. While developing we load extension as unpacked by selecting folder with files and `manifest.json` (Chrome -> extensions -> make sure "developer mode" is checked -> load unpacked -> choose this project's dist). 
One way is to bundle needed scripts as production ready and then load as unpacked extension, but it takes time. For development we want to have fast feedback, we don't want to wait for production ready builds every time we want to see changes in action.

### 💁 Possible Solution 

Currently while using app flow and `yoshi start`, as I understand css and js is bundled in `dist` folder and served via fake cdn, so was thinking to load these files as unpacked chrome extension (actually successfully did it). Wondering is this a right way to do it? Maybe there is other ways to do it?

### 💻 Code Sample

Our repo: https://github.com/wix-private/people-chrome-extension
### 🌍 Your Environment
```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: Not Found
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
    Watchman: Not Found
  Browsers:
    Chrome: Not Found
    Firefox: 62.0
    Safari: 12.1.1
  npmPackages:
    @storybook/core: Not Found
    @storybook/react: Not Found
    babel-preset-yoshi:  4.1.0 
    eslint-config-yoshi:  4.4.2 
    eslint-config-yoshi-base:  4.4.2 
    jest-environment-yoshi-bootstrap:  4.9.2 
    jest-environment-yoshi-puppeteer:  4.9.2 
    jest-yoshi-preset: ^4.1.0 => 4.9.2 
    storybook: Not Found
    tslint-config-yoshi:  4.4.3 
    tslint-config-yoshi-base:  4.4.3 
    typescript: Not Found
    webpack:  4.28.4 
    yoshi-config:  4.9.0 
    yoshi-helpers:  4.9.2 
    yoshi-runtime:  1.0.150 

 Yoshi config
{
  "entry": {
    "app": "./client.js",
    "background": "./background-scripts/background.js",
    "content": "./content-scripts/content.js"
  },
  "projectType": "app",
  "externals": {},
  "hmr": false,
  "splitChunks": false
}
```

**Comment by audriuss** [comment]
So, I have achieved to set up workable dev environment using "Client" type project. Sorry for repeating some details, but wanted to share the results and hoping that Yoshi team will consider to add/improve Yoshi in a way that would help to support Chrome extension development. 

Main things: 
- Loaded `/dist/statics` folder as unpacked extension in Chrome, so we get fast re-builded bundles on every save (using `npm start`). 
- Created custom script, which watches when `app.bundle.js` is made, in order to know when we can copy `manifest.json` and generate `index.html`. (Need this because dist is removed on every start)
- Created custom background script, which watches files change and reloads the extension in order to get something like HMR. 

Faced issues:
- dist folder is removed on every `npm start`. We need `manifest.json` in the dist folder, so we need a proper way to copy/generate it into `dist` folder after initial build is done after `npm start`.
- We need to generate an `index.html` which would have proper script src pointing to generated JS and CSS bundles.
- There is no HMR, or other fast way to refresh the extension.

Few insights that would help to improve even more:
- We don't need app server, although it's impossible to not run it with Yoshi
- Yoshi opens new tab on `npm start` with `http://localhost:3000/` which is not needed, since we don't need an app server
- `--no-server` cli param on `npm start` is not working and seems does nothing. Also seems there is a bug here https://github.com/wix/yoshi/blob/master/packages/yoshi/src/commands/start.js#L69 . Server cli arg is parsed as string, so it's impossible to be `=== false` as I understand.
- We don't need wixCdn server running
- We need a way to define copy task in Yoshi (to copy `manifest.json` to dist)
- We need a hook that would run after initial build is done on `npm start`

**Comment by ranyitz** [comment]
@audriuss, Thanks for opening this issue, I'm sorry it took so long to answer.

As far as I know, eveloping chrome extensions is not a very common use-case in Wix and therefore making sure Yoshi is working well for this type of development is not a top priority for us.

The Yoshi team can't concentrate on too many use-cases without losing the polish of the current ones. It's all tradeoffs in the end.

I think it's cool that you've made this effort, and I'm sure we'll use it in the future if we'll decide to target chrome extensions development.

**Comment by audriuss** [comment]
@ranyitz maybe there is any chance that Chrome extension flow could be added to the yoshi roadmap? Maybe it could be developed during guild weeks?

**Comment by ranyitz** [comment]
Hey @audriuss this is a really nice idea, and actually yoshi's architecture totally supports it.

Our problem with creating new flows is not the development of the flows, but **their maintenance**. We want to make sure that our team focuses on the features/flows which are the most used in Wix.

Currently, you are the only user that requested yoshi to create a dedicated flow for chrome extension development. If there would be more projects that needs it, it would make more sense for us to create and maintain it.

**Comment by audriuss** [comment]
@ranyitz  thanks for the answer! Yes, seems that Yoshi should support it. I do understand your point which is very valid :]
