### ISSUE TITLE
Can't generate a new project: `npm config set registry http://npm.dev.wixpress.com` does not work

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1403]
# 🐛 Bug Report

![image](https://user-images.githubusercontent.com/11733036/60192241-38367c80-983e-11e9-93eb-4dc5d8fca477.png)

### 😯 Current Behavior

The user creates an app, he gets a message that he needs to use the private registry, after running the command the user gets the same message.

### 🤔 Expected Behavior

Have an error message only when it is really needed and have a way to solve the problem and create an app 🎳 

### 🔦 Context

There are some places when this strategy is not working. (That I know of)
1. The registry is configured using `NPM_CONFIG_REGISTRY` environment parameter and it is different from the one that we expect in `create-yoshi-app`.
2. The registry is configured using a local npm config and it is different from the one that we expect in `create-yoshi-app`.

### 💁 Possible Solution

1. Check that this repo is either `http://npm.dev.wixpress.com` or `http://repo.dev.wixpress.com/artifactory/api/npm/npm-repos`

Right over here:

https://github.com/wix/yoshi/blob/10346e6c2fb074190af8ce5b35fc8168811f40bf/packages/create-yoshi-app/src/verifyRegistry.js#L9

2. Ping the registry and see if there is a connection (instead of checking npm config). This would be a much better test in any case and should ignore such cases of different urls to the same registry.

(While `npm ping` is not implemented on our local registry, it's possible to just check a small library that we know exist only there 💇‍♂ )

**Comment by ranyitz** [comment]
> We can combine the two (#1415):

> 1. Always install using the private registry
> 2. Try to ping the registry and fail with a relevant error message (instead of checking string equality)

**Comment by Gongreg** [comment]
@ranyitz seems like the issue wasn't closed even though it was solved in #1419 .

**Comment by ranyitz** [comment]
Thanks, you are right. closing
