### ISSUE TITLE
Remove `--ssl` and `--https` cli options 

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1409]
# 🐛 Bug Report

### 😯 Current Behavior

There are currently two ways to configure `webpack-dev-server` (e.g. local CDN) to serve assets on `https`/`ssl`.

One way is via a command line parameter (`--ssl`/`--https`) and the other is via the Yoshi config `servers.cdn.ssl`.

The first (with CLI parameters) is confusing because it implies that the app server will run on `https` as well (while that is not true).

Another problem is that Webpack public path is configured via the Yoshi config `servers.cdn.ssl` option, and therefore does not configure correctly (causing dynamic imports and other assets managed by Webpack to fail.)

https://github.com/wix/yoshi/blob/07542070cad3f0eab57e3cf75c4acf6b22363d0b/packages/yoshi/config/webpack.config.js#L83

### 🤔 Expected Behavior

There is one way to configure your CDN to run over `https`. preferably using yoshi config.

**Comment by Gongreg** [comment]
Hey @ranyitz,
I could work on removing the ssl/https flags from cli.
Wouldn't that theoretically be a breaking change?
But as you said the https/ssl option is redundant.
Maybe it should be simply ignored in v4 and removed in v5?

**Comment by ranyitz** [comment]
@Gongreg Thanks for your offer to help with it!

You are correct, that would be a breaking change.
It is currently targeted as a feature for v5, we have a milestone where are keep track on those features.

When we'll start working on version 5 (hopefully soon) we'll create a branch for it and we'll start adding those breaking changes to it while keeping it up to date with the current version.

After the release we'll merge this branch with master and continue development on it.

I'll let you know when it'll be relevant to work on this feature! 🙏

**Comment by Gongreg** [comment]
Pr is released.
