### ISSUE TITLE
When creating a library, stylable doesn't work. Can't use wix-ui-tpa

### ISSUE THREAD

**Issue by henrykuzmick** [wix/yoshi#1412]
# 🐛 Bug Report

### 😯 Current Behavior

When creating a new project using the `library` option stylable isn't setup. We can't tweak webpack, so can't add stylable by ourselves either. 
If the library is for a reusable component, there's a good chance you'd need something like `wix-ui-tpa`, which is impossible to add now.

### 🤔 Expected Behavior

Stylable should work out of the box.

### 🔦 Context 

We were making a badges library / reusable component for members and forum (https://github.com/wix-private/app-market/tree/master/badges/members-badge-lib)
In one case we should use a tooltip, and we should use `wix-ui-tpa`, but were unable to import it. 
Ended up with writing our own tooltip for this, but of course, that's not the best option.

### 🌍 Your Environment
  System:
    OS: macOS 10.14
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: Not Found
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: Not Found
    Firefox: 61.0.2
    Safari: 12.0
  npmPackages:
    @storybook/core:  5.0.11
    @storybook/react: 5.0.11 => 5.0.11
    babel-preset-yoshi:  4.1.0
    eslint-config-yoshi:  4.4.2
    eslint-config-yoshi-base:  4.4.2
    jest-environment-yoshi-bootstrap: Not Found
    jest-environment-yoshi-puppeteer: Not Found
    jest-yoshi-preset: Not Found
    react-scripts:  2.1.0
    storybook: Not Found
    tslint-config-yoshi:  4.4.3
    tslint-config-yoshi-base:  4.4.3
    typescript: 3.0.1 => 3.0.1
    webpack:  4.35.0
    yoshi-config:  4.9.0
    yoshi-helpers:  4.9.0
    yoshi-runtime:  1.0.144

 Yoshi config
{
  "hmr": "auto"
}

**Comment by ranyitz** [comment]
Stylable should work out of the box, please see https://github.com/wix/yoshi/blob/master/packages/yoshi/config/webpack.config.js#L743-L754.

Webpack runs on the app (not on the library itself).

> Stylable should work out of the box.

Can you describe how you expect Yoshi and Stylable to behave? What is the expected input/output?
