### ISSUE TITLE
[CYA] Always install from private registry instead of showing an error

### ISSUE THREAD

**Issue by ronami** [wix/yoshi#1415]
### Summary

Currently, running `npx create-yoshi-app` while not being configured with the private registry results in an error and requires you to run it again (and also install `create-yoshi-app` again). Instead, we can spawn the `npm install` command with the private registry for a better flow.

**Comment by ranyitz** [comment]
Great idea,

Related to #1403 

We can combine the two:

1. Always install using the private registry
2. Try to ping the registry and fail with a relevant error message

Let's continue on #1403 to prevent duplication
