### ISSUE TITLE
undocumented breaking change in yoshi 4

### ISSUE THREAD

**Issue by vybu** [wix/yoshi#1432]
Hi we updated from yoshi 3 to 4 and and the bundle naming changed. On 3 the chunk css files were named `chunkName.css`, now it's `chunkNane.chunk.css`.

This is a breaking change, seems not documented in migration guide.

Another thing is that naming is inconsistent now:
`appCommons.chunk.css`
`appCommons.rtl.css` -> would expect this to be `appCommons.chunk.rtl.css`

**Comment by ranyitz** [comment]
@vybu Thanks for opening this issue! I agree about both. The first can be solved by updating the migration guide. The second one can be changed by doing a PR, but would be a breaking change as well, so I would open it as a separate issue for discussion, and specifically talk about whether we should change it for yoshi@5.

Would you have the time to do those?
