### ISSUE TITLE
Mocha tests are triggered by dist change

### ISSUE THREAD

**Issue by astrauka** [wix/yoshi#144]
Steps to reproduce:
* start mocha tests in watch mode for a single file
* start development server `yarn start`
* watch the test runs to repeat while build is in progress

**Comment by shlomitc** [comment]
How do you run mocha for a single file?
And why do you need this use case when developing? Running `yarn start` will run the tests for you.

**Comment by astrauka** [comment]
@shlomitc 
> How do you run mocha for a single file?

```
./node_modules/mocha/bin/mocha spec_name --reporter mocha-env-reporter --watch
```
> why do you need this use case when developing?

It behaves the same as with `yarn test:client --watch` + having `.only` defined on a test, just no need to edit the code.

Now I see the test repeated only once, so it's ok to close the issue.
