### ISSUE TITLE
yoshi build --cdn=http://example.com

### ISSUE THREAD

**Issue by davydof** [wix/yoshi#1453]
# 🙋 Feature Request
Add cli-argument to `yoshi build` task to change the cdn.

### 😯 Current Behavior
To serve the fullstack app I should do `yoshi build` to build the TS code in JS and after do `node dist/src/server.js` or serve it with [pm2](http://pm2.keymetrics.io/).

And it builds with chunks.
In the bundle file `dist/statics/app.bundle.js` webpack created line with default cdn url and port:
```
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "http://localhost:3200/";
```

Locally I want default cdn and on remote server I need another cdn to serve the app and get correct links to the chunks in the `app.bundle.js`.

### 🤔 Expected Behavior
`yoshi build --cdn=http://example.com:1234`

In the bundle file `dist/statics/app.bundle.js` webpack created line with default cdn url and port: `/******/ 	__webpack_require__.p = "http://example.com";`

### 💁 Possible Solution 

Add cli-argument to `yoshi build`:
`--cdn`
e.g.:
```
yoshi build --cdn=http://example.com:1234
```

### 🔦 Context 

Probably Yoshi has another flow to serve the full-stack app.

Thank you.

**Comment by ranyitz** [comment]
@davydof If I understand correctly, you want a way to configure the static [`publicPath`](https://webpack.js.org/guides/public-path/).

Maybe this issue is relevant https://github.com/wix/yoshi/issues/914#issue-399706753?

If not, please share some more context regarding why you want to change the static public path by configuration.

**Comment by davydof** [comment]
@ranyitz 
yes, I want to configure the public path
yes, seems like it's relevant to #914

**Comment by ranyitz** [comment]
@davydof ok cool, would it be ok that I'll close this issue in favor of #914? It will be easier to manage like that.

**Comment by davydof** [comment]
@ranyitz yes, but please push #914 to your roadmap :-)

**Comment by ranyitz** [comment]
Cool, closing 👍
