### ISSUE TITLE
OOI Template TypeScript, Can not change button background color from settingsPanel. 

### ISSUE THREAD

**Issue by eran-gottlieb** [wix/yoshi#1455]
# 🐛 Bug Report

### 😯 Current Behavior

1. create-yoshi-app ooi-demo and choose Out-Of-Iframe template with TypeScript transpiler 
2. Run project (npm start), open settings and change Button Background color.
3. Result: Button background color does not change. 

### 🤔 Expected Behavior

1. create-yoshi-app ooi-demo and choose Out-Of-Iframe template with TypeScript transpiler 
2. Run project (npm start), open settings and change Button Background color.
3. Result: Button background color changes as defined in settings. 

### 🔦 Context 

...

### 💁 Possible Solution 

Copy Widget.st.css from the JavaScript template (missing css rules in TypeScript template)  

### 💻 Code Sample

...

### 🌍 Your Environment

```
➜  ooi-demo git:(master) ✗ npx yoshi info

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.10.0 - /usr/local/bin/npm
    Watchman: Not Found
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: Not Found
    Safari: 12.1.1
  npmPackages:
    @storybook/core: Not Found
    @storybook/react: Not Found
    babel-preset-yoshi:  4.1.0 
    eslint-config-yoshi:  4.9.5 
    eslint-config-yoshi-base:  4.4.2 
    jest-environment-yoshi-bootstrap:  4.10.1 
    jest-environment-yoshi-puppeteer:  4.10.1 
    jest-yoshi-preset: ^4.6.3 => 4.10.1 
    storybook: Not Found
    tslint-config-yoshi:  4.4.3 
    tslint-config-yoshi-base:  4.4.3 
    typescript: ^3.2.2 => 3.5.3 
    webpack:  4.28.4 
    yoshi-config:  4.10.1 
    yoshi-helpers:  4.10.1 
    yoshi-runtime:  1.0.157 

 Zero config 🛴

```

**Comment by ranyitz** [comment]
@eran-gottlieb Thanks for opening this issue! 👍 

Would you have the time to create a PR that fixes it? (Let me know if I can help in any way)

**Comment by deanshub** [comment]
hey @eran-gottlieb started to work on that and I'm not sure if I get the issue,
currently I can change the background color of the button and see the change in the editor
![image](https://user-images.githubusercontent.com/2688676/65127459-1f360580-da00-11e9-9e63-e0b91f91a342.png)
but I can't see the changes in the viewer since I don't publish the site
![image](https://user-images.githubusercontent.com/2688676/65127554-50aed100-da00-11e9-99c2-7b12f08ec227.png)
which seems to be the proper behaviour

**Comment by ranyitz** [comment]
Closing. We can open in case this is still an issue
