### ISSUE TITLE
TypeScript migration tracking issue

### ISSUE THREAD

**Issue by ronami** [wix/yoshi#1462]
### Summary

This goal of this issue is to help us track which packages have migrated to TypeScript. We would love to get help from the community with the migration.

This PR is a continuation of #1401 which describes why we decided to migrate.

#### List of packages

|Package|Owner|PR|Status|
|-------|-----|--|------|
|~`babel-plugin-transform-hmr-runtime`~|||~Not relevant~|
|~`babel-preset-yoshi`~|||~Not relevant~|
|~`bootstrap-hot-loader`~|@ronami|#1447|**Merged**|
|~`create-yoshi-app`~|@amitdahan|#1598|**Merged**|
|~`eslint-config-yoshi`~|||~Not relevant~|
|~`eslint-config-yoshi-base`~|||~Not relevant~|
|`jest-yoshi-preset`|@yanivefraim|#1473|Up for grabs|
|~`stylelint-config-yoshi`~|||~Not relevant~|
|~`tslint-config-yoshi`~|||~Not relevant~|
|~`tslint-config-yoshi-base`~|||~Not relevant~|
|`yoshi`|||Up for grabs|
|~`yoshi-angular-dependencies`~|||~Not relevant~|
|~`yoshi-config`~|@ronami|#1401|**Merged**|
|~`yoshi-helpers`~|@ronami|#1463|**Merged**|
|~`yoshi-style-dependencies`~|||~Not relevant~|
|`yoshi-template-intro`|||Up for grabs|

#### How to migrate

Because Yoshi is a monorepo, we have dependencies between packages. To avoid having to define types for JavaScript packages, we will start by migrating leaf packages (without dependencies) and then walk up the dependency tree until everything is migrated.

1. Start by claiming a package in this issue.
2. Copy `tsconfig.json` from an already migrated package.
3. If the package you're migrating have dependencies on another package in this repo, use `references` (See [project references](https://www.typescriptlang.org/docs/handbook/project-references.html)).
4. Rename all files with `js` extension to `ts` (or `tsx` if they have jsx in them).
5. Change all `ts` files to use EcmaScript modules instead of CommonJs (Use [Lebab](https://github.com/lebab/lebab) to make it easier).
6. Make sure tests, type-checking and lint pass.
7. Open up a PR and comment on this issue.

Hope this goes smoothly.

**Comment by amitdahan** [comment]
Hey guys! What's the plan regarding `scripts` folders?
Some are outside any of the sub-packages, some are in.
What's should our approach for these types of files be (specifically during our migration)?

Naive approach would be to include them inside `src` and then run scripts (only after a `tsc` has been run) from `build/scripts`.
Wdyt?

**Comment by ronami** [comment]
> Hey guys! What's the plan regarding `scripts` folders?
> Some are outside any of the sub-packages, some are in.
> What's should our approach for these types of files be (specifically during our migration)?
> 
> Naive approach would be to include them inside `src` and then run scripts (only after a `tsc` has been run) from `build/scripts`.
> Wdyt?

I think it depends on the use case, in the case of https://github.com/wix/yoshi/blob/master/packages/create-yoshi-app/package.json#L18, I think we can use [ts-node/register](https://github.com/TypeStrong/ts-node#programmatic), similar to how it's used for Mocha, or we can even keep those files as JavaScript files.

**Comment by ranyitz** [comment]
This issue was very successful as now the only `js` module we have is `yoshi-flow- legacy` the developer experience, ease of making broad changes and readability of the code improved a lot!!

Great work and thanks to everyone who invested their time and effort in this! ❤️

____________

Special thanks to @ronami on the great initiative and big part of the migration work. 🏆
