### ISSUE TITLE
Linked yoshi projects are not rebuilding when dependency project is changed

### ISSUE THREAD

**Issue by talbenmoshe** [wix/yoshi#1466]
# 🐛 Bug Report

### 😯 Current Behavior

When linking 2 Yoshi projects A and B and starting them both on "watch" mode.
Package B is not rebuilt when A changes

### 🤔 Expected Behavior

Project B will detect the changes in package A and rebuild itself

### 🔦 Context 

Using lerna to link several packages, I'd like to be able to run them all together and that changes in one package will affect dependent packages

### 💁 Possible Solution 

Add something like:
```

      const aaa = debounce(
        () => {

          appServer();
        },
        500,
        { maxWait: 1000 }
      );

      watch({ pattern: 'node_modules' }, async () => {
        aaa();
      });
```
To Yoshi's start script

**Comment by ronami** [comment]
I'm sorry for the long time it took me to respond.

Can you please explain about the two packages? How does package B consume package A? I assume package A is a library (not using app-flow, with every file built separately to `dist`) and package B being an app and uses `projectType: app` and gets bundled with Webpack. With that setup, Webpack's watch should trigger when package A changes.

**Comment by talbenmoshe** [comment]
Seems like you got it exactly right 😃 
Although the project type shouldn't matter.
If  **C** depends on **B** that depends on **A** then if I make a change in **A** - I want **B** to rebuild and then **C** will also rebuild automatically.

**Comment by ronami** [comment]
How each package is built? What is its output? Webpack or Babel/TypeScript separately? If A and B are built as a library (Babel/TypeScript separately) and C is an app (built with Webpack) then C should be built whenever either of them is changed. B however will not be built if A changes.

Is that your use-case? Can you please explain it?

**Comment by talbenmoshe** [comment]
Here is a concrete example. Please look at this: https://github.com/wix-private/photography/tree/master/logo-builder/zoe-editor

In the packages folder there are 3 projects: `zoe-editor-client` (App) that depends on `zoe-editor-view` (library) that depends on `zoe-editor-core` (library).
They are all managed by lerna.

All are Yoshi projects using babel.
All of them are linked and I'm running them in parallel. I'd like that when I change `zoe-editor-core` then `zoe-editor-client` will be rebuilt and automatically refresh the UI on the client.

The way I do it now, is to run some custom script I made called `dependency-watcher.js` that watches all of the libs and when they change, it writes a dummy.js file to `zoe-editor-client` making it rebuild.

**Comment by talbenmoshe** [comment]
@ronami , Do you need any more info?
