### ISSUE TITLE
Importing JSON files in typescript breaks jest (but works fine) in yoshi 4

### ISSUE THREAD

**Issue by liorcode** [wix/yoshi#1511]
# 🐛 Bug Report

### 😯 Current Behavior

Importing a JSON file in a typescript file like this: `import links from './articles-links.json';` works fine (even though `esModuleInterop` is off), but causes tests using `links` to fail (`links` is undefined in tests environment).

On the other hand, changing the import to `import * as links from './articles-links.json';` will fix the tests, but will break the app in run time.

### 🤔 Expected Behavior

`import` should behave the same in both tests and runtime.
I expect that with `esModuleInterop` off, json imports would work with the `import * as` syntax, as documented in typescript docs. (but behaving the same as in runtime is also a possible solution..)

### 💁 Possible Solution 

I assume the reason is that in the real app webpack and babel is bundling the json and works without default imports, while in tests, ts-jest doesn't go through babel/webpack and requires the `import * as` syntax.

### 💻 Code Sample

This test will fail:
https://github.com/wix-private/promote/blob/f32f01390dec698f01de0a64adbff4b7077d5653/promote-campaigns-manager/promote-campaigns-manager/src/client/stores/links.spec.ts

### 🌍 Your Environment

Relevant typescript configuration
```
"resolveJsonModule": true,
"esModuleInterop": false,
"allowSyntheticDefaultImports": true,
```
Yoshi info:
```
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  Binaries:
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
    Watchman: Not Found
  Browsers:
    Chrome: Not Found
    Firefox: 63.0
    Safari: 12.1.2
  npmPackages:
    @storybook/core: Not Found
    @storybook/react: Not Found
    babel-preset-yoshi:  4.10.2
    eslint-config-yoshi:  4.11.1
    eslint-config-yoshi-base:  4.4.2
    jest-yoshi-preset: ^4.11.1 => 4.11.1
    storybook: Not Found
    tslint-config-yoshi:  4.11.1
    tslint-config-yoshi-base:  4.4.3
    typescript: ^3.5.3 => 3.5.3
    webpack:  4.28.4
    yoshi-config:  3.31.0
    yoshi-helpers:  4.11.1
    yoshi-runtime:  1.0.223

 Yoshi config
{
  "entry": {
    "bm-module": "client/bm-module",
    "bm-component": "client/bm-component"
  },
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM",
    "react-module-container": "reactModuleContainer",
    "@sentry/browser": "Sentry",
    "@wix/business-manager-api": "BusinessManagerAPI"
  },
  "hmr": "auto"
}
```

**Comment by EvertonSA** [comment]
Hi, can this issue be oppened again?

**Comment by ranyitz** [comment]
Yes @EvertonSA, @liorcode.

Sorry that no one has got to this issue yet.

Can one of you [include a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff) ?

**Comment by BenjaminBorlet** [comment]
I have the same issue, just import any json, i wont work in test env

**Comment by ranyitz** [comment]
>  just import any json, i wont work in test env

@BenjaminBorlet I just tried to import a json file from a newly generated client TypeScript project.

![image](https://user-images.githubusercontent.com/11733036/77410257-4c0a1180-6dc3-11ea-985a-bcd10cea4c39.png)

If you want this issue to be solved [include a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff).

**Comment by xontik** [comment]
I think a found my problem :
`
module.exports = {
  testMatch: ['**/+(*.)+(spec|test).+(ts|js)?(x)'],
  testPathIgnorePatterns: ['environment.test.ts'],
  transform: {
    '^.+\\.(ts|js|html|json)$': 'ts-jest'
  },
  resolver: '@nrwl/jest/plugins/resolver',
  moduleFileExtensions: ['ts', 'js', 'html'],
  coverageReporters: ['html']
};
`

I didn't have the "json" part int the transform pattern
