### ISSUE TITLE
Two assets with the same name override each other

### ISSUE THREAD

**Issue by ronami** [wix/yoshi#1524]
### Summary

Since #1020 we changed our static assets names to not include any unique hash (https://github.com/wix/yoshi/blob/master/packages/yoshi/config/webpack.config.js#L77). This causes two assets in two different directories to have one override the other.

We should add a hash to static file names with `[hash]`, similar to how it's done in https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L381.

**Comment by asaf-yonay** [comment]
@ronami / @deanshub hey - can we prioritise this? @yaronshavit says it's a blocker on their part. :)

**Comment by ronami** [comment]
> @ronami / @deanshub hey - can we prioritise this? @yaronshavit says it's a blocker on their part. :)

Just merged thanks to @deanshub, I'll release in a bit and update @yaronshavit.
