### ISSUE TITLE
Flaky test in app-flow tests (hmr for web-worker)

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1528]
The web-worker `hmr` test is a very flaky test:

**Test** - https://github.com/wix/yoshi/blob/master/test/projects/kitchensink-javascript/integration/hmr.test.js#L102

**Failing build** - http://pullrequest-tc.dev.wixpress.com/viewLog.html?buildId=4566204&buildTypeId=Yoshi_TestAppFlow&tab=buildLog&_focus=2681#_state=1119

**Another failing build** - http://pullrequest-tc.dev.wixpress.com/viewLog.html?buildId=4562665&buildTypeId=Yoshi_TestAppFlow&tab=buildLog&_focus=2688#_state=1120

**Comment by yanivefraim** [comment]
Not relevant anymore
