### ISSUE TITLE
wix-bootstrap-renderer brings an older version of yoshi-config

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1537]
# 🐛 Bug Report

### 😯 Current Behavior

When trying to migrate a fullstack project to use the brand new `yoshi-server` and trying to use a route function there is an error in the browser:

![image](https://user-images.githubusercontent.com/11733036/64729905-d0abd700-d4e6-11e9-8b16-7600832374d3.png)

**tl:dr**
The version of `yoshi-config` which gets installed in the root of the `node_modules` is version `3.31.0` which comes from `@wix/wix-bootstrap-renderer`.

https://github.com/wix-private/fed-infra/blob/b6823cf446ace650a8aef5a690cf2c08d30ff3b1/wix-bootstrap-renderer/package.json#L32

### 🤔 Expected Behavior /  💁 Possible Solution

1. Maybe we can validate the version of `yoshi-config` in the root to make sure it's ok.
2. Maybe we should load the version of `yoshi-config` starting from the yoshi directory using something like https://github.com/sindresorhus/import-from
3. Maybe we should stop using `yoshi-config` in wix-bootstrap-renderer.

**Comment by yanivefraim** [comment]
I actually could not reproduce this one. There is no error, plus, checking with `qnm`:

```
yoshi-config
├── 4.28.3
└─┬ @wix/wix-bootstrap-renderer
  └── 3.31.0
```

WDYT?

**Comment by ranyitz** [comment]
I'm not exactly sure why, but my guess is that now we get more than one dependency on `yoshi-config@4.28.3` (it's possible to check it using `qnm yoshi-config --why`)

If that's the case then this issue is no longer relevant, we can open again in case we see this error.
