### ISSUE TITLE
Weird log in the console when using render in a route function

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1538]
# 🐛 Bug Report

### 😯 Current Behavior

After running npm start and navigating to a route in a fullstack app, we get this in the console:
 
(Looks like the content of the `ejs` template)

![image](https://user-images.githubusercontent.com/11733036/64730549-419fbe80-d4e8-11e9-8474-472271f460c3.png)

### 🤔 Expected Behavior

The console should be kept clean :0

### 👣 Steps to Reproduce

```sh
git clone git@github.com:wix-a/yoshi-server-migration.git
cd yoshi-server-migration
npm install
npm start

// Go back to console and see the log
```

**Comment by yanivefraim** [comment]
This issue is caused by the `debug: true` flag that we added to the demo project, as part of the render model.

It is by `ejs` design , see https://github.com/tj/ejs#options:


> - `debug` Output generated function body


For example:

```
await ejs.renderFile('./src/templates/app.ejs', { debug: false });
```

Will output the following log:

```
var __line = 1
  , __lines = "<div></div>\n"
  , __filename = "./src/templates/app.ejs";
try {
  var __output = "";
  function __append(s) { if (s !== undefined && s !== null) __output += s }
  with (locals || {}) {
    ; __append("<div></div>\n")
    ; __line = 2
  }
  return __output;
} catch (e) {
  rethrow(e, __lines, __filename, __line, escapeFn);
}
```

**Comment by ranyitz** [comment]
I see, thanks for the research, closing
