### ISSUE TITLE
Ability to use ContextReplacementPlugin

### ISSUE THREAD

**Issue by Faradey27** [wix/yoshi#156]
Currently we have moment and some other libs that provide by default things that we don't really need them all and as a result we have 200kb+ of extra data in our bundles, contextReplacmentPlugin can solve this problem.

https://stackoverflow.com/questions/25384360/how-to-prevent-moment-js-from-loading-locales-with-webpack

How to use
(package.json)
```
yoshi: {
   contextReplacmentPluginRegexp: regex
}
```

**Comment by ronami** [comment]
@Faradey27 moment.js is already being handled. I don't think allowing users to pass regex to webpack's contextReplacmentPluginRegexp is a good idea. We should configure yoshi to specific problems with certain libraries like we did with moment.js.

If I didn't understand it correctly, please re-open :)
