### ISSUE TITLE
Yoshi build fails on annotating es6 modules. 

### ISSUE THREAD

**Issue by maxaon** [wix/yoshi#1579]
# 🐛 Bug Report

### 😯 Current Behavior

Build fails on annotating js files with esnext modules (import and export) 

Fails with error: 
```
ERROR in ./client.js
Module build failed (from ../node_modules/yoshi-angular-dependencies/ng-annotate-loader.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) error: couldn't process source due to parse error,'import' and 'export' may appear only with 'sourceType: module' (2:0)
    at runLoaders (/home/peterk/projects/test-angular/node_modules/webpack/lib/NormalModule.js:312:13)
    at /home/peterk/projects/test-angular/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/peterk/projects/test-angular/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at Object.context.callback (/home/peterk/projects/test-angular/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.module.exports (/home/peterk/projects/test-angular/node_modules/ng-annotate-loader/loader.js:87:10)
```
### 🤔 Expected Behavior

Files must be annotated, event if it's es6 modules. All other features should be working ( like tree shaking and etc) 

### 🔦 Context 

Becasue of this, we cannot upgrade to yoshi 4. And youshi 3 stared to fail during start  and it's impossible to develop anything. 

### 💁 Possible Solution 

1. Use [babel-plugin-angularjs-annotate](https://github.com/schmod/babel-plugin-angularjs-annotate). I think it's preferable way.
2. Use [ng-annotate-patched](https://github.com/bluetech/ng-annotate-patched#readme)

Also it should annotate in files in TS flow. 

### 👣 Steps to Reproduce 

Demo project [test-angular](https://github.com/wix-a/test-angular)

### 💻 Code Sample

```javascript
import angular from 'angular';

angular.module('test', [])
  .factory('test', $http => () => $http.get('as'));
```

**Comment by ronami** [comment]
Thanks for the issue, I think it's a duplicate of https://github.com/wix/yoshi/issues/1388#issuecomment-503987247. I don't think there's a lot we can do about it other than maintaining a fork.

**Comment by maxaon** [comment]
@ronami No need to maintain. There is already  ng-annotate-patched which has all needed support. And it seems i need it already for 2 projects

**Comment by ronami** [comment]
> @ronami No need to maintain. There is already ng-annotate-patched which has all needed support. And it seems i need it already for 2 projects

Can you please add a link to the project? Does it have any breaking changes?
