### ISSUE TITLE
`npm start` fails to run local server in BM template

### ISSUE THREAD

**Issue by javinor** [wix/yoshi#1582]
# 🐛 Bug Report

### 😯 Current Behavior

```
npx create-yoshi-app foobar
cd foobar
npm start
```

fails to connect to localhost

changing `tsconfig.json` from `noEmit: true` to `noEmit: false` solves the problem (`__tests__/dev/server.js` is not copied to `dist` folder)

...

### 🤔 Expected Behavior

the above scenario should just work
...

### 💁 Possible Solution 

This change was introduced [here](https://github.com/wix/yoshi/blob/master/packages/create-yoshi-app/templates/business-manager-module/typescript/tsconfig.json#L13). I don't know if this should be reverted or maybe the `start` script in `package.json` should be updated...
...

**Comment by amitdahan** [comment]
Hey, thanks for the bug report, that's a nice catch! 
On it!
