### ISSUE TITLE
Enabling SSL from CLI works differently than in yoshi config

### ISSUE THREAD

**Issue by amitdahan** [wix/yoshi#1589]
# 🐛 Bug Report

### 😯 Current Behavior
If you run `yoshi start --ssl`, CDN will be SSL enabled, but webpack's `publicPath` is set to the default CDN URL which is `http://localhost:3200`.
When enabling SSL using `servers.cdn.ssl` in yoshi's config, this works as expected.
When enabling SSL via `--ssl`, assets loaded via `url-loader` (for example) fail to load with the local dev server, since it's configured with bad `publicPath`.

### 🤔 Expected Behavior
If a CLI arg and a config option do the same thing - they **must** do the same thing!

### 🔦 Context
This was a user complaint by @ChasyaMargalit

### Workaround
Setting the following in `package.json` (instead of using `--ssl`) resolves the issue for now:
```
"servers": {
  "cdn": {
    "ssl": true,
  }
}
```

### 👣 Steps to Reproduce
- Import a (big) image inside a JS/TS module
- Run `yoshi start --sl`
Image request is `404`.

### 🌍 Your Environment
Latest yoshi.

**Comment by ranyitz** [comment]
Another suggested solution - https://github.com/wix/yoshi/issues/1409
