### ISSUE TITLE
Using yoshi.config.js in templates (?)

### ISSUE THREAD

**Issue by amitdahan** [wix/yoshi#1592]
Do we prefer configuring `yoshi` through the config file or through `package.json`?
If we'd rather have a separate config file, they should be used in templates.

Wdyt?

**Comment by ranyitz** [comment]
Personally I would prefer no config at all :) I think that `yoshi.config.js` is just another file on the root directory and therefore I would not necessarily add it to our templates.

**Comment by amitdahan** [comment]
Cool, just making sure I'm synced
