### ISSUE TITLE
webdriver-manager update fails (Github request, rate limit reached)

### ISSUE THREAD

**Issue by odedcagan** [wix/yoshi#160]
It is an open issue for webdriver-manager: https://github.com/angular/webdriver-manager/issues/216
It seems running it with `gecko --false` fixes the problem.

When running e2e using protractor, Yoshi first updates webdriver and then launches it.
Currently it is only possible to pass flags to the run function.
https://github.com/wix/yoshi/blob/ec7d0a0ee81e72195e36c643c45d7e04e3b3baec/yoshi/lib/protractor.js#L48-L50

We should support passing flags to the update function as well.

**Comment by yanivefraim** [comment]
moved to https://github.com/wix-private/wix-js-stack/issues/526
