### ISSUE TITLE
Storybook and resolve-url-loader

### ISSUE THREAD

**Issue by muteor** [wix/yoshi#162]
To get font imports working in our project we use the `RESOLVE_URL_LOADER=true` yoshi flag. This works great in the project itself but we also have a storybook for the project and the webpack config from `yoshi/config/webpack.config.storybook` does not respect the flag meaning we get cannot resolve errors.

I have hacked a fix like this:

da-frontend/storybook/.storybook/webpack.config.js
```
const genDefaultConfig = require('@storybook/react/dist/server/config/defaults/webpack.config.js');
const wixStorybookConfig = require('yoshi/config/webpack.config.storybook');

module.exports = (config, env) => {
  const conf = wixStorybookConfig(genDefaultConfig(config, env));
  // Add resolve-url-loader before all sass-loader loaders
  conf.module.rules.forEach(rule => {
    if (rule.use) {
      let add = false;
      rule.use.forEach(loader => {
        if (loader.loader && loader.loader === 'sass-loader') {
          add = true;
        }
      });
      if (add === true) {
        let f = rule.use.pop();
        rule.use.push({loader: 'resolve-url-loader', options: {
          attempts: 1,
          keepQuery: true,
        }});
        rule.use.push(f);
      }
    }
  });

  return conf;
};
```
This works but is obviously not great hack :) So if the storybook webpack config could also support the flag or have an option, that would fix the issue for us.

Note: I had to add ` attempts: 1` to the loader as without it build time doubled. This could also be useful optimisation for the yoshi loader.

**Comment by ranyitz** [comment]
Yoshi 3 seems to be a good time to change the attempts attribute to 1 (breaking change)

**Comment by ranyitz** [comment]
#375 is configuring attempts to 1 and uses `resolve-url-loader` by default.

@muteor, do we still need this feature for storybook config?

**Comment by muteor** [comment]
For now no, we ended up backing out and loading fonts from CDN.

**Comment by ranyitz** [comment]
Thanks @muteor closing for now.
