### ISSUE TITLE
Write monorepo kitchensink tests

### ISSUE THREAD

**Issue by ronami** [wix/yoshi#1637]
### Summary

Monorepo support in Yoshi is still experimental but we already have two large projects that use it and we work on it constantly. Having tests will give us the confidence to know we didn't break things as we make changes and not break our clients often.

Our kitchensink tests normally test both TypeScript and JavaScript projects but monorepo projects only need to have TypeScript test projects since we currently only support (and aim to support in the future) TypeScript.

**Comment by ranyitz** [comment]
Fixed on #1285
