### ISSUE TITLE
Support Web Workers in Webpack

### ISSUE THREAD

**Issue by ronami** [wix/yoshi#1638]
### Summary

Currently, spawning your own web-workers with `new Worker()` is very hard. You can create a web-worker bundle with [config.webWorker](https://github.com/wix/yoshi/blob/0dd8bc71b8c5429302db804507b5afc377f6c497/packages/yoshi-config/src/config.ts#L69) and target `new Worker('...')` to its output but it's very cumbersome and not immediately obvious.

A better way to add seamless support for web-workers is with [worker-plugin](https://github.com/GoogleChromeLabs/worker-plugin) or [worker-loader](https://github.com/webpack-contrib/worker-loader). Both statically analyze the app code and create child compilations that target `webworker`.

See create-react-app's in progress [issue](https://github.com/facebook/create-react-app/issues/3660) and [PR](https://github.com/facebook/create-react-app/pull/5886) for more information.

**Comment by ranyitz** [comment]
Closed in #1650
