### ISSUE TITLE
Default CLI command for Yoshi (including flows)

### ISSUE THREAD

**Issue by amitdahan** [wix/yoshi#1673]
Let's say we support the following CLIs:
* `yoshi-app build`
* `yoshi-app start`
* `yoshi-app test`
* `yoshi-app lint`
* `yoshi-app info`
* `yoshi-app release`

I thought we could run one of the commands by default by just running `yoshi-app`.
I think `yoshi-app start` should be the "default", so simply `yoshi-app` works.

WDYT?

**Comment by ronami** [comment]
Nice idea, this is already happening since #1647.

**Comment by amitdahan** [comment]
Amazing! Sorry I missed it!
