### ISSUE TITLE
Align generators npm scripts

### ISSUE THREAD

**Issue by amitdahan** [wix/yoshi#1689]
# NPM Scripts in Generators

Some generators specify unconventional (?) npm scripts, for example:

https://github.com/wix/yoshi/blob/a77be2e2823e659f7325f91cde1b09f2dd5c3e72/packages/create-yoshi-app/templates/business-manager-module/typescript/%7B%25packagejson%25%7D#L10-L16

Since the generators are basically setting the standard for newly created projects at Wix, we should provide a better starting point. 
The current setup raises eyebrows.

* I don't think we need to have a `release` phase in most templates (probably only in `library`).
* We need to have a `build` script, which will be referenced in `pretest`, or not.

**Comment by amitdahan** [comment]
Anymore ideas?

**Comment by deanshub** [comment]
the `build` and `pretest` issue should be solved in yoshi in general (we're gonna remove it from the pretest)

**Comment by deanshub** [comment]
I think we should generate a `yoshi-flow-editor start` which will make `"PORT=5000 yoshi start --server ./dist/server.js --url http://localhost:5000/business-manager/3fdba72b-c9e7-4529-9219-807ad4b36d91/{%projectName%}"` redundent and will auto know the urls

**Comment by amitdahan** [comment]
Agreed. The new Flows will allow us to clean the "default" way of using our main CLI commands.

**Comment by ranyitz** [comment]
> auto know 😄 

That's in important discussion
