### ISSUE TITLE
yarn start does not watch for file changes

### ISSUE THREAD

**Issue by joncys** [wix/yoshi#170]
After running `yarn start` it sometimes finishes without starting a watch progress for development changes.

**Comment by shlomitc** [comment]
Is it still happening? How can I reproduce it?

**Comment by joncys** [comment]
Highly doubt it.
On top of that, when I opened it, I think it was our configuration related (we had some pretty dumb ideas w/ npm scripts).

**Comment by shlomitc** [comment]
ok, so I'm closing. if it happens again, please re-open.
