### ISSUE TITLE
Stylable files are not visible to webpack when `slplitChinnk` option is true

### ISSUE THREAD

**Issue by xmityaz** [wix/yoshi#1710]
# 🙋 Feature Request

### 😯 Current Behavior

When using yoshi parameter `slplitChinnk: true` in project with stylable (basically with WixStyleReact) webpack has trouble with resolving `.st.css` files.
Basically, with current yoshi webpack configuration, `.st.css` files cannot be found if they appear in `commons.chunk`

### 🤔 Expected Behavior

Don't have such troubles

### 💁 Possible Solution 

I have shared this problem with stylable team. They suggested me to set `useEntryModuleInjection: true` to `StylableWebpackPlugin` in webpack configuration.
I've hardcoded it in my node_modules/yoshi and it actually solved my issue.

So it would be great to have an ability for one of 2 options:
**a)** set this flag in yoshi config
**b)** set an object with all the overwrites for `StylableWebpackPlugin` in yoshi

Here is the part I need to change:
https://github.com/wix/yoshi/blob/master/packages/yoshi-common/src/webpack.config.ts#L505

Please advice how to approach better. Or maybe you know the other option to handle it

**Comment by ranyitz** [comment]
Hey @xmityaz! Thanks for opening this issue and I'm truly sorry that it took so long to answer. The team is extremely busy and we managed to miss this issue.

I'm wondering what is your workaround for now.
Regarding the configuration option - `useEntryModuleInjection`, I tried to look it up in [the docs](https://github.com/wix/stylable/tree/7711ad348f7c98b29af69c284104886213841807/packages/webpack-plugin) but couldn't find it and if it is safe to use.

We try to insert configuration only if it is absolutely necessary. In case that there is some configuration option which is good for everyone, we prefer to just configure it for everyone. What I need to know here is whether this is something that we want **for everyone**, whether it's **tested/safe to use**, and whether someone would break if we'll just change it to `true`.

@tomrav @barak007 we'll appreciate your help on this one.

**Comment by xmityaz** [comment]
Got the advice from stylable team.
It can be resolved in projects without yoshi, adding `stylable.config.js` and override the default stylable config.

Regarding the options itself - `useEntryModuleInjection`.
Here is explanation from @barak007 taken from slack:

> Injection of css, originated in a css in js stylable modules, that are bundled in the entry chunk (and not extracted to static css) can be done in two places
> 1. before importing the entry module which is less intrusive to the user code
> 2. after all modules from the entry module were imported which requires changes to the entry module
> in the first method there is bug. since the implementation needs to import all modules before startup we are manually import each .st.css modules from the entry chunk
> sometimes webpack split chunks in a way we don't recognize properly this leads to your error.
> useEntryModuleInjection is the option that enable mode 2. in this mode we don't import each style. we let the webpack module system run and then initializing the runtime renderer.
> then each dynamic chunk when loaded auto render asynchronously
