### ISSUE TITLE
After some yarn starts the computer becomes unstable

### ISSUE THREAD

**Issue by joncys** [wix/yoshi#172]
After running `yarn start` a couple of times, the next time running `yarn start` seems to start an infinite amount of processes and thus the computer becomes extremely slow and unusable to a point, I can't even properly restart it and have to do it by holding the power button.

**Comment by viliusl** [comment]
@joncys - is it easily reproducible? If so - show me, we'll figure out what processes don't want to die and figure out how to take care of that. Or just send `ps aux | grep node` or similar next time it happens.

**Comment by ronami** [comment]
@joncys is this still a problem?

**Comment by joncys** [comment]
@ronami nope.
