### ISSUE TITLE
Support for .flat() and .flatMap()

### ISSUE THREAD

**Issue by BnayaZil** [wix/yoshi#1735]
# 🙋 Feature Request

### 😯 Current Behavior
Testing (in Jest) a code with .flat() / .flatMap() throwing an error: `.flat is not a function`.

### 🤔 Expected Behavior
To support flat and flatMap in our Jest.

**Comment by ranyitz** [comment]
Hey @BnayaZil I think that it is not related to Jest/Yoshi specifically, you are most probably running in NodeJS.

The `.flat()` method is [supported from node > 11.15.0](https://node.green/#ES2019-features-Array-prototype--flat--flatMap-)

**Comment by amitdahan** [comment]
@BnayaZil Can we close this? Did you try using a higher node version?

**Comment by BnayaZil** [comment]
Yes, @ranyitz was right.
