### ISSUE TITLE
installing dependencies when needed

### ISSUE THREAD

**Issue by deanshub** [wix/yoshi#1738]
# 🙋 Feature Request

### 😯 Current Behavior

pulling and checkout different code doesn't trigger anything

### 🤔 Expected Behavior

Change in dependencies should trigger a process which installs the relevant dependencies (both for internal usage and user's code)

### 💁 Possible Solution 

starting off by just running `npm install` in a git hook that checks for `package.json` file change. checkout #1737 

maybe later we can diff for changes and install just the relevant dependencies.

**Comment by ranyitz** [comment]
This is indeed frustrating, you don't know that something has changed and only realize that you've needed to install those modules when something isn't working.

The work of "diffing for changes and installing the relevant dependencies" sounds to me like something that yarn + lockfile would solve. We'll have it soon - https://github.com/wix/yoshi/pull/1733

In my opinion we can wait for yarn with this feature, check for a `yarn.lock` change and start by notifying the user that something was changed in their last pull and that they should run the command `yarn` to update the dependencies (not necessarily a new dependency)

**The reasons for notifying and not actually installing would be:**
1. Try this on a dry-run mode to see if it would be nice to work with.
2. Our CI may be stuck when merging, waiting for user input, I'm not sure that we want to test for this kind of things right now.
3. Sometimes I just want to get the code from origin without installing anything and I feel that even this extra question can slow me down.

**Comment by deanshub** [comment]
I still think it's a better ux to ask and install the dependencies
I can use the dry-run mode to evaluate dep change but I don't think yarn has this feature.
CI is solvable.

I want to implement this feature to support both yarn and npm so that I can move it internally and the users of editor\bm flow will get this feature as part of the solution, WDYT?
