### ISSUE TITLE
Yoshi's documentation site publishing seems to be failing since we've moved to yarn

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1754]
After https://github.com/wix/yoshi/pull/1733 When the whole monorepo moved from npm to yarn our website publishing (a travis job) start to fail.

I suspect that this line https://github.com/wix/yoshi/blob/master/.travis.yml#L18 that was using `yarn` for the last 5 months, but now when we have a `yarn.lock` file on the root it is using it and installed packages from our private registry which doesn't expose to travis machines.

The simplest solution that comes to my mind would be to use `npm` for that installation.

I'm free to more solutions (maybe better ones...)

**Comment by amitdahan** [comment]
Remind me again why aren't we using the public registry with employee access to the `@wix` scope?
That'd make this a non-issue, right?

**Comment by deanshub** [comment]
we can try adding `--no-lockfile`

**Comment by ranyitz** [comment]
@deanshub sounds like a good idea! Can you contribute a PR with that solution?

**Comment by deanshub** [comment]
https://github.com/wix/yoshi/pull/1757

**Comment by ranyitz** [comment]
@deanshub For next time, using one of [those keywords](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords) in the description of the PR would autoclose the related issue.
