### ISSUE TITLE
Clashing CSS module class names

### ISSUE THREAD

**Issue by artur-charcenko** [wix/yoshi#176]
In `communities-members-app` we include bundles from 2 other projects. Each of those projects contains components that have identical paths. Because of that components override each others styles. 

It would be nice to at least have an option to specify a namespace for each project css classes.

**Comment by roymiloh** [comment]
Keep in mind that we need to apply the future fix in both css-modules-require-hook ([protractor configuration](https://github.com/wix/yoshi/blob/af8c122893469022aa9bd8b0d72fa116d6617b13/yoshi/config/protractor.conf.js#L42) / [yoshi-runtime](https://github.com/wix/yoshi/blob/af8c122893469022aa9bd8b0d72fa116d6617b13/yoshi-runtime/index.js#L7) / projects themselves) and css-loader.

**Comment by yanivefraim** [comment]
fixed by https://github.com/wix/yoshi/pull/181

**Comment by yanivefraim** [comment]
The feature broke communities production. Reverted

**Comment by yanivefraim** [comment]
fixed
