### ISSUE TITLE
Add option to use CaseSensitivePathsPlugin

### ISSUE THREAD

**Issue by alexander-gorelik** [wix/yoshi#1760]
# 🙋 Feature Request
Add option to use CaseSensitivePathsPlugin on `yoshi start`

### 😯 Current Behavior

No case sensitivity is checked

### 🤔 Expected Behavior

Ability to turn on the behavior case sensitivity checks

### 💁 Possible Solution 

Add a property in the config that will give the ability to turn the feature on.

### 🔦 Context 
We work on both case sensitive  and  non-sensitive OS's
This causes a lot of problems when dealing with filenames and imports, the build is failing frequently.
I saw that you are using `CaseSensitivePathsPlugin already in [yoshi common](https://github.com/wix/yoshi/blob/master/packages/yoshi-common/src/webpack.config.ts)

Thanks

**Comment by ranyitz** [comment]
@alexander-gorelik Thanks for opening an issue, as far as I understand it, `CaseSensitivePathsPlugin` should be configured for everyone. In case it isn't working for your usecase it needs to be debugged. Can you [include a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)?
