### ISSUE TITLE
css-loader 3 update breaks clientside hashing

### ISSUE THREAD

**Issue by muteor** [wix/yoshi#1767]
# 🐛 Bug Report

### 😯 Current Behavior

Clientside is generating incorrect development hashes:

```
Warning: Prop `className` did not match. Server: "_-node_modules--wix-da-shared-react-dist-es-src-SiteHeader-SiteHeaderDesktop-SiteHeader__env__3MWYG" Client: "_-node_modules-@wix-da-shared-react-dist-es-src-SiteHeader-SiteHeaderDesktop-SiteHeader__env__3MWYG"
```

So here server generates: `_-node_modules--wix-da-shared-react...` 
but clientside is generating: `_-node_modules-@wix-da-shared-react...`

We use `wixCssModulesRequireHook` on server to generate module hashes.

### 🤔 Expected Behavior

Clientside hash should replace `@` with `-`

### 🌍 Your Environment

```
System:
    OS: macOS Sierra 10.12.6
    CPU: (4) x64 Intel(R) Core(TM) i7-6660U CPU @ 2.40GHz
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 79.0.3945.79
    Firefox: 71.0
    Safari: 12.1.2
  npmPackages:
    @storybook/core: Not Found
    @storybook/react: Not Found
    babel-preset-yoshi:  4.23.0
    eslint-config-yoshi:  4.22.0
    eslint-config-yoshi-base:  4.22.0
    jest-yoshi-preset: Not Found
    storybook: Not Found
    tslint-config-yoshi:  4.22.0
    tslint-config-yoshi-base:  4.22.0
    typescript: ~3.6.0 => 3.6.4
    webpack:  4.32.2
    yoshi-config:  4.23.3
    yoshi-helpers:  4.23.5
    yoshi-runtime: ^1.0.273 => 1.0.379

 Zero config 🛴
```

**Comment by deanshub** [comment]
found the issue, https://github.com/css-modules/generic-names/issues/8, for now I recommend you fixate yoshi's version in the package.json till I figure out a nice workaround

**Comment by ranyitz** [comment]
After seeing this issue we've decided to revert the css-loader upgrade. While we're not officially supporting "universal" apps we prefer to wait with this upgrade to the next major version of Yoshi. See #1769

**Comment by ranyitz** [comment]
This version includes the revert - https://github.com/wix/yoshi/blob/master/CHANGELOG.md#4237-2019-12-18
