### ISSUE TITLE
[RFC] Editor Yoshi Flow – Styles at Settings Panel and Application

### ISSUE THREAD

**Issue by tuchk4** [wix/yoshi#1770]
# RFC: Styles at Settings Panel and Application

Most of the ideas are come from [`@wix/tpa-settings`](https://github.com/wix-private/tpa-settings) which is used on [site-search](https://github.com/wix-private/site-search/tree/master/packages/search-results-settings), [challenges-web-ooi-component](https://github.com/wix-private/strategic-products/tree/master/achievements/web-client/challenges-web-ooi-component), [groups](https://github.com/wix-private/strategic-products/tree/master/social-groups/social-groups-ui/packages/social-groups-app) and [etsy](https://github.com/wix-private/wix-labs/tree/master/etsy-client) OOI applications.

# Table of contents

- [Requirements](#requirements)
- [Glossary:](#glossary)
  - [Color Theme](#color-theme)
  - [Font Theme](#font-theme)
  - [Default Values](#default-values)
  - [Shared contexts between Settings Panel and App environments](#-shared-contexts-between-settings-panel-and-app-environments)
- [Working with Styles at Settings Panel](#working-with-styles-at-settings-panel)
- [1. Styles API as Context](#1-styles-api-as-context)
  - [1.1 `IStyleKey` type as string](#11-istylekey-type-as-string)
    - [Define Default Value](#define-default-value)
  - [1.2 `IStyleKey` type as object](#12-istylekey-type-as-object)
    - [Define Default Value](#define-default-value-1)
  - [1.3 `IStyleValue` type](#13-istylevalue-type)
- [2 Get Styles variables at App `js` files](#2-get-styles-variables-at-app-js-files)
  - [2.1 Readonly Styles Context.](#21-readonly-styles-context)
  - [2.2 `getStylesValues`](#22-getstylesvalues)
- [3. Get styles variables at App `css` files](#3-get-styles-variables-at-app-css-files)
- [4. Process styles on site save](#4-process-styles-on-site-save)
- [Action items](#action-items)

[Example of Styles Context Usage at `@wix/tpa-settings`](https://github.com/wix-private/tpa-settings#2-styles-context-usage)

## Requirements

1. Support typescript
2. Support default values for both Settings Panel and App environments
3. Support Wix colors presets (e.g `color-1`)
4. Support Wix font presets (e.g `Body-M`)
5. Support site color palette change events
6. Should work out of the box without additional code
7. 🔥 It could be implemented as a separated package and integrated to `editor-yoshi-flow`. So it may be also used without `editor-yoshi-flow` like we already did at [site-search](https://github.com/wix-private/site-search/tree/master/packages/search-results-settings) and other OOI applications. Also see [RFC: UI Components for Settings Panel – Requirements#4](https://github.com/wix/yoshi/issues/1773)

## Glossary:

ℹ️ Font and Color Theme could be changed by the user from any part of the site (not only at the App's Settings Panel).

### Color Theme

<p align="center"> 
  <img src="https://d2wzpmhzgtb9fu.cloudfront.net/docs/wp-content/uploads/2016/08/21141645/colors.png"/>
  <br/>
  https://dev.wix.com/docs/uiux-basics/site-components/#color
</p>

```
.root {
  color: 'color(color-5)';
}
```

### Font Theme

<p align="center" >
  <img src="https://user-images.githubusercontent.com/2445828/70933799-829df680-2034-11ea-939b-4d552b1965d4.png" width="480"/> 
  <br/>
  https://dev.wix.com/docs/ui-lib/using-ui-lib/#font-values
</p>

```
.root {
  font: "font({theme: 'Body-M', size: '20px'})";
}
```

### Default Values

We need to specify the default value for each Style param, to render UI components with correct values at Settings Panel. It should be the default values until the user did any changes.

### ℹ️ℹ️ℹ️ Shared contexts between Settings Panel and App environments

Contexts should be `window.Wix` agnostic. This means that we should use the adapter for `window.Wix` at Setting Panel and corvid/OOI API at App.

## 1. Styles API as Context

I assume that API will be implemented as React Context. Here is two design proposals, we should select one to implement:

- [1.1 `IStyleKey` type as string](#11-istylekey-type-as-string)
- [1.2 `IStyleKey` type as object](#12-istylekey-type-as-object)

**Styles Context API objectives:**

- Manage local styles state and sync to `Wix.Styles`
- Handle site color change event. [Example implementation at `@wix/tpa-settings`](https://github.com/wix-private/tpa-settings/blob/master/src/contexts/StylesContext/styles/StylesStore.ts#L121)
- Automatically fix (if possible) known `Wix.Styles` bug, until it is not resolved, provided Wix API
- Encapsulate all the complex things inside and keep API as simple as possible
- Provide DX friendly API

**API Signature:**

ℹ️ NOTE: `IStyleValue` and `IStyleKey` namings are only for this document.

- `get(key: IStyleKey): IStyleValue`
- `set(key: IStyleKey, value: IStyleValue): void`
- `handleSiteColorChange(colors): void`
- `handleSiteFontChange(colors): void` – not sure, if it is required

<details>
  <summary>Styles Context API Examples</summary>

As context consumer:

```js
import { StylesConsumer } from '../styles-rfc';
const DesignTab = () => {
  return (
    <StylesConsumer>
      {styles => {
        return /* ... */;
      }}
    </StylesConsumer>
  );
};
```

As hook:

```js
import { useStyles } from '../styles-rfc'; // export result of `createStylesContext`

const DesignTab = () => {
  const styles = useStyles();
  return /* ... */;
};
```

As hoc:

```js
import { withStyles, WithStylesProps } from 'styles-rfc';

const InnerDesignTab: React.FC<WithStylesProps> = ({ styles }) => {
  return /* ... */;
};

export const DesignTab = withStyles(InnerDesignTab);
```

</details>

**Known Wix.Styles issues:**

There are a lot of issues with `Wix.Styles` API that could be automatically fixed in Styles Context.

<details>
<summary>Example issues</summary>

- `value` variable has different types in these statements – `Wix.Styles.setColor(key, value)` and `const value = Wix.Styles.getColor(key)`. We should do color normalizations on get and set calls.
- `Wix.Styles.getColor(key)` will always return the initial value, even `Wix.Styles.setColor(key, value)` call with the same `key`.
- There is no validation, so it possible to save any data in Styles. This is the reason, why developers use `Wix.Styles.Font` to store custom settings.
- API is not 100% covered with types
- etc.

</details>

### 1.1 `IStyleKey` type as string

```
type IStyleKey = string;
```

```js
styles.get('myColor');
styles.set('myColor', value);
```

**Advantages:**

- less code

**Disadvantages:**

- looks like a hard-coded string
- hard to support typings

There is the only way to support typings is to use `createStylesContext<T>()` function with generic types that return styles Consumer and Provider components.

```ts
enum StyleParamType {
  Color,
  Font,
  Number,
  Boolean,
}

function createStylesContext<T extends Record<string, StyleParamType>>(): {
  StylesConsumer: StylesConsumer<T>;
  StylesProvider: StylesProvider<T>;
  useStyles?: StylesHook<T>; // NOTE: ensure if `React.useContext` is available.
  withStyles?: StylesHoc<T>;
  getStylesValues: (settings: Partial<T>) => T; // function that returns an object with changed params and fills the rest with default values
} {}
```

**getStylesValues** – More explanation and examples at [`@wix/tpa-settings#getSettingValues`](https://github.com/wix-private/tpa-settings#getsettingsvalues). It is about settings (publicData), but the idea is the same. This will help us to implement a framework/environment agnostic approach.

```ts
const { StylesConsumer, StylesProvider } = createStylesContext<{
  myColor: StylesType.Color;
  myFont: StylesType.Font;
  myPadding: StylesType.Number;
}>();
```

#### Define Default Value

```ts
export interface IStyleParamColorValue {
  hex?: string; // could be only `hex`. Should throw exception if rgb/rgba
  colorTheme?: string; // https://dev.wix.com/docs/uiux-basics/site-components/#color
  opacity: number;
}

export interface IStyleParamFontValue {
  fontTheme: string; // https://dev.wix.com/docs/ui-lib/using-ui-lib/#font-values
  size: number;
  // ...
}

export interface IStyleParamValueByType {
  [StyleParamType.Color]: IStyleParamColorValue;
  [StyleParamType.Font]: IStyleParamFontValue;
  [StyleParamType.Boolean]: boolean;
  [StyleParamType.Number]: number;
}

function createStylesContext<T extends Record<string, StyleParamType>>(props: {
  // Using a `defaultValue` property instead of root level is good for flexibility and readability, so in the future, it will be easy to extend functionality of `createStylesContext`
  defaultValues: { [K in keyof T]: IStyleParamValueByType[T[K]] };
}): {
  StylesConsumer: StylesConsumer<T>;
  StylesProvider: StylesProvider<T>;
} {}
```

```ts
createStylesContext<{
  myThemeColor: StylesType.Color;
  myHexColor: StylesType.Color;
  myFont: StylesType.Font;
  myPadding: StylesType.Number;
}>({
  defaultValues: {
    myThemeColor: { colorTheme: 'color-1', opacity: 0.6 },
    myHexColor: { hex: '#3399ff', opacity: 0.6 },
    myFont: { fontTheme: 'Body-M', size: 15 },
    myPadding: 10,
  },
});
```

Since this code could be used in both Settings Panel and App environments, it is the reason why some types at the generic type and `devalueValues` type are different – we could not define default color that refs to `color-1` without `Wix` API. So we should use similar but another type and normalize values under the box.

### 1.2 `IStyleKey` type as object

ℹ️ NOTE: this way is implemented at `@wix/tpa-settings`

```ts
enum StylesType = {
  Color,
  Font,
  Number,
  Boolean,
}

type IStyleKey<T extends StylesType> = {
  type: T,
  key: string // `key` is used to store current Style value, accessible from CSS
};
```

```js
const myColor: IStyleKey<StylesType.Color> = {
  type: StylesType.Color,
  key: 'myColor',
};

styles.get(myColor);
styles.set(myColor, value);
```

**Advantages:**

- easy to support typings

**Disadvantages:**

- more code
- keep sync `key` field with the variable name. On another hand – this may be the advantage because if you need to change the style param key, it is possible to change only `key` field in `IStyleKey`.

#### Define Default Value

Default values could be defined per style key:

```ts
type IStyleKey<T extends StylesType> = {
  type: T;
  key: string;
  defaultValue: IStyleParamValueByType[T]; // see `Default Value` section at #1.1 for the interface signature
};
```

```js
const myColor: IStyleKey<StylesType.Color> = {
  type: StylesType.Color,
  key: 'myColor',
  defaultColor: { colorTheme: 'color-1', opacity: 0.6 },
};
```

### 1.3 `IStyleValue` type

Since we are talking about styles, there is the limited number of types for `IStyleValue`.

- Color
- Font
- Number
- Boolean

All types already exist at `@wix/native-components-infra`.

```ts
import {
  IWixStyleColor,
  IWixStyleFont,
} from '@wix/native-components-infra/dist/src/types/wix-sdk';
```

## 2 Get Styles variables at App `js` files

Sometimes we need to get style values for some specific calculations when it is not possible to implement App spec with only pure CSS.

### 2.1 Readonly Styles Context.

Should be shared implementation with contexts for Settings Panel but in `read-only` mode at App environment.
It could be used as Consumer, as hook or hoc.

At any component:

```js
import { useStyles } from '../styles-rfc'; // export result of `createStylesContext`

const Component = () => {
  // styles – readonly interface
  const styles = useStyles(); // also may be used as Context Consumer instead of hook

  return /* ... */;
};
```

Possible structure:

```
|- app/
|     |-index.ts
|
|- settingsPanel/
|               |-index.ts
|
|- styles/
|        |- StylesContext.ts  <-- Shared context between Settings Panel and App. Readonly for App environment.
|

```

### 2.2 `getStylesValues`

We similar function for settings [`@wix/tpa-settings#getSettingValues`](https://github.com/wix-private/tpa-settings#getsettingsvalues).
The same idea is for `getStylesValues`. This will help us to implement a framework/environment agnostic approach.

At controller file:

```js
export async function appController(config) {
  const styles = getStyleValues(config.styles);
  this.setState({ styles });

  return {
    methods: {},
  };
}
```

## 3. Get styles variables at App `css` files

This is the default way using https://github.com/wix-incubator/tpa-style-webpack-plugin

```css
.root {
  font: "fallback(font(--myFont), font({theme: 'Body-M', size: '20px'}))";
  color: 'fallback(color(--myColor), color(color-5))';
  padding: '"unit(fallback(--myPadding, 15), px)"';
}
```

The only workaround here is to use CSS in JS solutions instead of `tpa-style-webpack-plugin`.

ℹ️ NOTE: the main issue here that we need to defined default values in both CSS and JS files. We don't even have a workaround

## 4. Process styles on Site save

As discussed at the last meeting, it would be perfect, if we could process `st.css` file + styles from Settings Panel and generate the `css` file on each site save. It is possible to implement, but as far as I understand, this feature is related to the editor team.

---

## Action items

General:

- [ ] Should be implemented as a separated package and integrated to `editor-yoshi-flow`.

Settings Panel:

- [ ] 1. Styles API as Context
- [ ] 1.1 `IStyleKey` type as string
- [ ] 1.2 `IStyleKey` type as object

App:

- [ ] 2.1 Readonly Styles Context
- [ ] 2.2 `getStylesValues`

Editor:

- [ ] 4. Process styles on Site save

---

- if the point is checked - will be done
- if the point is un-checked - still in discussion
- if the point is crossed out - will not be done

**Comment by ranyitz** [comment]
**Putting those for reference:**

The current solution involves the use of [`WithStyles`](https://github.com/wix-private/native-components-infra#withstyles) and [`tpa-style-webpack-plugin`](https://github.com/wix-incubator/tpa-style-webpack-plugin)

Two JIRA tickets that talks about possible future handling of styles in the platform:

https://jira.wixpress.com/browse/PLAT-165
https://jira.wixpress.com/browse/PLAT-187

**Comment by tuchk4** [comment]
FYI: Approach for working with styles  from`@wix/tpa-settings`  is not a replacement for `WithStyles` and `tpa-style-webpack-plugin`.
They are working together.
