### ISSUE TITLE
[RFC] Editor Yoshi Flow – Events between Settings Panel and Application

### ISSUE THREAD

**Issue by tuchk4** [wix/yoshi#1772]
# RFC: Events between Settings Panel and Application

Most of the ideas are come from [`@wix/tpa-settings`](https://github.com/wix-private/tpa-settings) which is used on [site-search](https://github.com/wix-private/site-search/tree/master/packages/search-results-settings), [challenges-web-ooi-component](https://github.com/wix-private/strategic-products/tree/master/achievements/web-client/challenges-web-ooi-component), [groups](https://github.com/wix-private/strategic-products/tree/master/social-groups/social-groups-ui/packages/social-groups-app) and [etsy](https://github.com/wix-private/wix-labs/tree/master/etsy-client) OOI applications.

# Table of contents

- [Requirements](#requirements)
- [1 Create Event Emitter](#1-create-event-emitter)
- [2 Events API at Settings Panel](#2-events-api-at-settings-panel)
- [3 Events API at App](#3-events-api-at-app)
  - [3.1 Events data from event listeners](#31-events-data-from-event-listeners)
  - [3.2 Event data as props](#32-event-data-as-props)
- [Action itemsx](#action-itemsx)

[Events documentation at `@wix/tpa-settings`](https://github.com/wix-private/tpa-settings#events-between-settings-panel-and-applications)

## Requirements

1. Support typescript
2. Should be possible to trigger events from the Settings Panel to the App, but not vice a versa
3. Should be possible to listen to events in the App
4. Should be possible to listen to Settings Panel's `close` event to reset App view
5. 🔥 It could be implemented as a separated package and integrated to `editor-yoshi-flow`. So it may be also used without `editor-yoshi-flow`, like we already did at [site-search](https://github.com/wix-private/site-search/tree/master/packages/search-results-settings) and other OOI applications. Also see [RFC: UI Components for Settings Panel – Requirements#4](https://github.com/wix/yoshi/issues/1773)

ℹ️ At at `@wix/tpa-settings` events are a workaround that is built on top of Wix PublicData (settings storage). Not a good solution, but it is the only way to publish events from Settings Panel to App.

Since we talk about the more mature solution, it should be implemented as a core Wix API. So likely this is not our responsibility, but we should push this feature has to be implemented.

## 1 Create Event Emitter

```ts
function createEventEmitter<T>(): {
  // trigger event K with value T[K]
  // API available at Settings Panel
  trigger<K extends keyof T>(event: K, value: T[K]): void;

  // listen event K
  // API available at App
  listen<K extends keyof T>(event: K, listener: (value: T[K]) => void): void;

  // triggers on Settings Panel close
  // API available at App
  onClose(listener: () => void): void;
} {}
```

```ts
const events = createEventEmitter<{
  showNoResults: void;
  previewState: 'regular' | 'error';
}>();

events.trigger('previewState', 'error');
```

We may use the same `createEventEmitter` function in both Settings Panel and App environments but its behavior (return type) will be different. Or we can use the different functions for each environment, but we should share type `T`.

## 2 Events API at Settings Panel

At any component:

```js
import { useEvents } from '../events-rfc';

const Component = () => {
  const events = useEvents();

  function handleClick() {
    events.trigger('previewState', 'error');
  }

  return /* ... */;
};
```

## 3 Events API at App

We should select one to implement:

- [3.1 Events data from event listeners](#31-events-data-from-event-listeners)
- [3.2 Event data as props](#32-event-data-as-props)

### 3.1 Events data from event listeners

```js
events.listen('previewState', state => {
  setState('previewState', state);
});

events.onReset(() => {
  setState('previewState', 'regular');
});
```

### 3.2 Event data as props

At controller file:

```js
import { events } from '../events-rfc';

export async function appController(config) {
  syncEventDataWithState(this, events, config);
  return {
    methods: {},
  };
}
```

ℹ️ This example is 100% pseudo-code. The main idea is that we sync and reset events data to App state, and all App components stays with default approach `View = F(props, state)`.

We can do it automatically or let developers to subscribe to all events manually at controller and change App view using `setState`.
The benefits are that all logic is done at controller part and components are just simple View models.

---

## Action items

General:

- [ ] Should be implemented as separated package and integrated to `editor-yoshi-flow`.

Settings Panel:

- [ ] 2 Events API at Settings Panel

App:

- [ ] 3.1 Events data from event listeners
- [ ] 3.2 Event data as props

---

- if the point is checked - will be done
- if the point is un-checked - still in discussion
- if the point is crossed out - will not be done

**Comment by bodia-uz** [comment]
I tried to understand how TPA messaging works now.
Here is some result with a reason why the widget does not receive events:
https://github.com/wix-private/santa-editor/issues/23535
