### ISSUE TITLE
yoshi build under symlink monorepo and 'externalUnprocessedModules'

### ISSUE THREAD

**Issue by zivl** [wix/yoshi#1785]
## Context and Background:
We have a monorepo, managed with `lerna` (symlinks and etc.).
We have *commons* module which has some utility functions and being consumed by our application modules, lets call them *A* and *B*. The *commons* module **is not transpiled** and we consume the functions strait from the `/src` folder.
We run `npm i` from the root folder of the monorepo, so everything is hoisted/linked accordingly by `lerna`. 

## Problem:
We are using `externalUnprocessedModules` to tell `yoshi` to transpile the *commons* module consumed in *A* and *B*. When we run `yoshi build` then the files in *commons* are not transpiled.

## Solution:
The solution split into the following `yoshi` packages:
`yoshi-helpers`
Need to add another condition here to include files which comes from the same repo.
```typescript
const allSourcesButExternalModules = (filePath: string) => {
    filePath = path.normalize(filePath);

// example of whats need to be added: filePath.startsWith(MONOREPO_ROOT))
// MONOREPO_ROOT is imported from `yoshi-config/paths`
    return (
      filePath.startsWith(process.cwd()) && !filePath.includes('node_modules')
    );
  };
```

`yoshi-config`
in file `/src/paths.ts`
Need to add back the following lines (it was there before)
```typescript
const LERNA_JSON = findUp.sync('lerna.json');
const MONOREPO_ROOT = LERNA_JSON && path.dirname(LERNA_JSON);
```

**Comment by ranyitz** [comment]
Hey @zivl, Thanks for opening this issue, and nice debugging! I'll try to get to it soon!

**Comment by ranyitz** [comment]
Ok, I think that the reason `externalUnprocessedModules` isn't working for you is this - I believe that webpack resolves the real path of the module and therefore [this condition](https://github.com/wix/yoshi/blob/c88dd373698b9d8d6756b67e2787d75df4079c07/packages/yoshi-helpers/src/utils.ts#L44) doesn't turn up to be thruthy, it used to work up until this [change](https://github.com/wix/yoshi/pull/1279).

The change that you suggest would be a possible breaking change for everyone that has a monorepo (and aren't wants to transpile the module)

__________________

In any case, it's important to say that `externalUnprocessedModules` is a legacy feature that we would like to deprecate. I would transpile those modules as part of their build process and not rely on the consumer to transpile them.
