### ISSUE TITLE
Verdaccio publishing during tests is too verbose

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1813]
# 🐛 Bug Report
We have many many lines in CI of verbose verdaccio publishing.

![image](https://user-images.githubusercontent.com/11733036/71678414-c4959f00-2d8d-11ea-8779-8864ff005bd4.png)

It would be nice to see this output only if there is a problem.
When everything is working we don't really care about all of these logs.

**Comment by juanpicado** [comment]
You have `http` level, is too verbose imho. 
https://github.com/wix/yoshi/blob/master/verdaccio.yaml#L33

I'd rather

``
logs:
  - {type: stdout, format: pretty, level: warn}
```
Does it work for you? can I PR? 🙃

**Comment by ranyitz** [comment]
@juanpicado Thanks a lot 🙂

Of course, that sounds great!

**Comment by juanpicado** [comment]
I assume the log noise is not what the image report, I see lerna but the text points out to Verdaccio, hopefully is what you meant.
