### ISSUE TITLE
Jest and svelte environment differences

### ISSUE THREAD

**Issue by giladsegal** [wix/yoshi#1816]
# 🐛 Bug Report

Possible mismatch between jest and svelte environments

### 😯 Current Behavior

Spreading `undefined` as an object for a svelte component doesn't cause tests to fail
Doing the same thing in production causes a runtime exception `undefined is null or not an object`

```jsx
<MyComp {...undefined} />
```

### 🤔 Expected Behavior

Either both environment should fail or succeed

### 👣 Steps to Reproduce 

`SiteButtonContent` in `editor-elements`:
remove `|| {}` from `linkProps`

**Comment by NitayRabi** [comment]
Currently `editor-elements` uses a custom configuration for running jest (and not trough Yoshi) - this should be considered when `editor-elements` will use `yoshi` for testing

**Comment by yanivefraim** [comment]
Is this still relevant?
