### ISSUE TITLE
Running test that includes publishing to verdaccio pollutes the file system

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#1826]
🐛 Bug Report

### 😯 Current Behavior
When running `yarn test:integration:ts` for exmaple, a test suite which includes publishing to verdaccio, many files are changed/created in the file system, which means that if you forgot to commit/stage your changes you'll get confuse or even loose your changes.

### 🤔 Expected Behavior

Before you run the test suite locally you should use a special env param or approve that you are aware to those changes before the publish starts. Maybe we can also suggest to run the "fast" mode locally.

### 🔦 Context

Some of my work has been deleted and many files has created

![image](https://user-images.githubusercontent.com/11733036/71880923-fc0f9d00-3139-11ea-8fe0-1abe03f20631.png)

### 💁 Possible Solution 

The expected behavior included a possible solution.

### 👣 Steps to Reproduce

Run the `test:integration:js` locally.

**Comment by yanivefraim** [comment]
What about adding those to the .gitignore?
We can add a message anyway.
