### ISSUE TITLE
Pullrequest CI has a publish task

### ISSUE THREAD

**Issue by yanivefraim** [wix/yoshi#1833]
For some reason, PR CI has a publish task:

![Screen Shot 2020-01-07 at 14 08 32](https://user-images.githubusercontent.com/1336186/71894575-4f441880-3157-11ea-9d6d-7550132daad7.png)

It does not publish anything, eventually, but I would check and fix it anyway (might cause problems)

**Comment by ranyitz** [comment]
I think that it's related to the fact that we now have a `"customPublish"` arg in `package.json`. IMHO the easiest solution that will prevent us from publishing in a PR would be to check if we are in a PR in `scripts/customPublish.ts` and abort the operation.

In case we'll want to publish from a PR in the future we'll be able to remove the condition and do it properly.
