### ISSUE TITLE
Failed build with dynamic import

### ISSUE THREAD

**Issue by maxaon** [wix/yoshi#1867]
# 🐛 Bug Report

### 😯 Current Behavior

Yoshi fails build when shared lib has dynamic imports.  

### 🤔 Expected Behavior

build with dynamic import should be working

### 🔦 Context 

We have node library with dynamic import. Main artifact executes this code and expects that lib will dynamically load some big JSON and execute some code.
In previous it seems that yoshi build it in common js form.
Adding 
```json
  "externalUnprocessedModules": [
    ""
  ],
```
or 
```json
  "externalUnprocessedModules": [
    "moduleA"
  ],
```
doesn't help

### 💻 Code Sample
**in moduleA**

```js
export function getFile() {
    return import('file.json')
}
```

**in moduleB**

```js
import {getFile} from 'moduleA'

getFile().then(console.log);
```

### 🌍 Your Environment

```
// PASTE HERE
```

**Comment by ranyitz** [comment]
@maxaon I need a bit more information to understand what happening here. This use-case incorporates two different builds, I would like to be able and look at each one, see the output etc. Can you [create a small repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff) that demonstrate the problem?

**Comment by maxaon** [comment]
So seems it's issue of npm/webpack
https://github.com/webpack/webpack/issues/8656

**Comment by maxaon** [comment]
Seems this is same issue as described in https://github.com/webpack/webpack/issues/8656
Because of different version (instances) of packages it fails to work.
I've used yarn for installation and it helped. In other project  either yarn worked or adding specific version of acorn.
@Lukermelesh

**Comment by ranyitz** [comment]
Hey, you're referring to an [old annoying npm dependencies problem](https://github.com/webpack/webpack/issues/8656#issuecomment-456010969) that [hasn't solved yet](https://github.com/webpack/webpack/issues/8656#issuecomment-571779872)

While this may be the problem I can't confirm without looking at the `node_modules` tree and verify. Also, I'm wondering if it's happening to everyone? If not that i'm interested how you got `acorn` in your `node_modules` tree.

If you want any further investigation from our side, please provide a repo.

We can leave this issue open in case we'll see more instances of this problem.
