### ISSUE TITLE
Yoshi start is not fully completed before tests execute

### ISSUE THREAD

**Issue by Gongreg** [wix/yoshi#1950]
# 🐛 Bug Report

Currently the feature tests are not actually waiting till the dev environment fully starts.

### 😯 Current Behavior

Right now both yoshi (started as a child process in tests) and the tests themselves are awaiting `waitForPort(3000)` command. Because they are in separate processes the order in which waitForPort will be executed is undefined.

### 🤔 Expected Behavior

The tests properly await till yoshi fully starts up.

### 🔦 Context

Relevant PR: https://github.com/wix/yoshi/pull/1932

This issue has made us to use rebound with checking if the server is fully booted up in start.ts . 

### 💁 Possible Solution

One possible solution was to output a text message in cli only after the yoshi has fully booted up and then await for it in the tests. https://github.com/wix/yoshi/pull/1932/commits/b89a32cdedc72878c911f0a6e9604503952acaf4 

This issue is not a blocker, just something to be aware of.

### 👣 Steps to Reproduce

Quite difficult to reproduce, since the order in which `waitForPort()` in tests and in yoshi itself is resolved is not guaranteed, so you have to keep retrying till the tests `waitForPort()` resolves first.

### 💻 Code Sample

https://github.com/wix/yoshi/pull/1932

### 🌍 Your Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
    Safari: 13.0.5
  npmPackages:
    @storybook/core: Not Found
    @storybook/react: Not Found
    babel-preset-yoshi: Not Found
    eslint-config-yoshi: Not Found
    eslint-config-yoshi-base: Not Found
    jest-yoshi-preset: ^4.1.0 => 4.33.0
    storybook: Not Found
    tslint-config-yoshi: Not Found
    tslint-config-yoshi-base: Not Found
    typescript: Not Found
    webpack:  4.28.4
    yoshi-config:  3.31.0
    yoshi-helpers: Not Found
    yoshi-runtime: Not Found

 Yoshi config
{
  "projectType": "app",
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM",
    "@wix/fedops-logger": "fedopsLogger"
  },
  "servers": {
    "cdn": {
      "port": 3300
    }
  },
  "hmr": "auto"
}
```

**Comment by ranyitz** [comment]
Thanks for opening this issue! This is well explained 👍 

I'll throw some ideas to the board:
1. I don't want to couple production behavior for a problem we have only in tests, we can output something only during tests (passing a specific `process.env` variable)
2. We can make a request to `heart_beat` route in the server which we can add (should be up after the process is occupied)
3. I'm interested what is the interval of the production `waitPort` function. In tests we can use `setTimeout` for an additional `intervalTime` of the production wait port, so we'll make sure it finish after.

**Comment by Gongreg** [comment]
Sounds like #1 would be easiest to implement and definitely stable :)

**Comment by ranyitz** [comment]
![image](https://user-images.githubusercontent.com/11733036/74335603-37d6fb80-4da5-11ea-8f0b-b0670b58d7aa.png)

Keep reminding me my first issue 🤣 
_______

@ronami @yanivefraim what do you say?
