### ISSUE TITLE
Chore: Update `fork-ts-checker-webpack-plugin`

### ISSUE THREAD

**Issue by yanivefraim** [wix/yoshi#1999]
Currently, we are using version `1.6.0`, while the latest version is `4.0.4`.  There's probably an issue with Typescript V3.8.2, which causes the `fork-ts-checker-webpack-plugin` to break. This issue was fixed in V4.0.4 (see https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/363)

**Comment by amitdahan** [comment]
@yanivefraim How did that TypeScript error ever resolve itself?
