### ISSUE TITLE
remove tslint dependency from haste-tslint

### ISSUE THREAD

**Issue by shlomitc** [wix/yoshi#200]
This issue was raised due to the fact that installing `yoshi` in a clean folder without `typescript` throws some `peerDependencies` warning. This is because `tslint` has a peerDep of `typescript` (which isn't installed by `yoshi`).

Since `yoshi` is using semver, this seems legit to remove the `tslint` dependency in a future major version.
https://github.com/wix/haste/blob/master/packages/haste-task-tslint/package.json#L11

CC @AviVahl

**Comment by ranyitz** [comment]
From version 3, yoshi is not using `haste-task-tslint` anymore.

Closing.
