### ISSUE TITLE
Discuss: proto codegen in yoshi

### ISSUE THREAD

**Issue by viliusl** [wix/yoshi#201]
@ranyitz @ronami node-platform is moving towards serving rpc services. For that to work we have 2 pieces of a puzzle:
 1. generating js/ts files from `.proto` definitions via [wix-proto-codegen](https://github.com/wix-platform/wix-node-platform/tree/master/rpc/wix-proto-codegen) - you can use usage in [here](https://github.com/wix-private/fed-infra/blob/master/app-settings/app-settings-service/package.json#L11)
 2. creating modules that expose only proto files and are cross-published to both npm and mvn repos. example [here](https://github.com/wix-private/fed-infra/tree/master/app-settings/app-settings-api)

For both of these I would like to use yoshi/haste. Where for no. 1 I think we should just add plugin to yoshi and no 2. is more interesting - It is more of a verification thing - module needs to store proto files in certain location, build proto files with no-emit (to verify corectness), have a mark in package.json, not contain pom.xml. I would like to give smth for developers that they could use so they don't make mistakes - if they do smth will just not works and feedback loop is not great:/

I would like to discuss how we should proceed.

cc: @hugebdu

**Comment by ranyitz** [comment]
@viliusl @hugebdu Is this still relevant?
