### ISSUE TITLE
yoshi stopped renaming jsx to js+map

### ISSUE THREAD

**Issue by viliusl** [wix/yoshi#202]
module: https://github.com/wix-private/fed-infra/tree/master/react-test-wrappers

It had yoshi version set to `^1.1.19` and I observed that published module changed between `react-test-wrappers@1.0.10` and `react-test-wrappers@1.0.16` without any changes in code.

1.0.10: all `.jsx` files were transpiled to `.js` and `.js.map`;
1.0.16: all `.jsx` files were transpiled, but placed to `dist` as `.jsx`;
1.0.17: is back to normal after freezing yoshi version to `1.1.19`.

So there is definitely a regression in yoshi. You can verify behavior by  toggling yoshi version in `react-test-wrappers`.

@ronami @ranyitz

**Comment by ranyitz** [comment]
This seems to be a bit outdate, we'll try to learn from this for the next time.
