### ISSUE TITLE
[RFC] Yoshi flow editor: Develop your app locally.

### ISSUE THREAD

**Issue by yavorsky** [wix/yoshi#2043]
This RFC related to really important part of development process. By developing the app we want to not rely on additional environment not related to our widget, but  on the same time, be sure app will work as expected after we publish it.

Currently, the best way to develop OOI app is to run it in viewer and editor environment, provide HMR (in progress) and point platform part to download `viewerScript`, `editorScript`, editor/settings apps endpoints to local ones. On the same time, we should have production version pointed to stable builds from CDN.

Currently, from what I saw we have 2 different flows from team to team:
### Maintain 2 Apps in Dev Center.
One app is configured to local environment, second - to prod one. It's really easy to set-up. You just need to go to dev center, copy paste values you need, create same components. Then you probably need to have at least 2 websites for each app to verify everything is working fine.
Of course it will create some inconveniences and potential issues:
- You should maintain 2 apps on dev center. After you added new widget, you need to add it to second app. After 
- You should maintain 2 apps in the project. Currently, you should handle additional logic for viewerScript:
*example from achievements app*

```ts
const prodAppConfig: IAppConfig = {
  widgetId: 'achievements_dev',
  pageId: 'challenge_page',
  widgetType: 'ef4e59bd-625a-484e-9ba1-650d4aecf03b',
  pageType: '847c2f5d-017f-499f-9c3e-069164fc116f',
};

const devAppConfig: IAppConfig = {
  widgetId: 'challenges_dev_widget',
  pageId: 'challenges_dev_page',
  widgetType: '4224a7c4-3783-466b-be3e-b0826d2225da',
  pageType: '642217d5-f1e7-476a-8c55-7241da8e2267',
};

export const APP_CONFIG: { [key: string]: IAppConfig } = {
  [APPS.Prod]: prodAppConfig,
  [APPS.Dev]: devAppConfig,
};

// Later in viewerScript
const appConfig = APP_CONFIG[config.appParams.appDefinitionId];
```
Moreover, with new editor flow, where we want to maintain `.component.json` file for each widget, we should extend it to be something like

*.component.json*
```js
{
  "local": {
      "id": "LOCAL_APP_ID",
    },
  "prod": {
      "id": "PROD_APP_ID",
    }
}
```
 so we'll configure viewerScript to map widgets correctly under the hood.
![excalidraw-202034141034](https://user-images.githubusercontent.com/1521229/75879132-823b1d80-5e23-11ea-9274-0bf290b41c05.png)

### Use Client Spec Map Experiments
Single app approach. Dev center is configured to prod CDN bundles / endpoints.
We are using [Client Spec Map Experiments](https://github.com/wix-private/meta-site/blob/master/wix-meta-site-server/app-store-service/client-spec-map-experiment-server/README.md) to override some values to local ones when experiment enabled.
The flow should be:
- User generates new app with `petri-spec` file, for example `specs.editor-dev-flow.ButtonWidget_local`
- When you add your app to LC, it will create a spec.
- Then you have to create expertiment (probably can be automated)
- Add your Client Spec Map Experiments and create rules to override `viewerScript`, `viewerWidget`, editor app endpoints, etc. (also can be automated in future)
- Enable this experiment via Petry Sidekik or by query param for editor and viewer.
You will see local versions of your apps.
With this approach you don't need to maintain 2 apps, but you need to maintain values to override. On the same time you have single app, which make this flow more reliable. You won't face cases when you added something locally, but didn't on prod version.

For now, this approach is working only for published apps and I'm trying to find people who can help with it.
![excalidraw-202034141034 (2)](https://user-images.githubusercontent.com/1521229/75879929-f924e600-5e24-11ea-9652-a9e26e71e291.png)

Please share you experience and what issues you can see with 1 or 2 approach.
Actually I'm betting on 2 approach and like it more. We can automate more things here and it's more reliable in general.

**Comment by ronnyrin** [comment]
worth mention that in both approachs you will have issues with ssr. In ssr your old code will run and then in csr your new code and you will have conflicts and styles issues.

In stores we usually work only with static override extension for the viewer side and with our local env for the editor (regular `yoshi start`).

**Comment by yavorsky** [comment]
@ronnyrin But why in SSR we'll have old code?
For first case it will be separate app configured to localhost and all content (viewerScript, viewerWidget, css files) will be served from localhost, which is updated.

For second case I assume CSM Experiments will override values before SSR and we'll have localhost versions also. For editor, iFrame will be rendered from lcoal dev-server by yoshi with HMR, etc.

Please correct me if I miss something.

**Comment by bodia-uz** [comment]
We used the same approach as Ronny described (https://github.com/wix/yoshi/issues/2043#issuecomment-594505098).
But if you will resolve editor mode issues with "Use Client Spec Map Experiments", it's should be much better.

About SSR. As I understand, with localhost URLs SSR will fail to render and fallback to CSR. Better to ask the viewer platform.

**Comment by yavorsky** [comment]
@bodia-uz do you use static override? From what I understood you use just configured CSM Experiments with enabled experiment which overrides viewerScript, viewerWidget, etc values.
You are not using static override extension.

@ronnyrin but how static override will solve SSR problem, when platform will still load viewerScript for SSR on its side?

Also, are you sure, platform is not considering values from Client Spec Map Experiments while processing SSR?

cc @gileck

**Comment by bodia-uz** [comment]
> do you use static override? From what I understood you use just configured CSM Experiments with enabled experiment which overrides viewerScript, viewerWidget, etc values.
You are not using static override extension.

Ah. Yes. We used "CSM Experiments" (and sometimes a static overrides) for viewer and dev app for the editor (iframe over OOI)

**Comment by ronnyrin** [comment]
ssr runs somewhere in aws and can't access your localhost from there so if you are using CSME, ssr will failback to only csr. If you are working with static overrides, ssr will run with your product version and only csr will run with your local version.

**Comment by yavorsky** [comment]
@ronnyrin But when using static override, it causes some issues for iFrame. For example, If I will override statics for editor apps or settings pannel apps, it will affect statics inside it, but I can't change the structure of `.vm` file for example. Here we can update react, some global values I can get topology. So to test it I need to GA new version of the server with updated VM.

Moreover, if you are using .html file from cdn instead of server (like site-search), it will cause some security issues and content won't be rendered. Seems like issue is the way static override intercept iframe's `src` path. It's just showing blank page instead of content from `localhost:3200/somefile.html`

**Comment by yavorsky** [comment]
After really fruitful discussion I can propose really simple solution, that will solve issues of maintaining 2 applications, maintaining client spec map experiments and different version for bolt's SSR and CSR.

### Url overrides
Inspired by sled approach, we can override ooi urls we need for viewer part.
It's `viewerScript`, `viewerWidget` and `baseStaticsUrl` urls.
The issue was that we didn't have editor support for this, since rendering iFrame is a bit different flow. But for now all PRs are merged and current flow is working as expected.

After `yoshi start` we can auto open viewer and editorUrl with needed query params to override. Moreover, we can override multiple widgets ifrmae paths.

Our flow will match requirements that I see really convenient:
- We don't need to maintain second app
- We don't need to maintain Client Spec Map Experiments, creating new spec for each project, creating new experiment etc.
- Overrides are flexible according to local project structure. After adding / removing widget locally, new url will represent relevant override map.
- We can create a tunnel to localhost or verify ip is static, public and use this value instead of localhost for viewer urls override. This will solve issue when SSR fallbacks to CSR or use public version on for SSR and local for CSR.

So for now, we can use
- `tpaWidgetUrlOverride` and `tpaSettingsUrlOverride` to override editor app and settings pannel apps. 
- `widgetsUrlOverride` to override viwerWidget bundle.
- `viewerPlatformOverrides` to override viewerScript bundle.

Platform changes:
[Santa PR](https://github.com/wix-private/santa/pull/46987) (allow override wigetUrl)
[Editor PR](https://github.com/wix-private/santa-editor/pull/26890) (allow pass query params to editor)
[Document management PR](https://github.com/wix-private/document-management/pull/1881)

The only issue I can see is that we'll have long inconvenient urls, but since we'll generate it automatically it won't be a problem. Also we can shorten it if we want to display in console after start.

**Comment by ronnyrin** [comment]
I think you still have issues with preview mode because it's going to be OOI as well but the preview itself is an iframe in the editor. How would you pass the overrides to it?

**Comment by yavorsky** [comment]
@ronnyrin I've opened Prs to editor, DM and viewer which fixes it:
https://github.com/wix-private/santa/pull/46987
https://github.com/wix-private/santa-editor/pull/26890
https://github.com/wix-private/document-management/pull/1881

**Comment by yavorsky** [comment]
cc @netanelgilad This is an RFC I talked yesterday. We should probably have a sync about suricate integtaion

**Comment by netanelgilad** [comment]
> We can create a tunnel to localhost or verify ip is static, public and use this value instead of localhost for viewer urls override. This will solve issue when SSR fallbacks to CSR or use public version on for SSR and local for CSR.

Yep you can use suricate to tunnel the requests to the localhost server. Since there are url override, the only thing needed is to use the suricate url instead of localhost, and it should work for SSR as well. 

We are building a similar solution for building components in `editor-elements` and I think maybe the solution should be the same. There are some considerations about loading the local code in production SSR servers (memory leaks, failures, etc...) so in `editor-elements` the plan is to run a local thunderbolt server that loads the local `editor-elements` from the yoshi CDN.

cc @gonengar @NitayRabi Hopefully I'm not mixing concerns, but I think there could be a joint effort here to solve those issues in the `yoshi` flows with built-in suricate integration.
