### ISSUE TITLE
App server is not being closed after SIGINT (ctrl+c)

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#2095]
# 🐛 Bug Report

### 😯 Current Behavior

When starting yoshi serve and cancel it using `ctrl+c` (sending a SIGINT signal) it stays opens, the app server process stays up.

### 🤔 Expected Behavior

All the child processes will be closed when the parent process is interrupted.

### 👣 Steps to Reproduce 
Use the API as mentioned here - https://wix.github.io/yoshi/docs/api/node#yoshi-serve

Try to close it using `ctrl+c`

Go the the browser (`http://localhost:3000`)

See that it's still working and that you have an open node process.

### 🌍 Your Environment

Yoshi v4.47.3

**Comment by daliusd** [comment]
New correct API link: https://wix.github.io/yoshi/docs/node-api/#yoshi-serve

I don't reproduce this issue however.

**Comment by ranyitz** [comment]
Fixed on #2504
