### ISSUE TITLE
[jest-yoshi-preset]: add "globals" jest option for "e2eOptions"

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#2102]
# 🙋 Feature Request

### 😯 Current Behavior
It's not possible to configure `e2e` test environment "globals" and therefore hard to turn off `ts-jest`'s `diagnostics` options

### 🤔 Expected Behavior
The way to configure `ts-jest` is [via "globals" option in jest config](https://huafu.github.io/ts-jest/user/config/diagnostics), this should be exposed so we will be able to turn off diagnostic if we would like too, just like in the spec environment (`specOptions`)

### 💁 Possible Solution 
See this PR for reference - https://github.com/wix/yoshi/pull/1952

https://github.com/wix/yoshi/blob/03967b23792c0791a2709ced4b2c14808f9efb7a/packages/jest-yoshi-preset/jest-preset.js#L31-L39

### 🔦 Context

I think that it's opinionated, but I would probably prefer warnings over throwing an error in tests, just because when debugging tests, it can be very annoying

**Comment by lironch** [comment]
@ranyitz you can close this issue can now 👍

**Comment by ranyitz** [comment]
Thanks @lironch. Closing
