### ISSUE TITLE
yoshi start --url multi parameters

### ISSUE THREAD

**Issue by dudubernhard** [wix/yoshi#2105]
### 😯 Current Behavior

In my project I'm starting my app with (package.json):
"start": "yoshi start --url localhost:3000/111?referrer=PremiumPurchasePlan&domainName=&siteId=222",

Current Behavior:
opens: http://localhost:3000/111?referrer=PremiumPurchasePlan (only the first query param).

I tried to replace & with %26 - but it is not helping.

### 🤔 Expected Behavior

show full url:
localhost:3000/111?referrer=PremiumPurchasePlan&domainName=&siteId=222

Thanks,
Dudu.

**Comment by yavorsky** [comment]
@dudubernhard Your command cause bash syntax error and it just works till last allowed symbol in npm.scripts environment.
You tried to replace &, but you still have `?`.

If you try: `yoshi start --url localhost:3000/111?referrer=PremiumPurchasePlan&domainName=&siteId=222` not inside script, but explicitly, you'll probably have error like `parse error near `&'`.

So you can:
- Wrap your url with `\"` and it will work as expected
- Or add `\` before all `?` and `&` in your script.

**Comment by dudubernhard** [comment]
Hi.
First - thanks!
I tried all permutations of \, \\, \", ', ... but all of them are not
working.
Do you have any other ideas ?
You can check on the repo:
https://github.com/wix-private/premium-success-pages

Thanks.

**Comment by yavorsky** [comment]
I just tried it with wrappign url in `\"` and seems it's working fine.
<img width="1352" alt="Screen Shot 2020-03-18 at 2 30 49 AM" src="https://user-images.githubusercontent.com/1521229/76913723-86a21480-68c0-11ea-8459-5de78b6cd8fe.png">

Opened PR:  https://github.com/wix-private/premium-success-pages/pull/10

Please let us know if it's still now working as expected

**Comment by dudubernhard** [comment]
opsssss, don't know why it didn't work for me, My Bad.
if you want you can add it to the yoshi doc:
https://wix.github.io/yoshi/docs/api/cli

Thanks a lot !
