### ISSUE TITLE
eslint-config-yoshi-base update rule

### ISSUE THREAD

**Issue by malcolmmadsheep** [wix/yoshi#2144]
# 🙋 Feature Request

[Update rule `no-useless-constructor`](https://github.com/wix/yoshi/blob/master/packages/eslint-config-yoshi-base/index.js#L167) for `*.ts,*.tsx` files.

### 😯 Current Behavior

For example we have class with a constructor which accepts optional param and assign it to class' private field:

```ts
class A {
  constructor(private x?: number) {}
}
```

With this rule enabled `no-useless-constructor` we got an error that constructor is unused.

### 🤔 Expected Behavior

Such a constructor should be valid for TS classes.

### 💁 Possible Solution

Solution is simple:

```json
{
    "no-useless-constructor": "off",
    "@typescript-eslint/no-useless-constructor": "error"
}
```

What do you think?

(I wanted to submit PR with this, but couldn't even push branch 😞)

**Comment by ranyitz** [comment]
@malcolmmadsheep Awesome explanation! We'll definitely accept a PR for that :)

You can't push a branch, but you can have your own fork and send the PR from there 🙂
