### ISSUE TITLE
[RFC] BoB apps support for yoshi-flow-editor

### ISSUE THREAD

**Issue by yavorsky** [wix/yoshi#2146]
#### This issue related to best-of-both apps support for editor flow

Terminology (will be updated):
**bob** - Best-of-both. Best of platform and app builder. We can build platform apps using app-builder and import it in editor.
**ooi**  - Out of iframe. Apps that's running in viewer not wrapped in iframe. Still wrapped in iframe in editor environment.

Seems like we can reuse a lot of logic between platform apps and ooi apps. Since we have different UI part (widgets), we still can use controllers, which is automatically collected and output as `viewerScript.bundle.js`.
Moreover we're working on `editorScript` support. At first iteration, it will be just an entry-point for `editorScript.bundle.js`. Users will control what this module is exporting, and what additional logic contains. The only thing - we need to prevent breaking changes in future to prevent people pinning `yoshi-flow-editor` version 👀and always get fresh feedback. So it will be our wrapper, which is basically pass everything from user's module.

Here is proposed update for current template. It's very raw and I can miss some things. But the idea is to make everything simple and consistent. Moreover, it would be really cool if some teams that has few components wanted to migrate from OOI to platform components can use the same app and do it consequently.

```
src
   components
        some-platform-component
           .component.json
            Settings.ts
            viewer.controller.ts
            editor.controller.ts
        some-ooi-component
           .component.json
            Settings.ts
            controller.viewer.ts (former controller.ts)
            Widget.ts
editor.app.ts
viewer.global.ts
.application.json
```
We've tried to find what could be common for these types of components.
Let's take [conferencer-bob app](https://github.com/wix-private/conferencer-bob/tree/master) as an example.

#### viewerScript (controller.viewer.ts)
[Widgets directory](https://github.com/wix-private/conferencer-bob/tree/0ca75a0c56d4ddf3603277fc31aa35647e787b30/src/widgets/speakersWidget) contains 2 types of widgets `.viewer.ts` and `.editor.ts`. Initially I thought abut it as a widget replacement. But actually it's controllers. Widget part is hidden from us at all.
It doesn't render anything, but just configure in declarative (editor) or imperative(viewer) our widgets. We even load viewer controller via `viewerScript.bundle` [inside createControllers function](https://github.com/wix-private/conferencer-bob/blob/0ca75a0c56d4ddf3603277fc31aa35647e787b30/src/viewerApp/viewer.js#L20)

To be more consistent, we can rename controller.ts to `viewer.conroller.ts` for ooi apps. It will give more clarity for people who working on ooi apps first time.

#### editorScript (controller.editor.ts)
Editor controllers are being [imported and consumed](https://github.com/wix-private/conferencer-bob/blob/0ca75a0c56d4ddf3603277fc31aa35647e787b30/src/editorApp/editorModule.js#L87-L89) to platform inside `editorScript.bundle`.

Since ooi part doesn't have any reason to be separated by components, we are not going to have `editor.controller.ts` for ooi component types. (We can think a bit about it and maybe it's possible to split current editorScript, but can't give good answer.)

#### Settings panel
[Settings will look the same](https://github.com/wix-private/conferencer-bob/tree/0ca75a0c56d4ddf3603277fc31aa35647e787b30/src/editorApp/panels). It's a react app that use editor sdk and other APIs. The same we have for ooi.

So the thing is we have a lot of similar things and definitely can create common flow for it.

#### global viewerScript and editorScript
Another proposed change is to create common `editorScript.global.ts` and `viewerScript.global.ts` files (maybe with different naming).
For ooi and platform apps we need to include single `editorScript` file with app-level logic. For example [platform apps](https://github.com/wix-private/conferencer-bob/blob/0ca75a0c56d4ddf3603277fc31aa35647e787b30/src/editorApp/editorModule.js) and [ooi apps](https://github.com/wix-private/strategic-products/blob/master/achievements/web-client/challenges-web-platform/src/editor/editor.ts) use it to install pages for the whole app, etc.

something like editorScriptWrapper.ts. *(THIS WILL BE GENERATED UNDER THE HOOD)*
```ts
// app-level editor controller
export * from 'editorScript.global.ts'

// component-level controller only for platform apps.
import editorController1 from 'components/some-platform-app/editor.controller.ts' 
import editorController2 from 'components/other-platform-app/editor.controller.ts' 
editorScriptBuilder()
  .withWidget(editorController1)
  .withWidget(editorController2)
```

For `viewer.controller.ts` I have not so strong confidence, but we still can have some app-level hadlers, for example `initAppForPage`.

This scripts will be imported by our main editorScript and viewerScript wrappers and then do some additional magic - collect all viewer and editor controllers under the hood.

#### Questions that we ask ourselves before making it live:
- Is it possible to mix ooi component and platform component in the same app
- Should create new template for this approach? I think yes, since it will not just bootstrap everything, but give really basic knowledge. We'll also have different UI part as it was said.
- Everything else from the comments 😉

#### Very very very raw 🍣 todo list:
- [ ] Investigate more and more
- [ ] Migrate example bob app to yoshi-flow-editor. (https://github.com/wix-private/conferencer-bob)
- [ ] Refactor editor-runtime to contain helpers/wrappers for both component types. (Add https://github.com/wix-private/bob-widget-services)
- [ ] Create new create-yoshi-app template for platform app.
- [ ] Collect `editor.controller`s into single editorScript.
- [ ] Generate app editor manifest for all components.
- [ ] Extend `editorScript` wrapper with some useful stuff (translations, experiments, etc)
- [ ] Update documentation for these changes

#### What we can reuse?

- `start`/`build` with updated entryPoints
- HMR
- Override urls for local development mode
- `.application.json` and `.components.json` configuration.
- `.ci_config` builder
- `settings` and `controllers` wrappers
- general infrasturcture

> It's a raw issue and will be updated often.

**Comment by maoryosef2** [comment]
First of all this looks really great.

**some comments**
 `.application.json` - what will this (or currently) include?

> For `viewer.controller.ts` I have not so strong confidence, but we still can have some app-level hadlers, for example `initAppForPage`

I think that it is a must, since this is your way to init something on the app level, so even if we just expose `initAppForPage` and hide the entire `createControllers` part, it is still very useful.

>Is it possible to mix ooi component and platform component in the same app?

There is no technical limitation that I am aware of it, and I think that it will make sense for application to be in a migration phase or even do A/B tests, which will include both types of widgets,  though maybe @gileck @itaiche knows about possible limitations?

**regarding the general structure**
it's very similar to what was created for our sample app.
Though I am less in favour of having the same file names (`viewer.controller.ts`/ `editor.controller.ts`) separated by folder name, IMO it makes it hard to navigate the code in your IDE and when debugging in the browser

**Additional Feature - Public API**
In platform apps, the controller can expose an api for consumers to use with corvid.
It is exposed both in the viewer (the actual API) and the editor (for intellisense).
We can add a JSON schema in `.component.json`, and use it to validate the exported props in the viewer, and to generate the needed manifest.

**Comment by yavorsky** [comment]
> some comments
.application.json - what will this (or currently) include?

This will include appDefinitionId. We need it to create override query params for local experience. For now, user should add `appDefinitionId` for app and `id` for each widget (this helps us to generate viewerScript with `createControllers` under the hood). 

>I think that it is a must, since this is your way to init something on the app level, so even if we just expose initAppForPage and hide the entire createControllers part, it is still very useful.

Cool. We can still have it optional. And most ooi apps will ignore it, but if you need, you can have it.

>There is no technical limitation that I am aware of it

Wow, that sounds really cool. Then we can think in terms not `ooi` or `bob` app, but component. Migrations from ooi to bob for bigger projects will be gradual and smooth!

> Though I am less in favour of having the same file names (viewer.controller.ts/ editor.controller.ts) 

But you can navigate by folder name. The basic idea is taken from next.js, where your logic separated by 'routes'. And with this approach we still have to follow convention to collect all controllers coupled by widget.

> We can add a JSON schema in .component.json, and use it to validate the exported props in the viewer, and to generate the needed manifest.

Sounds reasonable 👍
