### ISSUE TITLE
Managing dependency updates of "problematic" packages

### ISSUE THREAD

**Issue by amitdahan** [wix/yoshi#2176]
# Summary
Currently renovate manages our dependencies fairly well, apart from a few dependencies, like `@babel/*`, or just any `@types/*` dependency.

With #2174 we'll be ignoring `@babel/*` packages, we'll manage them manually until we find a better solution.

Any better ideas?

In the case of babel I feel we have to manually align ourselves with the dependencies we cannot control.
For example, in the case of the latest (as of writing this) updates to `@babel/*`, we were "held back" from updating (type errors) by hoisted lower-versions of said packages that came to be because latest `storybook` is still locked on it.

**Comment by amitdahan** [comment]
Alternatively - we can use yarn resolutions.
But resolutions only makes sense for `devDependencies`, unless I'm mistaken.

**Comment by ranyitz** [comment]
For starters, it would be good to distinguish between changes that may affect users and changes that only affect us.

(dependencies vs devDependencies)

We'll treat each update differently, I know that this is possible via renovate.

________________

Updating `@types` of dependencies has a high chance to be a breaking change.
But updating `@types` of devDependencies can only break yoshi's local `build` process.

Packages that has a separate `@types` package are doomed to be hard to maintain as someone needs to maintain the connection between the types and the production code.
