### ISSUE TITLE
Yoshi starts dev/server.ts file without transpilation

### ISSUE THREAD

**Issue by maxaon** [wix/yoshi#2232]
# 🐛 Bug Report

### 😯 Current Behavior

yoshi doesn't transpile dev/server.ts file in legacy flow and server fails to start

### 🤔 Expected Behavior

server should start

### 👣 Steps to Reproduce 

clone demo repo: https://github.com/wix-a/test-yoshi-dev-server
npm install && npm start
see error in target/server.log

### 🌍 Your Environment

```
 Yoshi config
{
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM",
    "@wix/fedops-logger": "fedopsLogger"
  },
  "hmr": "auto"
}
```

**Comment by ranyitz** [comment]
@maxaon This is the legacy flow, and as legacy we don't provide new features to improve it. Why aren't you using the app Flow?
