### ISSUE TITLE
Use more strict eslint rules

### ISSUE THREAD

**Issue by ronami** [wix/yoshi#224]
We should have a base eslint config and a fullstack (react) one.

Yoshi itself should be linted with the base config. Generated fullstack (possibly client) projects should use the fullstack eslint config.

Once Yoshi becomes a monorepo the eslint config should be a separate package.

**Comment by ranyitz** [comment]
We now lint ourselves using `eslint-config-yoshi-base` which is awesome.

The next stage would be to create `eslint-config-yoshi` (for client/fullstack projects) and also provide it to our consumers.

**Comment by ronami** [comment]
Relevant: #265.

**Comment by ronami** [comment]
Will be released as `eslint-config-yoshi-base` and `eslint-config-yoshi` in v3.
