### ISSUE TITLE
Extending classes can cause issues do to babel transpilation 

### ISSUE THREAD

**Issue by NitayRabi** [wix/yoshi#2281]
# 🐛 Bug Report

### 😯 Current Behavior

- When running `yoshi start` ES6 classes are not transpiled by babel. 
- When running `yoshi build` ES6 classes are transpiled.

This can cause (in a very specific flow) the following issue - 

- https://wix.slack.com/archives/CAP85K0P3/p1587454060038500
- https://stackoverflow.com/questions/51860043/javascript-es6-typeerror-class-constructor-client-cannot-be-invoked-without-ne

#### What's happening here ? 

- Given application `A` (e.g `Editor`), which serves an application fully built and transpiled (including ES6 classes), consuming package `B` (e.g `wix-ui-santa`) from an external source, and allows overriding using queryParam for testing and local dev purposes.
- When working on package `B`, serving it using `yoshi start` and using it in application `A`, in case a class from package `B` is extends in application `A` code this issue will arise

### 🤔 Expected Behaviour

- This is quite an edge case, but we do have this pattern used in Wix (including overrides and OOP)
- Using OOP approach with dev mode shouldn't break(? - or at least explaining about it in the docs as "gotcha/known issue") 

### Current workaround

- Running `yoshi start --production` provides same build

### 🌍 Your Environment

```
// PASTE HERE
```

**Comment by ranyitz** [comment]
@NitayRabi Thanks for opening this issue. I totally agree. We should look into the issue further.

I wonder what is the cost of transpiling the classes on development as well. In case this does not adds much to the dev time or makes it much harder to debug your code, it's a considerable option.
