### ISSUE TITLE
Add ability to turn off `webpackbar`

### ISSUE THREAD

**Issue by sidoruk-sv** [wix/yoshi#2347]
# 🙋 Feature Request

### 😯 Current Behavior

For now, `webpackbar` is awesome, but for debug needs sometimes it is a need to save the output for debugging.

### 🤔 Expected Behavior

`webpackbar` is turned OFF when some parameter (or ENV variable) is passed to yoshi.

**Comment by sidoruk-sv** [comment]
Resolved by: #2344

`PROGRESS_BAR=false`

**Comment by ranyitz** [comment]
@sidoruk-sv, that's great that you've opened an issue for this! I think that in case you're debugging you don't want webpackbar at all. For example, during start we don't clear the screen in case you use `DEBUG=true` environment parameter.

https://github.com/wix/yoshi/pull/2142

If you ask me, when `DEBUG=true` is used we can remove webpackbar completely. It's important to say that `PROGRESS_BAR=false` doesn't remove it completely but instead it changes the UI to be the "basic" UI which leaves much less clutter on the screen. While this is not bad, I would prefer to not have that as well during debugging.

You can see that we have a [`useProgressBar`](https://github.com/wix/yoshi/blob/7f020e7218312f1cf9eeb80b68ea9d27504b797d/packages/yoshi-common/src/webpack.config.ts#L335) option that can be easily disabled in case `process.env.DEBUG==='true'`

**Comment by ranyitz** [comment]
Opened an issue for that - https://github.com/wix/yoshi/issues/2350
