### ISSUE TITLE
E2E tests are failed in yoshi 2.1.1

### ISSUE THREAD

**Issue by adavidof** [wix/yoshi#236]
After migration to yoshi 2 the tests are failed

Project:
https://github.com/wix-private/media-platform-client

CI:
http://tc.dev.wixpress.com/viewLog.html?tab=buildLog&buildTypeId=MediaClient_MediaPlatformClient&buildId=60861598&_focus=3011

How to reproduce locally:
1. `git clone git@github.com:wix-private/media-platform-client.git`
2. `git checkout improvement/yoshi-2.1`
3. `npm install`
4. `npm run build`
5. `npm run test:e2e`

**Comment by adavidof** [comment]
@ranyitz 
any updates?

**Comment by ranyitz** [comment]
Not from my side,
It seems that the app won't `start` (not specifically related to the e2e)
@bildja any updates?

**Comment by adavidof** [comment]
@ranyitz he is on vacation
I'm checking

**Comment by adavidof** [comment]
@ranyitz any updates?

**Comment by yairhaimo** [comment]
I receive timeout errors for e2e tests with Yoshi 1.
Same as with yoshi 2:
`7 specs, 4 failures, 3 pending specs`

**Comment by yairhaimo** [comment]
I just cloned and ran `npm install` and it didnt work.
Can you try to clone from scratch and run e2e on master?

**Comment by adavidof** [comment]
@yairhaimo 
try steps
1. `git clone git@github.com:wix-private/media-platform-client.git`
2. `git checkout improvement/yoshi-2.1`
3. `npm install`
4. `npm run build`
5. `npm run test:e2e`

**Comment by adavidof** [comment]
@ranyitz 
any updates?

**Comment by bildja** [comment]
@yairhaimo @ranyitz in yoshi 1 it DOES work on CI now, build runs the e2e and it passes, and afaik it didn't after update of yoshi 2, that's why it was rolled back to y1, right, @adavidof ?

**Comment by ranyitz** [comment]
@bildja yes, it is clear.
Now we only need to debug and understand why.

**Comment by ronami** [comment]
Hey @adavidof @bildja 

I'm trying to clone and run the project locally with `master` branch but I'm getting typescript errors. Can you help me run the project locally with `master` branch? It would help me to have a working branch with Yoshi v1 so I can understand what's wrong with v2.

Thanks! :)

**Comment by bildja** [comment]
@adavidof please assist.

**Comment by adavidof** [comment]
@ronami 
the build is green
try to fetch the latest master and do the:
```bash
npm install
npm start
```

**Comment by yairhaimo** [comment]
@adavidof - Just wanted to let you know that we **are** working on this. It's just a complicated issue and its taking longer than we expected. Thanks for your understanding.

**Comment by bildja** [comment]
@yairhaimo hi, it's been a month and a half since the issue is open and we don't update to yoshi 2. Maybe if the issue is that complicated we might want to decide that it's not worth it and we come up with some solution? (not update to yoshi 2, not run the e2e, run them in a different way, etc.)

**Comment by ranyitz** [comment]
@bildja @adavidof Good news, I've checked today with our new version `yoshi@3`, which is in late stages of `alpha`. And it seems to be working perfectly.

Just update to version `{ yoshi: ^3.0.0-alpha.12 }` and you're good 👍

**Comment by bildja** [comment]
Seems to be working with 3-alpha after numerous of fixes on our side (minor ones though), thanks, @ranyitz

**Comment by ranyitz** [comment]
no probs. Please note that version 3 is in beta and might have some breaking changes. If it's urgent use a specific version, or wait until the official version :)
