### ISSUE TITLE
Issue with yoshi/types and Stylable *.st.css declarations

### ISSUE THREAD

**Issue by simast** [wix/yoshi#2387]
# 🐛 Bug Report

### 😯 Current Behavior

Adding `import('yoshi/types')` and Stylable declaration to the same `external-types.d.ts` file causes Stylable import not to work correctly in TypeScript. Instead of Stylable `*.st.css` declaration - `*.css` is being used form Yoshi:

<img width="472" alt="Screenshot 2020-05-13 at 10 39 10" src="https://user-images.githubusercontent.com/433527/81784842-21f0e800-9506-11ea-9e74-4439fcb3f877.png">

### 🤔 Expected Behavior

We can use `import('yoshi/types')` and custom Stylable declaration together (as yoshi/types does not provide its own Stylable module declaration).

### 🔦 Context 

I was following the migration guide which suggested to replace and use this in a `external-types.d.ts`:

```ts
import 'yoshi/types'
``` 

Which is actually a bad thing - because imports at the top level turn the file into a local module (not a global ambient one). All the other custom `declare module` statement become invisible in the global context. The solution since TS 2.9 is to replace this with `import('yoshi/types')` - which works fine but introduces a weird issue where when you have `App.st.css` impot - it is picking styles for `*.css` coming from yoshi/types and not your custom `declare module '*.st.css'`.

### 💁 Possible Solution 

It would be nice if Styleable declare module declaration were not separate but part of `yoshi/types`? Not sure if that would solve the issue of `*.css` overriding `*.st.css` however.

### 👣 Steps to Reproduce 

1. Create a TypeScript yoshi project.
2. Remove node_modules/yoshi/types reference import from tsconfig.
3. Add the following code to your `extenral-types.d.ts`:

```ts
import('yoshi/types')

declare module '*.st.css' {
  const stylesheet: import('@stylable/runtime').RuntimeStylesheet;
  export = stylesheet;
}
```

4. Try to import Stylable file.

### 💻 Code Sample

```ts
import('yoshi/types')

declare module '*.st.css' {
  const stylesheet: import('@stylable/runtime').RuntimeStylesheet;
  export = stylesheet;
}
```

### 🌍 Your Environment

```
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
  Binaries:
    Node: 12.16.2 - /var/folders/44/d8s143gn0cl85cvm8vfrj1q80000gp/T/fnm-shell-6584735/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.14.4 - /var/folders/44/d8s143gn0cl85cvm8vfrj1q80000gp/T/fnm-shell-6584735/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    @storybook/core: Not Found
    @storybook/react: Not Found
    babel-preset-yoshi:  4.57.2 
    eslint-config-yoshi:  4.71.0 
    eslint-config-yoshi-base:  4.71.0 
    jest-yoshi-preset: ^4.1.0 => 4.72.0 
    storybook: Not Found
    tslint-config-yoshi:  4.32.0 
    tslint-config-yoshi-base:  4.22.0 
    typescript: ~3.7.5 => 3.7.5 
    webpack:  4.43.0 
    yoshi-config:  4.72.0 
    yoshi-helpers:  4.72.0 
    yoshi-runtime:  1.0.732 

 Yoshi config
{
  "projectType": "app",
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM",
    "@wix/fedops-logger": "fedopsLogger"
  },
  "hmr": "auto"
}
```

**Comment by ranyitz** [comment]
@simast Thanks for opening this issue! If I recall correctly we tried to do this in the past and reverted because it contained a breaking change - https://github.com/wix/yoshi/pull/2024

I think that those types required a specific version of TypeScript. If so, we can provide this on yoshi@5 an declare a minimum version of TypeScript that can work with it.

**Comment by simast** [comment]
Sure, is there a workaround now how to get this working on current Yoshi version however?

**Comment by ranyitz** [comment]
> Remove node_modules/yoshi/types reference import from tsconfig.

@simast If you don't do that, is there a problem?

(Use `yoshi` types from your `tsconfig.json` file)

**Comment by simast** [comment]
We have a monorepo where `yoshi` is hoisted to the root. I guess the solution in this case is to just include `../../node_modules/yoshi/types` in `tsconfig`? I will give it a try.

**Comment by simast** [comment]
Seems to work 👍

**Comment by amitdahan** [comment]
Hey @simast! While working on #2604 I found a trick to still use node's resolution algorithm to resolve yoshi's correct path for type inclusion :)

```typescript
/// <reference types="yoshi/types" />
//  and potentially:
/// <reference types="jest-yoshi-preset/types" />
```

**Comment by amitdahan** [comment]
Regarding conflicts with `.st.css` I found the the order of declaration matters, so I'd declare the `.st.css` module above the reference comment, as seen here:
https://github.com/wix/yoshi/blob/089ed38a3d8f379ab32f037dfd957550ba6cf1c6/packages/yoshi-flow-editor/types.d.ts
