### ISSUE TITLE
Deprecate/remove wallaby's mocha-ts

### ISSUE THREAD

**Issue by roymiloh** [wix/yoshi#239]
[wallaby-mocha](https://github.com/wix-private/yoshi/blob/master/config/wallaby-mocha.js) supports TypeScript for a long (long) time, it's time to deprecate/remove [wallaby-mocha-ts](https://github.com/wix-private/yoshi/blob/master/config/wallaby-mocha-ts.ts).

**Comment by ranyitz** [comment]
@roymiloh we've moved some files, so now it's here - 
https://github.com/wix/yoshi/blob/master/packages/yoshi/config/wallaby-mocha.js
https://github.com/wix/yoshi/blob/master/packages/yoshi/config/wallaby-mocha-ts.ts

I would love to have that land on version 3.0.0.

We need a PR that adds a deprecation warning, we'll merge it to master. (version 2) And another PR that removes it completly to version 3.

PRs welcome!
