### ISSUE TITLE
RFC for monorepo flow: run build for specific pacakge

### ISSUE THREAD

**Issue by tuchk4** [wix/yoshi#2415]
# 🙋 Feature Request

### 😯 Current Behavior

when run `yoshi build` at the root – yoshi builds all packages.
Sometimes I would like to rebuild the only specific package to not to wait for the whole build.

### 💁 Possible Solution 
If just run `yoshi build` at the package – it works. But as I know – the main "philosophy" of the monorepo flow is that all commands should be run from the root. That's why maybe we can extend the build command and pass the package name.

```
yoshi build editor-elements-registry
```

I am OK with the first option – run `yoshi build` at the package. 
So nothing needs to be done at yoshi :)

**Comment by amitdahan** [comment]
You mean like this: https://github.com/wix/yoshi/pull/2299 ? 😃 
(It only builds "app" sub-projects selectively, it still runs `tsc -b` on all projects.

**Comment by tuchk4** [comment]
@amimagid Yes, exactly. 

As I understand, we should use `yoshi-monorepo` bin to run build script?

or we can run `yoshi build app-a app-b`?

**Comment by amitdahan** [comment]
Yeah, sorry, that'll work too!

**Comment by ranyitz** [comment]
@tuchk4 So as @amitdahan said, it's possible to run `yoshi build [...appName]`.

We would like to add support for running build from a specific app. By understanding the current working directory we'll be able to run the build for that specific package. (It would be another way to do the same thing, but it makes sense to want to build a certain package when you are working only on it)

**Comment by tuchk4** [comment]
I have checked, `yoshi build {packageName}` works for us.

I think we can close this issues since this completely resolves what I need

**Comment by tuchk4** [comment]
@amimagid  #2299 works only for packages with `type: 'app'`.
https://github.com/wix/yoshi/blob/master/packages/yoshi-flow-monorepo/src/load-package-graph.ts#L64


In our case, I would like to `yoshi build conventions`, where `conventions` is not `type: 'app'` :)


cc @ranyitz

**Comment by ranyitz** [comment]
Yeah, it's a naive heuristic. We'll surely need to change it in the future.
