### ISSUE TITLE
Have an ability of setup step on start

### ISSUE THREAD

**Issue by roymiloh** [wix/yoshi#242]
# Overview
My app communicates with several http/ws/db services (via RPC, WS, Redis, MongoDB etc), so in order to run it locally, I need to put up these services before starting my app (by using testkits or the services themselves).
Today I can do that, but via the [entryPoint](https://github.com/wix/yoshi/blob/master/yoshi/lib/tasks/run-server.js#L21) flag, it means that every time I change a file, the process [will be killed](https://github.com/wix/yoshi/blob/master/yoshi/lib/tasks/run-server.js#L39) and [spawned again](https://github.com/wix/yoshi/blob/master/yoshi/yoshi-start.js#L18) - completing the whole process of restarting those services takes time.

I'd like to have the ability to define a setup step which occurs once per `yoshi start`. So for example my Redis service will be getting started at the very beginning of the process, then on every change I'll just flush it (a way cheaper than restarting the entire Redis).

# Solutions
I had two solutions in my mind:
1. Instead of killing the `entryPoint` process, we can communicate with. So on every change we can send a `CHANGED` message and my entryPoint will decide how to handle it. If `entryPoint` is the file that has been changed, we'll have to kill it entirely and spawn it again, but that's pretty rare case. 
2. Having another flag called `setupFile` (could be also under yoshi config), so we'll simply spawn it once and that's it. Again, if `setupFile` changed, we will kill & spawn it.

Personally I prefer no.1, it feels more powerful to the end users.

\*  Yes, we can make abstractions on top of `yoshi start`, but why?

**Comment by viliusl** [comment]
@roymiloh - I like No. 1. But I instead would follow unix dichtonomy and send `SIGHUP` signal - node default behavior is to die in this case (then yoshi could just respawn it) and if developer added listener via: 

```js
process.on('SIGHUP', () => {
 // restart what you want
});
```

then process will stay alive.
