### ISSUE TITLE
Better error message when users don't have `yoshi-style-dependencies` 

### ISSUE THREAD

**Issue by amitdahan** [wix/yoshi#2430]
# Summary

Today, users who don't include `yoshi` in their deps, don't get `yoshi-style-dependencies`, and have to know they need to specify it manually.

The error they see whenever they run their build is something like:

```
Module not found: Can't resolve 'yoshi-style-dependencies' in '...'
```

I think if we explained this in a custom error it would help our users.

Problem is - we only need to error if the user has a direct or indirect import of a `.css` or `.scss` file and wants to bundle his lib.

When do we not show the error?

**Comment by daliusd** [comment]
We have agreed with @amitdahan that most probably message is good enough now. Let's wait until stalebot cleans up this issue (or something else happens).

**Comment by ranyitz** [comment]
@daliusd & @amitdahan If that's the case, we can close this. Thanks
