### ISSUE TITLE
yoshi-library test --passWithNoTests fails with Unknown or unexpected option

### ISSUE THREAD

**Issue by mharsat** [wix/yoshi#2464]
# 🐛 Bug Report

### 😯 Current Behavior

Running `yoshi-library test` with no test files fails with
```bash
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
```
and running `yoshi-library test --passWithNoTests` fails with
```bash
Unknown or unexpected option: --passWithNoTests
```

### 🤔 Expected Behavior

Running `yoshi-library test --passWithNoTests` should not fail when no test files exist

### 💁 Possible Solution

Forward the `--passWithNoTests` flag

### 👣 Steps to Reproduce 

Run `yoshi-library test --passWithNoTests`

### 💻 Code Sample

[https://github.com/wix-private/wix-ricos/blob/18a0b3513482273a483b95841410079f7337ccad/wix-ricos-editor/package.json#L21](https://github.com/wix-private/wix-ricos/blob/18a0b3513482273a483b95841410079f7337ccad/wix-ricos-editor/package.json#L21)

### 🌍 Your Environment

```
"yoshi-flow-library": "^4.77.4"
```

**Comment by ranyitz** [comment]
@mharsat Thanks for opening this issue, while we can enable each option specifically I think that in this case it would be best if we could forward the rest of the cli arguments to jest, similarly to what has been done [here](https://github.com/wix/yoshi/pull/618)

PRs welcome
