### ISSUE TITLE
Update create-yoshi-app to download latest version under the hood

### ISSUE THREAD

**Issue by yavorsky** [wix/yoshi#2481]
# 🙋 Feature Request

### 😯 Current Behavior
Currently a lot of people are installing `create-yoshi-app` as a global package and use it for months. It's bad b/c we are updating it a lot, so users should receive latest ones.

We are asking to use `npx create-yoshi-app@latest` in docs, but anyway it's being ignored by 
users.

### 🤔 Expected Behavior
The create-yoshi-app should always use latest version.

### 💁 Possible Solution 
Would be good if we'll have create-yoshi-app as a wrapper with latest version loader inside.
It will download latest version of our runner with latest templates and scripts.

Users can still use global version, so a lot of issues of using outdated version will be resolved.

`create-yoshi-app my-app` -> GET create-yoshi-app@latest -> execute it

**Comment by daliusd** [comment]
IMHO this would be non-standard behaviour in node world. As well this would introduce some new problems. E.g. imagine situation where yoshi has new bug and yoshi team needs to recommend using different (older) version. In such situation we would end-up with pressure on yoshi team to fix problem asap as it will be impossible to use older version.

CRA added following text to their documentation: "If you've previously installed create-react-app globally via npm install -g create-react-app, we recommend you uninstall the package using npm uninstall -g create-react-app to ensure that npx always uses the latest version." . I think we can add similar documentation to create-yoshi-app and that would be good enough IMHO.
