### ISSUE TITLE
Failed to compile. Module not found: Can't resolve '@wix/platform-editor-sdk'

### ISSUE THREAD

**Issue by davydof** [wix/yoshi#2534]
# 🐛 Bug Report

### 😯 Current Behavior

Probably it relates to https://github.com/wix/yoshi/issues/2533

After I add import `import { EditorSDK } from '@wix/platform-editor-sdk';` I get the error:
```
Failed to compile.

(client) ./features/***/***.ts
Module not found: Can't resolve '@wix/platform-editor-sdk' in '****'
```

### 🤔 Expected Behavior

Should work without any error.

### 👣 Steps to Reproduce 

1. Clone this repo:
https://github.com/wix-private/accessibility-wizard

2. `yarn`

2. Switch to branch
https://github.com/wix-private/accessibility-wizard/tree/import-error-2

3. `yarn start`

You will see the error

Open the file `AlternativeText.rule.ts`

And uncomment line 20:
`// type EditorSdk = EditorSDK;`

and change `EditorSDK` -> `EditorSdk` on line 26

And the error will be gone

OR

Comment line 22:
`// @injectable()`
and remove `@inject(services.editorSdk)` on line 26, after should be:
`constructor(private readonly editorSdk: EditorSDK) {}`

And the error will be gone as well.

I don't understand why it gives me the error and how debug it.

Typescript doesn't give me any error.

Probably @yavorsky can help with it.

### 💻 Code Sample

https://github.com/wix-private/accessibility-wizard/tree/import-error-2

### 🌍 Your Environment

```
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: Not Found
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
    Safari: 13.1.1
  npmPackages:
    @storybook/core: Not Found
    @storybook/react: Not Found
    eslint-config-yoshi:  4.78.0 
    eslint-config-yoshi-base:  4.78.0 
    jest-yoshi-preset: ^4.1.0 => 4.84.0 
    storybook: Not Found
    tslint-config-yoshi:  4.32.0 
    tslint-config-yoshi-base:  4.22.0 
    typescript: ^3.8.3 => 3.9.3 
    webpack:  4.43.0 
    yoshi-config:  4.84.0 
    yoshi-helpers:  4.84.0 
    yoshi-runtime:  1.0.732 

 Yoshi config
{
  "projectType": "app",
  "entry": {
    "app": "client.tsx",
    "editor": "editor.ts"
  },
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM",
    "lodash": "_",
    "@wix/wix-base-ui/lib": "baseUILib",
    "@wix/fedops-logger": "fedopsLogger"
  },
  "hmr": "auto",
  "exports": "accessibility-wizard",
  "servers": {
    "cdn": {
      "ssl": true
    }
  }
}
```

**Comment by bildja** [comment]
Getting the same:
```
(client) ./widgets/common.ts
Module not found: Can't resolve '@wix/platform-editor-sdk' in '/Users/dmitriyb/projects/bobcast/src/widgets'
```

at https://github.com/wix-private/bobcast/pull/2/files#diff-bb5df1b564feec0dbcfe3c78c514b799R1

The module is installed and the files are there, so it's not clear why

**Comment by bildja** [comment]
https://github.com/wix-private/bob-bootstrap project has lots of imports of this platform sdk lib and it's working..

**Comment by yavorsky** [comment]
@bildja bob-bootstrap is using https://wix.github.io/yoshi/docs/editor-flow/overview to provide a build, but seems like your project is based on yoshi client.

I tried to clone it and start and can see a couple of typescript errors, which seems like pretty relevant:

<img width="1289" alt="Screen Shot 2020-06-17 at 2 32 27 PM" src="https://user-images.githubusercontent.com/1521229/84893115-63e1f080-b0a7-11ea-9212-cbcff022e639.png">

When I just commented out some modules which caused these errors, importing files with editor-sdk seems to work fine.. I think it's rather related to how typescript handling the errors and seems like there are some bugs which causing weird logs..
Can you please fix ts errors except `module not found`, clear webpack cache `rm -r node_modules/.cache` and try again ?

**Comment by bildja** [comment]
@yavorsky typescript errors are fine, the error is runtime one.
Long story short:
I digged a bit and it seems to be not exactly related to `yoshi`, but rather to platform-editor-sdk. Discussed with @zemlanin and Anton will probably come up with the changes to the lib and it will solve this issue.

Longer version:
the problem is when trying to use enum values (in my case specifically it's `const enum`) as runtime values. js-platform-editor-sdk does not create index.js (or any other js files), so there is nowhere to import them from to use as runtime values. The solution might be to create these files with tsc or something.

**Comment by davydof** [comment]
Fixed by
https://github.com/wix-private/js-platform-editor-sdk/pull/569
