### ISSUE TITLE
[FEATURE REQUEST] Multiple Configs

### ISSUE THREAD

**Issue by ChenRoth** [wix/yoshi#260]
# 🙋 Feature Request
multiple configs (per env)

### 😯 Current Behavior

there's a single config for all envs

### 🤔 Expected Behavior

I'd like to have a different yoshi config for different environments

### 💁 Possible Solution 

extends the yoshi config to multiple configs based on NODE_ENV (or some other env variable)

### 🔦 Context 

I'm running angularJS and React together, which for an unknown reason doesn't work well when running Karma with `React` specified as as external in webpack.
the solution would be having a separate config for the test env

### 🌍 Your Environment
```
"yoshi": {
		"hmr": false,
		"entry": {
			"app": "./app.ts",
			"externals": "./externals.ts",
			"mocks": "../test/mock/mocks.ts"
		},
		"specs": {
			"browser": "{src/app.ts,test/mock/appMock.ts,src/**/*.spec.+(js|ts)}"
		},
		"externals": {
			"react": "React",
			"react-dom": "ReactDOM",
			"angular": "angular",
			"jquery": "jQuery",
			"Wix": "Wix",
			"lodash": "_",
			"urijs": "URI"
		}
	}
```

**Comment by ranyitz** [comment]
@ChenRoth You can use the javascript config and make these tests there.

There is no documentation. but see [this PR](https://github.com/wix/yoshi/pull/172)

Also, if you want, you can add it yourself - https://github.com/wix/yoshi/issues/318

Thanks in advance, and let me know if it solves your problem.

**Comment by ranyitz** [comment]
Yoshi aims to be a **zero-configuration** toolkit, we will add more configuration files only when it is the only way.
