### ISSUE TITLE
HMR "auto" not reloading for CSS changes

### ISSUE THREAD

**Issue by itaibenda** [wix/yoshi#262]
# 🐛 Bug Report

### 😯 Current Behavior

I'm working with a newly generated project with Yoshi `HMR` flag set to `auto`. I modify a scss file in dev mode (`npm start`) and save the file. The actual behavior: nothing reloads.

### 🤔 Expected Behavior

HMR should kick in and reload the view

### 🌍 Your Environment

```
  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 8.7.0 - /usr/local/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 5.8.0 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 66.0.3359.139
    Firefox: 57.0.4
    Safari: 11.1
  npmPackages:
    yoshi: ^2.1.2 => 2.1.7

 Yoshi config
{
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM"
  },
  "hmr": "auto"
}
```

**Comment by ronami** [comment]
Solved in #281 (and will be released in v3).
