### ISSUE TITLE
Unable to create using create-yoshi-app due to missing @wix/add-sentry dependency

### ISSUE THREAD

**Issue by arunmadhavan-g** [wix/yoshi#2634]
# 🐛 Bug Report

### 😯 Current Behavior

when I run `npx create-yoshi-app demo` the same fails with the following issue
```
$ npx create-yoshi-app demo
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@wix%2fadd-sentry - Not found
npm ERR! 404
npm ERR! 404  '@wix/add-sentry@^1.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'create-yoshi-app'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/arunmadhavang/.npm/_logs/2020-06-25T17_33_06_789Z-debug.log
Install for [ 'create-yoshi-app@latest' ] failed with code 1
```

Looks like the dependency is removed from npm registry
### 🤔 Expected Behavior

It should have created the project asking for options
...

### 🌍 Your Environment

```
// PASTE HERE
```

**Comment by ranyitz** [comment]
@arunmadhavan-g While we can (and should) improve the error message, the `create-yoshi-app` tool is internal, and therefore you won't be able to use it in order to generate a project. Sorry if the docs were misleading.

Closing
