### ISSUE TITLE
Lint errors for a new generated yoshi editor flow OOI application

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#2644]
# 🐛 Bug Report
<img width="1269" alt="Screen Shot 2020-06-28 at 22 02 49" src="https://user-images.githubusercontent.com/11733036/85956174-ca5eec80-b98c-11ea-9df5-9f09c18bd116.png">

I confirmed that those lint errors are correct. I wonder how our CI didn't caught those problems 🤔 

### 😯 Current Behavior
When generating a new yoshi flow editor ooi app there are lint errors that shows up after the project was generated, which also preventing CYA to do the initial commit.

### 🤔 Expected Behavior
There wouldn't be errors on first creation of a project

### 🔦 Context 
I tried to start a new application

### 👣 Steps to Reproduce 
Create a new editor-flow OOI application

**Comment by amitdahan** [comment]
Related: https://github.com/wix/yoshi/pull/2631#issuecomment-649544256
What are we missing?

**Comment by ranyitz** [comment]
After trying this again, I realized that those were real lint errors, but I got them for another `.eslintrc` that exists in a directory above the one I was generating the project in. So in fact, is a non issue, closing.
