### ISSUE TITLE
״yoshi build --analyze״ does not work on webWorker entries

### ISSUE THREAD

**Issue by ritabazak** [wix/yoshi#2648]
# 🙋 Feature Request

### 😯 Current Behavior

When running --analyze, it only analyzes the regular entries.

### 🤔 Expected Behavior

IF there are webWorker entries, --analyze should analyze those too.

**Comment by ranyitz** [comment]
I think that we did something similar on the monorepo flow https://github.com/wix/yoshi/pull/2295
It should be fairly simple to implement on the app flow as well.

@ritabazak do you want to take this?
