### ISSUE TITLE
BM Flow doesn't support reacting to `config` events in module bundle

### ISSUE THREAD

**Issue by amitdahan** [wix/yoshi#2650]
# Summary 
Same as we did for the `init` method in `BusinessManagerModule` bundles, we need to somehow support reacting to a `configModule` call, for our own module, using the [`BusinessManagerModule.config`](https://github.com/wix-private/business-manager/blob/master/business-manager-api/docs/business-manager-module.md#config) method.

This is currently not available to users in any way.

# Proposed Solution
1. Add a `moduleConfig.ts` convention that'll allow this to work exactly like it works for `moduleInit`.

2. A better approach, but probably more time-consuming would be to have a `module.ts` file that'll replace both `moduleInit.ts` and the mentioned `moduleConfig.ts` file, with 1 file that includes named-exports `init` & `config`:

```typescript
import { ModuleInitFn, ModuleConfigFn } from 'yoshi-flow-bm-runtime';

export const init: ModuleInitFn = ({ moduleParams }) => {
	// something something
};

export const config: ModuleConfigFn = ({ moduleParams }, sourceModuleId, configPayload) => {
	// something something
};
```

**Comment by amitdahan** [comment]
Cc: @netanel89 @just-jeb

**Comment by amitdahan** [comment]
After talking about it we decided approach 2 is good for us.
We'll use `module.ts` and named exports inside it.
This will allow us to support `dispose` in the future if we want.

**Comment by amitdahan** [comment]
@netanel89's [comment](https://github.com/wix/yoshi/issues/2651#issuecomment-652211981) from a related issue is related here as well:


> than in src should be an index.ts that includes the config/init

I think the only thing we said differently was `src/module.ts` vs `src/index.ts`.
Do you think `index` is any better than `module`?
Or would `module.ts` make sense to you as well?

**Comment by just-jeb** [comment]
`module.ts` makes much more sense than `index.ts`.
