### ISSUE TITLE
DOCS: fix link for the `Edit this page` in documentation

### ISSUE THREAD

**Issue by sidoruk-sv** [wix/yoshi#2657]
# 🐛 Bug Report

For now link on `Edit this page` leads to /generated/ file but should lead to the source file, which is a template for generated documentation.

Created because of comment from @amitdahan:
https://github.com/wix/yoshi/pull/2655#pullrequestreview-440771594

**Comment by ranyitz** [comment]
Totally agree, interesting if we can workaround this.

If not, we'll need to open an issue on https://v2.docusaurus.io/

**Comment by sidoruk-sv** [comment]
Ok, then created issue there too:
https://github.com/facebook/docusaurus/issues/3019

**Comment by sidoruk-sv** [comment]
Due to the response from docusaurus (https://github.com/facebook/docusaurus/issues/3019#issuecomment-652395621)

As I understood that:
> Editing the version_docs is a valid case and not a problem, and editing `source` file is the same as editing documentation for the `next` version.

**Comment by ranyitz** [comment]
Thanks @sidoruk-sv. Yes, it's really confusing. We don't have a "next" version that we work on at the moment.

It feels to me that we're not using it right.

Maybe we should just work on the `4.x` docs, remove the [custom script that creates a new version](https://github.com/wix/yoshi/blob/3bb49bc6fa25806e4311f819eee1ed33536ac5a4/scripts/createVersion.js#L49-L97) from the `next` version and use the next version as intended?

I'm ready to do this change. Maybe we can completely remove the `next` version and cut a new one when we start to work on yoshi 5?

What do you say? @amitdahan @yavorsky @sidoruk-sv

**Comment by amitdahan** [comment]
@ranyitz I'm convinced. It felt a little off to me as well and I couldn't point-out why.
