### ISSUE TITLE
Full reload HMR keeps refreshing if used with multiple entries in the same page

### ISSUE THREAD

**Issue by ronami** [wix/yoshi#270]
# 🐛 Bug Report

### 😯 Current Behavior

The bug happens when HMR is set to `true` (the default) with multiple entries all loaded on the same page. The page will start refreshing constantly and won't stop.

### 🤔 Expected Behavior

HMR should reload the page only when a change is detected.

### 💁 Possible Solution 

Not sure, see https://github.com/webpack-contrib/webpack-hot-client/issues/53.

**Comment by shellscape** [comment]
We've merged a fix to `webpack-hot-client` which will be published in the next few days.
