### ISSUE TITLE
Proper handling Typescript

### ISSUE THREAD

**Issue by felixmosh** [wix/yoshi#273]
# 🙋 Feature Request
All of the typescript runs uses the same `tsconfig.json` file, example:
On client & server projects, we wanna get tree-shaking feature (to enable it `module: 'es2015'`), but for server code we would like to transpile to cjs.

Another use-case, allow to lib authors to publish with es2015 files.

### 💁 Possible Solution 

Transpile the code twice, one time with `cjs` and another with `es2015` to a separate folder (`es`), in that way, node code will run on csj, and client can consume efficient es2015.

**Comment by ranyitz** [comment]
Closed on #298
