### ISSUE TITLE
yoshi: remove typescript peerDependency

### ISSUE THREAD

**Issue by viliusl** [wix/yoshi#287]
now, if you have a non-typescript project, `npm install` yields annoying warning (npm@5 will emit error):
```
├─┬ yoshi-tslint@1.0.7
  │ └── UNMET PEER DEPENDENCY typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev
```

We should change that into:
 - remove `peerDependency` of `typescript`;
 - add check to yoshi (yoshi-tslint) that checks if it's a typescript project (contains tsconfig) and then checks if `typescript` is present (require.resolve, or require within try/catch) and if not found, logs error and exits.

**Comment by viliusl** [comment]
ok, this one does not solve the issue - we have tslint with peerDependency as well:/

**Comment by yanivefraim** [comment]
todo:

1. move tslint to devDep, in yoshi-tslint
2. remove typescript peerDep from yoshi-typescript/Yoshi
3. add postinstall script:
a. Detect ts project.  if true, then: 
Install tslint if does not exist on package.json

**Comment by shahata** [comment]
@yanivefraim plz make sure we do this on sunday

**Comment by yanivefraim** [comment]
fixed in https://github.com/wix/yoshi/pull/295

**Comment by shlomitc** [comment]
Can we close this?

**Comment by ronami** [comment]
Closing. Please re-open if it's still relevant.
