### ISSUE TITLE
css bundle isn't ordered correctly

### ISSUE THREAD

**Issue by sthuck** [wix/yoshi#290]
# 🐛 Bug Report

### 😯 Current Behavior
When importing css files, order isn't maintained in bundle.
meaning if I import `file1.scss` and file `file2.scss`, `file1` should be guaranteed to show up before `file2` in bundle, but in effect content of `file2.css` can appear first.

### 🤔 Expected Behavior
file1 should be guaranteed to appear before file2 in the css bundle.

This matters for old projects which don't use css modules, this behavior change may break them.  **This was the behavior in yoshi 1.x.x.**.  Yes, by semantic versioning rules yoshi 2.x can have breaking changes, but I think this should qualify as an actual bug. CSS order should be well defined.

99% this bug comes from `extract-text-plugin` for webpack4, I don't know if there is much to be done.
Maybe consider moving to `mini-css-extract-plugin`, it seems like this is the recommended direction: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/749#issuecomment-374549467

### 👣 Steps to Reproduce 
you can find a repo demo here:
https://github.com/wix-a/yoshi-css-bug

in line 6 we import some reset css stylesheet.
https://github.com/wix-a/yoshi-css-bug/blob/master/src/client.tsx#L6
in line 8 we import the component. 
But in the resulting css bundle, the component stylesheet will appear **before**  the reset stylesheet, even though the import order is reverse. 
### 🌍 Your Environment
```
  System:
    OS: OS X El Capitan 10.11.6
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 8.9.1 - ~/.nvm/versions/node/v8.9.1/bin/node
    Yarn: 1.6.0 - ~/.nvm/versions/node/v8.9.1/bin/yarn
    npm: 5.3.0 - ~/.nvm/versions/node/v8.9.1/bin/npm
  Browsers:
    Firefox: 52.0.2
    Safari: 9.1.2
  npmPackages:
    yoshi: ^2.0.0 => 2.4.0

 Yoshi config
{
  "cssModules": false,
  "entry": {
    "demo": [
      "./client.tsx"
    ]
  },
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM"
  },
  "hmr": "auto"
}
```

**Comment by yury-n** [comment]
this happened to be a pretty big show stopper for us.
we try to avoid specificity in our css selectors as much as possible and heavily rely on the order of imports when we need to override some generic component's styles with styles for specific use case.
e.g.:
```
import Dropdown from '@shared/Dropdown'; // that imports Dropdown.scss
import s from './StyledDropdown.scss';
...
<Dropdown menuClassName={s['special-menu']} />
```

for now we'll have to downgrade yoshi so wanted to share this use case and upvote the switch to "mini-css-extract-plugin".

**Comment by ranyitz** [comment]
@yury-n @sthuck We are working on the next version of yoshi `v3.0.0`.

The first thing we've changed is the `extract-text-plugin` -> `mini-css-extract-plugin`: https://github.com/wix/yoshi/blob/v3.0.0-alpha.10/CHANGELOG.md#300-alpha0-may-14-2018

You can go ahead and check it out.

**Comment by ranyitz** [comment]
[Version 3](https://github.com/wix/yoshi/blob/master/CHANGELOG.md#300-jul-4-2018) is out. closing.
