### ISSUE TITLE
run stylelint if stylelint configuration exists in project

### ISSUE THREAD

**Issue by shahata** [wix/yoshi#3]
Currently we run stylelint only if `--client` flag is passed and we run it with some builtin config file. this is bad, we should remove this flag (no backward compatibility needed since no one currently uses it). instead, we should simply check if stylelint config exists in project, and run only if it does. also not sure we really need gulp plugin we currently use.

According to stylelint docs, they use [cosmicconfig](https://github.com/davidtheclark/cosmiconfig) so best way to know if config exists is simply to run `cosmicconfig('stylelint')`.

Regarding generated code, we should generate config section in `package.json` for client/fullstack projects. Something along the lines of:

```js
{
  "stylelint": {
    "extends": "stylelint-config-standard",
  }
}
```

**Comment by ronami** [comment]
Done https://github.com/wix/yoshi/pull/14.
