### ISSUE TITLE
Infinite refresh when multiple browser tabs are open and hmr is disabled

### ISSUE THREAD

**Issue by roymiloh** [wix/yoshi#303]
# 🐛 Bug Report

### 😯 Current Behavior

When I start my app and open it multiple times (via different iframes/tabs/browsers/...) it's getting refreshed infinitely.

### 🤔 Expected Behavior

To calm down:) it looks like the hmr plugin is injected to my bundle although I disabled it.

### 👣 Steps to Reproduce 

Note: I chose TypeScript preprocessor, haven't tried with babel - not sure it's related tho.

```sh
$ npx yoshi-create
$ jq '.yoshi.hmr = false' package.json > package.json.tmp && mv -f package.json.tmp package.json
$ npm start
```

Then on different terminal session:

```sh
$ chrome-cli open http://localhost:3000
$ chrome-cli open http://localhost:3000
```

**Comment by ranyitz** [comment]
Starting from yoshi@2.9.0 you can configure live reload (which was enabled by default)

https://github.com/wix/yoshi#yoshilivereload

With the following configuration you won't have any `hmr`/`live-reload` code in your bundle:

```json
{
"yoshi": {
	"hmr": false,
	"liveReload": false
	}
}
```

Closing
