### ISSUE TITLE
Ability to run yoshi test and yoshi start at the same time

### ISSUE THREAD

**Issue by iaroslavshvets** [wix/yoshi#304]
# 🙋 Feature Request

### 😯 Current Behavior

Currently we got `Error: listen EADDRINUSE 127.0.0.1:3200` while starting CDN. For example if we ran yoshi start & have prepush/precommit git hook, which runs tests

### 🤔 Expected Behavior

No error.

### 💁 Possible Solution 

1) Detect that yoshi's CDN is already running and not start another instance.
2) Setup CDN on a different empty port.

**Comment by ranyitz** [comment]
As yoshi controls the "CDN" server (which runs on `127.0.0.1:3200`), we can check if the port is already caught by another "CDN" and instead of exit with an error, just continue gracefully.

PRs welcome!
