### ISSUE TITLE
Stylable css is missing with Yoshi 2

### ISSUE THREAD

**Issue by mariafeldman** [wix/yoshi#309]
# 🐛 Bug Report

### 😯 Current Behavior

Stylable css which WSR use is missing since we migrate to Yoshi 2 with `"separateCss": true`

Here is the screenshot with Badge from WSR, which implemented with stylable

![2018-05-28_1601](https://user-images.githubusercontent.com/2092879/40653960-78b0b084-6345-11e8-9b4f-edc068b134b1.png)

#### Example  
https://www.wix.com/dashboard/d2342015-2a5f-4241-9f65-b88f2f2ec365/coupons/?referralInfo=sidebar&debug

with coupons-client.1.98.0 with experiment specs.wos.CouponsPlatform

...

### 🤔 Expected Behavior

With yoshi 1 the same page looks like this 
![2018-05-29_0944](https://user-images.githubusercontent.com/2092879/40653882-34638276-6345-11e8-8b03-9989025f86fb.png)

#### Example  
https://www.wix.com/dashboard/d2342015-2a5f-4241-9f65-b88f2f2ec365/coupons/?referralInfo=sidebar&debug

with coupons-client.1.97.0 with experiment specs.wos.CouponsPlatform
...

### 🔦 Context 

...

### 💁 Possible Solution 

...

### 👣 Steps to Reproduce 

1. Create a basic react project
2. Use `yoshi2`
3. Add `wix-style-react` to dependencies
4. Add `"separateCss": true` to package json
5. Add a Badge component to your base App component

### 💻 Code Sample
```
import Badge from 'wix-style-react/Badge';

<Badge skin="danger">
         I'm a badge
</Badge>}
```
...

### 🌍 Your Environment

```
  System:
    OS: macOS Sierra 10.12.5
    CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 66.0.3359.181
    Firefox: 58.0.2
    Safari: 10.1.1
  npmPackages:
    yoshi: ^2.5.0 => 2.6.1 

 Yoshi config
{
  "entry": {
    "couponsBsmModule": "./businessManager/couponsBsmModule.entry.ts",
    "local": "./local.entry.tsx",
    "local.modal": "./local.modal.entry.tsx",
    "local.promoteModal": "./local.promoteModal.entry.tsx",
    "registerCouponModalComponent": "./businessManager/registerCouponModalComponent.entry.ts",
    "registerMainComponent": "./businessManager/registerMainComponent.entry.ts",
    "registerPromotionModalComponent": "./businessManager/registerPromotionModalComponent.entry.ts"
  },
  "servers": {
    "cdn": {
      "port": 3200,
      "dir": "dist/statics",
      "ssl": false
    }
  },
  "separateCss": true,
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM",
    "lodash": "_",
    "axios": "axios",
    "business-manager-api": "BusinessManagerAPI"
  },
  "externalUnprocessedModules": [
    "currencyformatter.js"
  ]
}
```

**Comment by ranyitz** [comment]
@mariafeldman Thanks for opening an issue!

When configured to `separateCss: true` did you've added the `[entryName].stylable.bundle.css` file to the `.vm`?

**Comment by mastertheblaster** [comment]
Not sure it's a good suggestion, cause now `[entryName].stylable.bundle.css` is created only for entries having stylable components. I cannot guess which entry has stylable components and which not. Need to think of smth else like (webpack concat plugin).

**Comment by ranyitz** [comment]
@mariafeldman @mastertheblaster I agree.

@barak007 @shlomitc can we just put all stylable content in the already created `[entryName].bundle.css`

**Comment by mastertheblaster** [comment]
We must also think if stylable should be appended or prepended.
Cause i have already seen on yoshi issue where imports where concatinated in wrong sequence and thus the CSS got corrupted.

**Comment by shlomitc** [comment]
@ranyitz - should the concatenation be done in `yoshi` or inside `stylable`?

**Comment by ranyitz** [comment]
@shlomitc I don't know, i'll accept a PR if a change is needed in the webpack configuration, but the solution should be a general solution for a component library that uses stylable (with consumers that use anything else...)

**Comment by itaibenda** [comment]
We also need to take source maps into account... Not sure if they are even created for stylable files.
My intuition tells me that it will be safer to append the stylable content to the existing CSS. @barak007 WDYT?

**Comment by ranyitz** [comment]
As a quick hack, stylable is being bundled to the javascript in all cases (ignoring `separateCss: true`) #329 

This is not a good solution in general, for people that would like to see styles on the page before the javascript is loaded. I'll close this until we'll have a better solution from the stylable side.
