### ISSUE TITLE
HMR doesn't work with multiple bundles on the same page

### ISSUE THREAD

**Issue by vybu** [wix/yoshi#323]
# 🐛 Bug Report

### 😯 Current Behavior

when you have multiple entries, hot reload works only for first entry.

### 🤔 Expected Behavior

should work for all entries.

### 💁 Possible Solution 

https://github.com/gaearon/react-hot-loader/issues/141

### 💻 Code Sample

yoshi.config.js

```js
{
  entry: {
   'entry-a': '...', // work for this one
   'entry-b': '...' // doesn't work for this one
}
```

**Comment by ranyitz** [comment]
@vybu Thanks for submitting this issue!

This seems to be related to #303.

**Comment by dotansimha** [comment]
My findings so far:
- `webpack-hot-client` only triggered for the first entry point.
- We can use the following code to make sure all entry points has a valid HMR configured:
```ks
        const normalizedEntries = normalizeEntries(webpackConfig.entry);
        webpackConfig.entry = normalizedEntries;

        const compiler = webpack(webpackConfig);

        // If both hmr and reload are false it makes this module fairly useless
        // https://github.com/webpack-contrib/webpack-hot-client#reload
        if (liveReload || hmr) {
          Object.keys(normalizedEntries).forEach(entryName => {
            const entryArr = normalizedEntries[entryName];
            entryArr.push('webpack/hot/only-dev-server');
            entryArr.push(`webpack-hot-client/client?ws://${host}:${hmrPort}`);
          });

          const hmrClient = hotClient(compiler, {
            port: Number(hmrPort),
            reload: liveReload,
            hmr: Boolean(hmr),
            autoConfigure: true,
            logLevel: 'warn',
          });
        }
```

There is an edge case I'm trying to solve now - in case of a page with 2 modules at the same time, and both has HMR, the real time changed only appears for the 2nd module. the first module get the update over the network with the correct code, but it's does not re-render the view.

**Comment by ranyitz** [comment]
@dotansimha comment on #444 

> At the moment, this PR fixes the issue with multiple entry points and HMR, but it's still not possible to load multiple bundles inside the same index file.

Which means this issue is solved for multiple entry points.
Changing the header to this one.

@maxaon Can you share your case?

**Comment by maxaon** [comment]
@ranyitz We have html file that contain 2 bundles: critical which contain some initial logging (like aplication started to load and sentry loader) and main bundle with our code. If i remove critical bundle and leave main and then change code my hot accept callback will work and application will be updated. If i put critical bundle only updates for it will be called. 

Project https://github.com/wix-private/video-maker/tree/master/video-maker-modal

Yoshi version is 3.14.1
