### ISSUE TITLE
Storybook : Allow running storybook in DEV mode

### ISSUE THREAD

**Issue by hepiyellow** [wix/yoshi#326]
# 🙋 Feature Request

### 😯 Current Behavior

When running storybook (using storybook's `start-storybook` script) using `yoshi/config/webpack.config.storybook`, then the code is bundled into one file. It is difficult to debug this way.

### 🤔 Expected Behavior

It would be much easier debugging, if Webpack would pack all separate files, and source-maps.
Would be also nice to have:
- [ ]  react, and react-dom in their non-minified versions when running storybook in DEV mode.
- [ ] class names not hashed, but with full name (dev mode)

**Comment by ranyitz** [comment]
@hepiyellow can you elaborate?
