### ISSUE TITLE
HMR fails when using ssl CDN server

### ISSUE THREAD

**Issue by muteor** [wix/yoshi#327]
It would be better if we did not use protocol-less urls for the server url here:

https://github.com/wix/yoshi/blob/5b1e0690d955936a2be53352bde6f4ccdbfabe28/yoshi/config/project.js#L39

Using protocol-less fails in the case of having ssl set to true and loading `http://localhost:3000` because the server is running on `https://localhost:3000` and protocol-less requests http://.

**Comment by ronami** [comment]
@muteor thanks, good catch. Can you put a PR to fix it? If not, I will push a fix later today.
