### ISSUE TITLE
Upon scss changes: 'Uncaught TypeError: Super expression must either be null or a function, not undefined'

### ISSUE THREAD

**Issue by tprupsys** [wix/yoshi#333]
This happens quite randomly on https://github.com/wix-private/members-area
An example case I ran into: I edited https://github.com/wix-private/members-area/blob/master/members-area-app/src/app/components/about/about-mobile.scss scss (simply removed a few lines from css class), that is imported to https://github.com/wix-private/members-area/blob/master/members-area-app/src/app/components/about/about-mobile-view.js like this `import styles from './about-mobile.scss';`

Then the error pops out in console:
```
app.bundle.js:40498 Uncaught TypeError: Super expression must either be null or a function, not undefined
    at _inherits (app.bundle.js:40498)
    at app.bundle.js:40511
    at Object.exports.__esModule (app.bundle.js:40531)
    at __webpack_require__ (app.bundle.js:662)
    at fn (app.bundle.js:88)
    at Object.<anonymous> (app.bundle.js:7639)
    at __webpack_require__ (app.bundle.js:662)
    at fn (app.bundle.js:88)
    at Object.defineProperty.value (app.bundle.js:76971)
    at __webpack_require__ (app.bundle.js:662)
```

I have been experiencing this on random basis for the past month. I need to close process and rerun `yarn start` so it works again.

This is the failed function:
```
function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }
```

**Comment by ronami** [comment]
@tprupsys Hey, any consistent way to reproduce the error?

**Comment by ronami** [comment]
Closing. Doesn't seem to be related to Yoshi and we took debugging it to slack.
