### ISSUE TITLE
Ability to include raw css files

### ISSUE THREAD

**Issue by donatas** [wix/yoshi#34]
I have a project, which uses css modules. It has a dependency on "component" module, which internally also uses css modules, but provides transpiled and pre-built js + css. The outcome is
component.css that contains classnames, matching component.js (css modules applied).
 
Importing component.js and component.css in my main project causes yoshi to apply css modules again for component.css, resulting in a mismatch with class names, used in component.js. 

`
:global {
@import "component/component.css"
}
` 

doesn't work, it still applies css modules for the component.css.

What the end result could be - ability to import "raw" css files that would be included in the bundle as is - maybe a different loader for webpack would do the trick.

**Comment by tqmukas** [comment]
Duplicates (#41)
