### ISSUE TITLE
Support Tree Shaking in Typescript Projects

### ISSUE THREAD

**Issue by yairhaimo** [wix/yoshi#343]
# 🙋 Feature Request

### 😯 Current Behavior

Tree shaking is not support for user code.

### 🤔 Expected Behavior

Support tree shaking for user code for Typescript projects.
```js
export function one() {...}
export function two() {...}
```
User code:
```js
import { one } from './utils';
```
Only `one` will be in the bundle.

### 💁 Possible Solution 

Change typescript module to `es2015` in the webpack loader.

**Comment by ranyitz** [comment]
Closed on #356
