### ISSUE TITLE
Support Dynamic Imports for Typescript Projects

### ISSUE THREAD

**Issue by yairhaimo** [wix/yoshi#344]
# 🙋 Feature Request

### 😯 Current Behavior

Can't lazy load code at the moment in Typescript projects.

### 🤔 Expected Behavior

This should be supported:
```js
import('./code').then(code => ...)
```

### 💁 Possible Solution 

Change module to `esnext` in webpack's typescript loader.

**Comment by ranyitz** [comment]
closed on #356
