### ISSUE TITLE
yoshi test --protractor. pass different protractor.conf.js file

### ISSUE THREAD

**Issue by zeevgg** [wix/yoshi#353]
# 🙋 Feature Request

### 😯 Current Behavior

when running `yoshi test --protractor`
it takes the  protractor.conf.js file.

...

### 🤔 Expected Behavior
allow passing which protractor.conf to use
`yoshi test --protractor --conf=another_protractor.conf.js`

...

### 💁 Possible Solution 

...

### 🔦 Context 

...

**Comment by ranyitz** [comment]
@zeevgg Can you supply some context, why would you like to use a different file?

**Comment by zeevgg** [comment]
I am running e2e on chrome and IE.
I want to run some tests on chrome and others on IE.
I have a different setup for some cases.
I want ie to go to browser stack and chrome to go run locally.
now I am doing it like that:


"test": "npm run test:localChrome && npm run test:browserstackIE",
"test:browserstackIE": "cp -f protractor_browserstack_ie.conf.js protractor.conf.js && yoshi test --protractor",
"test:localChrome": "cp -f protractor_local_chrome.conf.js protractor.conf.js && yoshi test --protractor",

**Comment by ronami** [comment]
Hey @zeevgg,

It's a bit hacky but because you have a very specific use-case, I think it might help with solving this issue:

You can run protractor twice:
```json
{
  "scripts": {
    "test-chrome": "BROWSER=CHROME yoshi test --protractor",
    "test-ie": "BROWSER=IE yoshi test --protractor"
  }
}
```

In your `protractor.conf.js`:
```js
if (process.env.BROWSER === 'CHROME') {
  module.exports = {
    specs: ['test/**/*.chrome.spec.js'],
    // ...
  };
} else if (process.env.BROWSER === 'IE') {
  module.exports = {
    specs: ['test/**/*.ie.spec.js'],
    // ...
  };
}
```

If we see that more users have a similar use-case we can think of developing a better solution on Yoshi's side.

Please let me know if it makes sense :)

**Comment by zeevgg** [comment]
hi, yes it is a nice and clean solution, very similar to what I do now with the copy file.
still, I think that we should have this feature in Yoshi.

**Comment by ronami** [comment]
Cool, closing for now.

Let's consider a better solutio nif we see more users with this use-case.

**Comment by zeevgg** [comment]
I still think that we should add it...
