### ISSUE TITLE
upgrade webpack to latest version

### ISSUE THREAD

**Issue by ipanasenko** [wix/yoshi#357]
Hey, guys.

Would be awesome to have latest webpack (3.7) in yoshi. It provides updated commons chunk plugin, which works with async chunks (children and deepChildren options): https://webpack.js.org/plugins/commons-chunk-plugin/#move-common-modules-into-the-parent-chunk

**Comment by roymiloh** [comment]
Closed by https://github.com/wix/yoshi/pull/367.
