### ISSUE TITLE
CheckDeps task fails if computer isn't connected to VPN

### ISSUE THREAD

**Issue by roymiloh** [wix/yoshi#365]
I cannot `yoshi build` when my computer is not connected to VPN. The error comes from [depkeeper@lib/registry.js#L39](https://github.com/wix/depkeeper/blob/master/lib/registry.js#L39).

The exceptions is:

```
`TypeError: Cannot convert undefined or null to object`
```

... `result` is still undefined, because the request failed. Maybe related to https://github.com/wix/depkeeper/issues/1, although I'd label it as a bug in depkeeper.

Anyway, I'd suggest to silently swallow error in this task if not in CI & this specific step (request to registry) fails.

@tqmukas

**Comment by tqmukas** [comment]
Fixed in https://github.com/wix/depkeeper/commit/cceccd5bbff68d2a1d9fa4ed377c939583fee53c
