### ISSUE TITLE
A proper way to include css from 3rd party libraries

### ISSUE THREAD

**Issue by tqmukas** [wix/yoshi#41]
There is no example how to include and use css from 3rd party libraries. When imported, it's being processed by style loader, css loader and css modules. This way its selectors are mangled and don't work.

Wrapping it to `:global` does not work:
```css
:global {
  @import './node_modules/awesome-loader.css';
}
```

**Comment by ronami** [comment]
Closing. Currently, the correct way is to import a file with a `.global.scss` suffix.
