### ISSUE TITLE
Storybook missing css modules

### ISSUE THREAD

**Issue by muteor** [wix/yoshi#420]
# 🐛 Bug Report

### 😯 Current Behavior

![image](https://user-images.githubusercontent.com/305164/42314402-d75abbb6-803c-11e8-888c-50926caf08b2.png)

Seems that css modules are broken, no styles included and empty class attributes in the DOM.

### 🤔 Expected Behavior

Css to work :)

### 👣 Steps to Reproduce

https://github.com/wix-private/da-frontend/tree/master/projects/da-shared-react

checkout da-frontend
```
cd projects/da-shared-react
npm i yoshi@3 yoshi-style-dependencies -D
npm i
npm run story
``` 

### 💻 Code Sample

Webpack config:

```
const wixStorybookConfig = require('yoshi/config/webpack.config.storybook');

module.exports = (config, env, defaultConfig) => {
  return wixStorybookConfig(defaultConfig);
};
```

### 🌍 Your Environment

```

  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-6660U CPU @ 2.40GHz
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 61.0
    Safari: 11.1.1
  npmPackages:
    yoshi: ^2.8.0 => 3.0.0

 Yoshi config
{
  "entry": {
    "app": "index.ts"
  },
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM",
    "immutable": "immuteable",
    "draft-js": {
      "root": "Draft",
      "commonjs2": "@wix/draft-js",
      "commonjs": "@wix/draft-js",
      "amd": "@wix/draft-js",
      "umd": "@wix/draft-js"
    },
    "@wix/draft-js": {
      "root": "Draft",
      "commonjs2": "@wix/draft-js",
      "commonjs": "@wix/draft-js",
      "amd": "@wix/draft-js",
      "umd": "@wix/draft-js"
    }
  },
  "features": {
    "addStoriesToBaseGlob": true
  }
}
```

**Comment by hepiyellow** [comment]
I am experiencing a similar issue:

I am trying to upgrade `wix-style-react` to work with Yoshi 3, and the storybook is failing to load `scss` in `wix-storybook-utils`.

When running `npx start-storybook`,
if I stop chrome debugger, and look at the render of `StoryPage` (from `wix-storybook-utils`), i see that the `_styles` has an error "ReferenceError: _styles is not defined".

`var _styles = __webpack_require__(/*! ./styles.scss */ "../node_modules/wix-storybook-utils/dist/src/StoryPage/styles.scss");`

**Comment by hepiyellow** [comment]
@ranyitz Yes. WSR was already running with Webpack 4 when we upgraded from Yoshi 1 to Yoshi 2. (We use storybook `4.x.x-aplha-x`)

**Comment by muteor** [comment]
Fixed it with:

`loaders/sass.js`
```change: 
- Number(tpaStyle), 
+ Number(tpaStyle || 0),
```

`yoshi/config/webpack.config.storybook.js`
Change the parameters of the `...require('../src/loaders/sass')` to object like:
```
{
  separateCss: false,
  cssModules,
  tpaStyle: false,
  projectName,
  hmr: true, // not sure about this???
  min: false
    }
```

**Comment by ranyitz** [comment]
Thanks @muteor, fixed on version __3.1.3__
