### ISSUE TITLE
tslint-config-yoshi: new rules

### ISSUE THREAD

**Issue by eranshabi** [wix/yoshi#422]
I think [wix-tslint-custom-rules](https://github.com/wix-incubator/wix-tslint-custom-rules) has 2 rules that may be useful in `tslint-config-yoshi`.

no-wallaby-file-only: protects you from committing `//file.only` (new wallaby feature). Has a fixer too.
no-async-without-await: protects you from async function that implicitly return undefined. Mostly it finds functions that are `async` with no reason.

We already use them in our ecom projects and they are useful.
thanks.

**Comment by yairhaimo** [comment]
Our rules of thumb when adding lint rules are:
1. Is it autofixable?
2. If not, does it detect a bug in the code?

If the answers to those questions are "no" we usually do not add the rule.

We feel that `no-async-without-await` does not answer these questions and we're not sure when you would want to use it.

Additionally, if you have a function that may throw an error, and should return a promise (with the rejected error), you can add `async` without `await`. Forcing the user not to use `async` here will  result in code that is less readable:

```js
async function foo() {
   mayThrowError();
}
```

Regarding `no-wallaby-file-only` - sounds good. Send a PR with that rule and we'll happily merge it.

Thanks!
