### ISSUE TITLE
Allow using Externals Enforcer Plugin

### ISSUE THREAD

**Issue by nayish** [wix/yoshi#430]
# 🙋 Feature Request

### 😯 Current Behavior

Whenever there is a library configured as en external (e.g. `lodash`)  and we import a specific path of that external (`e.g.` import * as reduce from 'lodash/reduce'`) it gets bundled in our bundle, this is undesirable (e.g adds 90k)

### 🤔 Expected Behavior

Allow breaking build when importing wrongly, in order to not let thing "leak" into the bundle.

### 💁 Possible Solution 

Allow using ExternalEnforcer plugin https://github.com/wix-incubator/externals-enforcer, which breaks the build when externals are wrongly imported
...

### 🔦 Context 

We found that our bundle had parts of external dependencies although they were set as external. 
example: https://image.ibb.co/ifVvU8/exte.png

**Comment by ronami** [comment]
Hey @nayish, thanks for diving in.

I think that it's a good idea to verify that dependencies you configured as externals don't get into the bundle. 

However, I think that doing it with a Webpack plugin has one main problem: Normally, your code is not the only code that requires external modules. In a situation where a 3rd party (non-wix) module requires an external module, `ExternalsEnforcerPlugin` will fail your build and you won't be able to fix it (without replacing that 3rd party).

If we ignore imports to external modules from inside `node_modules`, those external modules will be able to  get into the bundle without any notice.

@roymiloh created a solution (requires opt-in in Yoshi) specifically for lodash (which I think is the biggest part of the problem): https://github.com/wix/externalize-relative-module-loader. It's a Webpack loader that replaces every every occurrence of `require('lodash/foo')` with `require('lodash').foo`. That solution will work even if you have 3rd party modules that require `lodash/...`.

Are there any other dependencies (other than lodash) where you need to require internal files?

**Comment by nayish** [comment]
Hey @ronami, 

If I understand correctly, @roymiloh solution only solves the problem for libraries with straightforward imports. i.e. lodash/foo ->lodash.foo.
For other libraries this solution may not work (there doesnt have to be correlation between fileName and function name).
My webpack plugin has the plus of solving the issue for all libraries (and not only ones built like lodash).

You are right about the problem where you may not have access to the "problematic" code (since it is being imported by a third-party library) but as I wrote in the Readme there is a workaround - you can add the problematic third-party import  to your externals explicitly.

**So if for example:**
A: entry.ts
```
require('B');
```

A: package.json
```
externals: {
  'C': 'C'
}
```

B(third-party): entry.ts
```
require('C/foo')
```

Adding to the externals object in A's package.json: `'C/foo': 'C.Utils.foo'` (or wherever the  code sits in C's bundle.

In our usecase, we want to catch also some of our node_modules  from leaking into the bundle (for example our wixstores-client-core) project.

In general if the functions I am using **or a third party library is using** are marked as external in my project it is a waste to bundle them along with my project since they are already being downloaded separately in the external.

**Comment by felixmosh** [comment]
@ronami I'm not agree with you, If there is a third party that uses partials of my external libs it just increases the bundle size without me even knowing it. 
I think that @nayish plugin at least notifies / alerts the devs regarding sneaking into the bundle.

And you always can put those "partials" into your webpack externals, like @nayish explained.

**Comment by felixmosh** [comment]
First of all, it is an easy task to add a configuration to warn instead of break the build.

I recently investigated several bundles and noticed that some of our common libs such as `urijs` that are importing specific paths from it, and it is an external on the production artifact (the one that bundles the entire artifact), and I think that if in the middle of the build we got a notification regarding such cases it will prevent future issues.
