### ISSUE TITLE
Custom webpack configuration: deep extension for plugin configuration

### ISSUE THREAD

**Issue by HanWax** [wix/yoshi#433]
# 🙋 Feature Request

### 😯 Current Behavior

When customising webpack configuration, you can extend default settings, but you can't deep extend properties such as plugins.

### 🤔 Expected Behavior
Be able to deep extend plugin configuration so that I can configure settings such as UglifyJSPlugin options, without removing the configuration for other plugins. 

### 💁 Possible Solution 

[lookup-config.js](https://github.com/wix/yoshi/blob/9ffd8c083e62cf7a07df15355c4c3d4f353e0a7e/packages/yoshi/config/lookup-config.js)
```javascript
module.exports = () => {
  const projectConfig = get(explorer.load(), 'config', {});

  if (projectConfig.extends) {
    const extendsConfig = require(projectConfig.extends);
    const defaultConfig = extendsConfig.defaultConfig;

    if (get(defaultConfig, 'extendsPlugins')) {
      const extensionPlugins = get(defaultConfig, 'plugins');
      const projectPlugins = get(projectConfig, 'plugins');
      set(
        defaultConfig,
        'plugins',
        intersection(extensionPlugins, projectPlugins),
      );
    }

    return {
      ...defaultConfig,
      ...projectConfig,
    };
  }

  return projectConfig;
};
```
...

### 🔦 Context 

I would like to customise the UglifyJSPlugin options - specifically the 'keep_classnames' flag
...

**Comment by ronami** [comment]
Hi @HanWax, thanks for diving in. Why/when do you need to configure Uglify with `keep_classnames`?

**Comment by HanWax** [comment]
Hi @ronami

This is because of the way that we instantiate our classes in our SDK. 
Instead of instantiating them from the constructor, when we import them we wrap the constructor function with monitoring context for Sentry and then add this wrapped constructor to a map. The map is keyed by the classname. When we instantiate a class in our project - we then get the constructor from the map of the wrapped classes. 

Instead of using the keep_classnames flag, we could also set the mangle property of uglify options to specify only the classes which are these monitored component classes.

**Comment by ronami** [comment]
Is it possible to explicitly choose the monitoring id when you wrap a class instead of taking its name? That way your code will be resilient to being minified.

Something like this:

```js
sentryWrap(someConstructor, { name: 'someConstructor' });
```

That way we won't have to configure Uglify explicitly. If we turn on `keep_classnames` or `keep_fnames ` it may increase the size of the bundle of every project.
