### ISSUE TITLE
No error message when importing non existing `scss` file

### ISSUE THREAD

**Issue by mastertheblaster** [wix/yoshi#44]
If inside our `scss` file we import another one, and we accidentally provide wrong path, the node process takes 100% and no error is being reported. So it takes some time to find a root cause.

**Comment by tqmukas** [comment]
@mastertheblaster can you please provide more details?
It works for me just fine.
![screen shot 2017-03-15 at 09 46 06](https://cloud.githubusercontent.com/assets/6513105/23938292/664ff8e6-0964-11e7-9367-33008f5e0995.png)

**Comment by mastertheblaster** [comment]
Strange, it's reproducable for me.

I use `yarn start`. Once started i open the `scss` file and corrupt the path by adding extra `..` dots to the path, and there is no errors inside console, everything is green but node takes 100% cpu.
