### ISSUE TITLE
support both puppeteer and protractor at the same time

### ISSUE THREAD

**Issue by eranshabi** [wix/yoshi#449]
# 🙋 Feature Request

### 😯 Current Behavior
right now yoshi decides if it should run puppeteer or protractor based on some logic and then run only one of them.

### 🤔 Expected Behavior
run both puppeteer and protractor.

### 💁 Possible Solution 
don't use the same test glob for both. (for example what about `file.e2e.puppeteer.ts`)

### 🔦 Context 
This is a blocker for me to test a feature currently, as I have a test that works only in puppeteer but I can't run it because the project already has lot of protractor tests.

Also now it's not possible to migrate to protractor gradually.

**Comment by ranyitz** [comment]
@eranshabi thanks for opening this issue.

I agree that currently there is no easy migration path from protractor to puppeteer.

Introducting another extension and create another run is a possible solution but it is complex (to understand and to maintain). When creating such we'll need to support it for good.

@ronami @yairhaimo any ideas?

**Comment by eranshabi** [comment]
Here is a suggestion:
Running puppeteer tests on your own (without yoshi) is easy. I already have it working but can't use it because I can't serve the bundles, because serving them is a side effect of running `yoshi test:e2e` (as far as I understand from reading your code).
If you would allow users to serve the bundle using a yoshi command, no more changes would be needed from your side and we could migrate.

**Comment by eranshabi** [comment]
Here is a temporary hack for anyone needing this:
You can serve the statics yourself after `yoshi build`:
`app.use(express.static('./dist/statics'));`
and then `app.listen` to the port yoshi normally uses for statics.

(it's a bit more complex as you need to serve some other paths too depending on what files you use, for example translations)

**Comment by yairhaimo** [comment]
Thanks for the issue, as @ranyitz said, we don't yet have a clear migration path from protractor to puppeteer. We'll be sure to add it to our upcoming tasks and we'll update when we have something worth updating.

**Comment by ranyitz** [comment]
There is still no gradual migration path between protractor to puppeteer.

**Comment by netanelgilad** [comment]
Just dropping this idea here so I won't forget, didn't really think it through.
We can run protractor tests with puppeteer as the browser under test, see [this StackOverflow answer](https://stackoverflow.com/questions/51536244/how-to-use-puppeteer-in-an-angular-application/52765728#52765728). This way, users will be able to start writing new tests using `puppeteer` api instead of `webdriver`, and slowly migrate existing `webdriver` based tests to `puppeteer`. When all tests have been migrated, it should be simple to drop `protractor`.

**Comment by netanelgilad** [comment]
I think this issue is still relevant, reopening
