### ISSUE TITLE
when upgrading to yoshi 3.x, the project build fails due to css errors

### ISSUE THREAD

**Issue by ChenRoth** [wix/yoshi#465]
# 🐛 Bug Report

### 😯 Current Behavior

when running `npm start`, everything runs smoothly.
when running `npm build`, i'm getting this error:
```
ERROR in ./_local.global.scss
Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../node_modules/sass-loader/lib/loader.js):
Invalid CSS after ".wix-button-rgba": expected selector, was "(0,0,0,0)"
```

### 🤔 Expected Behavior

build should go through the css stage with no problems.
...

### 🔦 Context 

I want to upgrade this project to yoshi 3.x

### 💁 Possible Solution 

...

### 👣 Steps to Reproduce 

* clone and install the `ecom` repo `git@github.com:wix-private/ecom.git`
* checkout branch `dashboard-catalog-yoshi-3`, which includes a single commit that handles migrating to yoshi 3.x
(this branch won't be modified)
* try `npm run build`

### 🌍 Your Environment

```
 System:
    OS: macOS High Sierra 10.13.5
    CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 8.9.1 - ~/.nvm/versions/node/v8.9.1/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v8.9.1/bin/npm
    Watchman: 4.9.1 - /usr/local/bin/watchman
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 61.0
    Safari: 11.1.1
  npmPackages:
    yoshi: ^3.2.0 => 3.2.1

 Yoshi config
{
  "hmr": false,
  "entry": {
    "app": "./app.ts",
    "externals": "./externals.ts",
    "mocks": "../test/mock/mocks.ts"
  },
  "specs": {
    "browser": "{src/catalog/products/product/options/EditProductOption/EditProductOption.tsx,src/app.ts,test/mock/appMock.ts,src/**/*.spec.+(js|ts)}"
  },
  "externals": {
    "angular": "angular",
    "jquery": "jQuery",
    "react": "React",
    "react-dom": "ReactDOM",
    "react-dom/test-utils": "React.addons.TestUtils",
    "Wix": "Wix",
    "lodash": "_",
    "urijs": "URI"
  }
}
```

paste below your `yoshi` config block from your `package.json`. -->
```
"yoshi": {
		"hmr": false,
		"entry": {
			"app": "./app.ts",
			"externals": "./externals.ts",
			"mocks": "../test/mock/mocks.ts"
		},
		"specs": {
			"browser": "{src/catalog/products/product/options/EditProductOption/EditProductOption.tsx,src/app.ts,test/mock/appMock.ts,src/**/*.spec.+(js|ts)}"
		},
		"externals": {
			"angular": "angular",
			"jquery": "jQuery",
			"react": "React",
			"react-dom": "ReactDOM",
			"react-dom/test-utils": "React.addons.TestUtils",
			"Wix": "Wix",
			"lodash": "_",
			"urijs": "URI"
		}
	}
```

**Comment by ChenRoth** [comment]
a short time ago, @alex5il addressed a similar issue with @ronami and it seems the problem was the node-sass version.
@ronami , please advise.

**Comment by ronami** [comment]
Hey @ChenRoth, not sure if I remember about a similar issue, can you add some info on it?

**Comment by yairhaimo** [comment]
Yeah, it seems that node-sass 4.9.2 doesnt work with your project.
They dont have a changelog for that version so im unsure what broke.

We changed yoshi's dependency for `node-sass` from `"~4.5.3"` to `"^4.5.3"` so you received an update to the package in yoshi 3. You can install node-sass@4.8.3 and it should work.

**Comment by ronami** [comment]
Hey @ChenRoth, did it solve the problem?

**Comment by ChenRoth** [comment]
hi, haven't tried it yet (we do this kind of tech debt work once in a while)
closing the issue and will re-open if needed
thanks
