### ISSUE TITLE
Add jest-watch-typeahead plugin to jest

### ISSUE THREAD

**Issue by yakirn** [wix/yoshi#467]
# 🙋 Feature Request

### 😯 Current Behavior

In jest watch mode, when filtering by test/file name there is no autocomplete.

### 🤔 Expected Behavior

Jest should suggest autocomplete by test/file name.

### 💁 Possible Solution 

Since jest 21 a plugin is required to enable typeahead (autocomplete).
Add [this plugin](https://github.com/jest-community/jest-watch-typeahead) to jest's configuration in yoshi.

### 🔦 Context 

This looks like a fairly easy change, and a big win for DX. I could make a PR for this, but I'm too busy this week. Opening this issue incase someone else would like to step in before I can.

**Comment by ronami** [comment]
Currently, projects can opt-in to using this plugin by configuring Jest directly. I think that this is something we can add to https://github.com/wix/yoshi/tree/master/packages/jest-yoshi-preset once it's released.
