### ISSUE TITLE
Include source-map-loader

### ISSUE THREAD

**Issue by yuriibut** [wix/yoshi#473]
# 🙋 Feature Request

### 😯 Current Behavior

- `lerna` project with 2 packages
- one of packages links to another
- both packages use `typescript` and `yoshi`
- both packages generate source-map for `.ts` files

Problem: Package "A" , which links to package "B", don't use generated source maps of project "B".

### 🤔 Expected Behavior

Package "A" , which links to package "B", includes generated source maps of project "B" 

### 💁 Possible Solution 

Include `source-map-loader` to `yoshi`
https://www.npmjs.com/package/source-map-loader

### 🔦 Context 

This problem increases development time when you're using `yoshi` with `lerna` projects... ☹️

**Comment by ranyitz** [comment]
@yuriibut Adding this loader to all projects that use `yoshi` might cause a big performance penalty in build time.

> source-map-loader will extract from any JavaScript file, including those in the node_modules directory. Be mindful in setting include and exclude rule conditions to maximize bundling performance.

We can maybe insert this under feature flag, so it will work only for people who opt in to it.

Let's continue the discussion on #104
