### ISSUE TITLE
Precommit hook runs linter on all files, not just staged files

### ISSUE THREAD

**Issue by yurynix** [wix/yoshi#485]
# 🐛 Bug Report

### 😯 Current Behavior

Precommit hook runs linter on all files, not just staged files
<img width="599" alt="screen shot 2018-08-09 at 11 34 33" src="https://user-images.githubusercontent.com/326402/43887687-39c41a94-9bc8-11e8-855f-b2c2a2b6b104.png">

### 🤔 Expected Behavior

I expected the linter to run only on staged files via `git add`

### 👣 Steps to Reproduce 

1. Have 2 files with lint errors
2. stage one of them via `git add 1.js`
3. commit it via `git commit`
4. notice the linter will complain about the second file as well, although it's not  staged.

### 🌍 Your Environment
```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
    Yarn: 1.9.4 - ~/.nvm/versions/node/v10.7.0/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.1
    Safari: 11.1.2
  npmPackages:
    yoshi: ^3.0.0 => 3.4.3 

 Yoshi config
{
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM"
  },
  "hmr": "auto"
}

```

```
  "yoshi": {
    "externals": {
      "react": "React",
      "react-dom": "ReactDOM"
    },
    "hmr": "auto"
  },
```

**Comment by ranyitz** [comment]
Can you please use the [issue template](https://github.com/wix/yoshi/issues/new?template=BUG_REPORT.md) ?

**Comment by yurynix** [comment]
Sure, I've updated the issue.

**Comment by ranyitz** [comment]
A setup of [lint-staged](https://github.com/okonet/lint-staged) in `create-yoshi-app`'s templates would be nice.

PRs welcome!
