### ISSUE TITLE
JSON imports break wallaby, but builds ok

### ISSUE THREAD

**Issue by yurynix** [wix/yoshi#487]
# 🐛 Bug Report

### 😯 Current Behavior

Wallaby breaks when `.json` file is imported:

```es6
import mocks from '../../../test/mocks.json';
```

<img width="633" alt="screen shot 2018-08-09 at 13 02 07" src="https://user-images.githubusercontent.com/326402/43892763-8d246894-9bd5-11e8-99b5-d99c2405ad0a.png">

### 🤔 Expected Behavior

I expected wallaby to keep working, especially since the normal build runs ok

### 💁 Possible Solution 

to fix, in wallaby_common.js, we need to add proper loader for babel:
<img width="650" alt="screen shot 2018-08-09 at 13 10 31" src="https://user-images.githubusercontent.com/326402/43892803-a3c9d14c-9bd5-11e8-967d-8d619ac86a7e.png">

### 👣 Steps to Reproduce 

1. Create a spec file where wallaby runs fine
2. Import some `.json` file
3. Wally will no longer run and display in it's output:
<img width="633" alt="screen shot 2018-08-09 at 13 02 07" src="https://user-images.githubusercontent.com/326402/43892763-8d246894-9bd5-11e8-99b5-d99c2405ad0a.png">

### 🌍 Your Environment
```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
    Yarn: 1.9.4 - ~/.nvm/versions/node/v10.7.0/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.1
    Safari: 11.1.2
  npmPackages:
    yoshi: ^3.0.0 => 3.4.3 

 Yoshi config
{
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM"
  },
  "hmr": "auto"
}

```

```
  "yoshi": {
    "externals": {
      "react": "React",
      "react-dom": "ReactDOM"
    },
    "hmr": "auto"
  },
```

**Comment by ranyitz** [comment]
Can you use our [issue tempalate](https://github.com/wix/yoshi/issues/new?template=BUG_REPORT.md)?

**Comment by yurynix** [comment]
Sure, I've updated the issue.

**Comment by ranyitz** [comment]
Wallaby should work fine importing `json` files. (example from a local test below)

![image](https://user-images.githubusercontent.com/11733036/43999810-8c936e9a-9e1c-11e8-984d-fdd0a2cb2e80.png)

I'm not sure why inlining the `json` object solves the problem in your project, but you can try asking [these guys](https://github.com/wallabyjs/public/issues)

**Comment by yurynix** [comment]
Interesting, it seems I have misunderstood the issue. It's not about the `json` per se:

https://github.com/yurynix/json-test/commit/0f53d62e8da52f254cb9ff078809a64fa8d9a7b4

<img width="561" alt="screen shot 2018-08-12 at 20 41 00" src="https://user-images.githubusercontent.com/326402/44004772-dde341cc-9e70-11e8-91ad-98a1d5b3b851.png">

**Comment by ranyitz** [comment]
@yurynix yes, and that's probably because it's not in these glob patterns:

https://github.com/wix/yoshi/blob/e0ffc5ac873435966f60c6fee71e10e7ab5880a7/packages/yoshi/config/wallaby-common.js#L43-L60

You can move this file to be inside of `src` directory.

We can also add `json` files inside of `test` directory, but no one requested it until now.

Is it something you think everybody uses?

**Comment by yurynix** [comment]
> Is it something you think everybody uses?

We used that in the crash course project, to share a mock of "products" between server and client tests, it lived in a path of `test/mocks.json`, in the same place as `test/test-common.js`, so IMO, it worth solving...

**Comment by yurynix** [comment]
Indeed, adding:
```json
      'test/**/*.json',
```

solves that

**Comment by ranyitz** [comment]
@yurynix awesome, PRs welcome
