### ISSUE TITLE
Add a descriptive message in cases when the node version is below 8.7

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#491]
# 🙋 Feature Request

Throw a meaningful error when node version is lower than `8.7`.

### 😯 Current Behavior

When installed on a machine with `node < 8.7` `create-yoshi-app` is failing with the following error:

![image](https://user-images.githubusercontent.com/11733036/44001116-712a302c-9e34-11e8-9db5-3b43053215ff.png)

### 🤔 Expected Behavior

Check for now version, and throw a message in case node version is below 8.7

### 🔦 Context 

Some folks still use old node versions, `create-yoshi-app` is written and tested using `node > 8.7` feature. The simplest thing would be to throw a descriptive error.

**Comment by netanelgilad** [comment]
How about using the [`engines`](https://docs.npmjs.com/files/package.json#engines) field on the `package.json`? Maybe not the most beautiful solution, but it would print a warning by `npm` or `yarn` about using a non-supported version of node.

**Comment by ranyitz** [comment]
I think that you'll still see the following:
```
unexpected token )
```

which looks unprofessional.

`engineStrict` and other stuff that I've checked aren't supported anymore.

Manually checking the node version seems to be a pretty easy solution that does the trick.
