### ISSUE TITLE
run tests with retry option

### ISSUE THREAD

**Issue by zeevgg** [wix/yoshi#509]
# 🙋 Feature Request

### 😯 Current Behavior

all tests run only once

### 🤔 Expected Behavior

if test fails, rerun it again (N times) to help with cronical flakines.
this should be configurable, and off by default.

### 💁 Possible Solution 

add confugiration for number of retries.
it would be greate if only the faild tests will be rerun

### 🔦 Context 

we had a build that runs e2e flows on IE 11 woth browser stack.
some tests are flaky without any reasonable cause

thanks

**Comment by ranyitz** [comment]
@zeevgg Yoshi only runs the test-runner e.g. `mocha`/`jest`, and not actually runs each test. So it's not aware of the inner structure of the tests themselves (which changes between test-runners)

This feature is a really nice feature that would help to a lot of people, but currently I don't think of an easy way to do it from yoshi's side.

Would love to hear some ideas regarding the implementation.

**Comment by zeevgg** [comment]
there are existing solutions like: https://www.npmjs.com/package/protractor-retry
but need to check if it could be integrated easily into our eco system
