### ISSUE TITLE
Open/Refresh browser window when application is available

### ISSUE THREAD

**Issue by yairhaimo** [wix/yoshi#515]
# 🙋 Feature Request

### 😯 Current Behavior

When `yoshi start` finishes we tell the user that the application is available at a certain port.

### 🤔 Expected Behavior

In addition to telling the user the application is available, we should also automatically open the browser to that url.
If a browser window is already open to that url we should focus on the browser and refresh the window and not open a new window.

**Comment by ranyitz** [comment]
We have an open PR for that #539, we'll close that issue when it'll be merged.

**Comment by ranyitz** [comment]
@netanelgilad Should we close this?

**Comment by netanelgilad** [comment]
Most def.
