### ISSUE TITLE
Git hooks don't work until husky is reinstalled

### ISSUE THREAD

**Issue by netanelgilad** [wix/yoshi#521]
# 🐛 Bug Report

### 😯 Current Behavior

When generating a new project git hooks don't work until husky is reinstalled.

### 🤔 Expected Behavior

Git hooks should work right after generating a new project.

### 💁 Possible Solution 

Husky cannot install the git hooks when it gets installed because there isn't a git repository initialised yet. If the generated project should be a git repository, we should also `git init` before running `npm install` (Notice the _if_, since there are other issues about creating a project inside a monorepo which do not need a git repo or husky, maybe we should also ask the user if he wants to create a git repo).

### 🌍 Your Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  Binaries:
    Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
    npm: 6.4.0 - ~/.nvm/versions/node/v10.9.0/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1.2
  npmPackages:
    yoshi: ^3.0.0 => 3.6.0

 Yoshi config
{
  "entry": {
    "test-bmm-module": "./module",
    "test-bmm-app": "./client"
  },
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM",
    "react-addons-css-transition-group": "React.addons.CSSTransitionGroup",
    "lodash": "_",
    "urijs": "URI",
    "@wix/business-manager-api": "BusinessManagerAPI",
    "react-module-container": "reactModuleContainer"
  }
}
```

**Comment by ranyitz** [comment]
Related #527

**Comment by ranyitz** [comment]
@netanelgilad Great idea.
I think it's valid to create a git repo when starting a new project.
We'll also need to update [this part](https://github.com/wix-private/fed-handbook/blob/master/ZERO_TO_PRODUCTION.md#sync-with-remote-repository)
