### ISSUE TITLE
Dont run tests on `yoshi start`

### ISSUE THREAD

**Issue by yairhaimo** [wix/yoshi#524]
# 🙋 Feature Request

### 😯 Current Behavior

`yoshi start` runs tests unless otherwise specified.

### 🤔 Expected Behavior

`yoshi start` should not run tests.

**Comment by yanivefraim** [comment]
Do we consider this a breaking change? 
What will be the new ("do run tests") flag? (`--tests` / `--run-tests`)?

**Comment by Schniz** [comment]
I guess that `--with-tests` is easier to understand: `yoshi start --with-tests` reads better. what do you think?

**Comment by ronami** [comment]
Merged in #738.
