### ISSUE TITLE
Fix Typescript Types in Generators to Easily Support Strict Mode

### ISSUE THREAD

**Issue by yairhaimo** [wix/yoshi#530]
# 🙋 Feature Request

### 😯 Current Behavior

When generating a new Typescript project and enabling `strict` mode in `tsconfig.json` there are several type errors.

### 🤔 Expected Behavior

Enabling `strict` should just work out of the box on newly generated projects.

**Comment by amitdahan** [comment]
Do you think strict mode should *work* out of the box as an opt-in or out?

**Comment by yairhaimo** [comment]
I think it should be opt in but when you decide to opt in you wouldnt need to fix any existing code in order to make it work.

**Comment by amitdahan** [comment]
@netanelgilad node-library is strict-proof

**Comment by netanelgilad** [comment]
> @netanelgilad node-library is strict-proof

Nice 😄 

I'm currently waiting on my [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28445) to update the typings for `react-i18next` so that they could work in strict mode. (relevant for frontend typescript project types).

**Comment by netanelgilad** [comment]
Once #542 gets merged, no need to wait for the PR to fix `reacti-18next` types, they are correct in version 7.
