### ISSUE TITLE
Add .editorconfig to generated projects

### ISSUE THREAD

**Issue by netanelgilad** [wix/yoshi#532]
# 🙋 Feature Request

### 😯 Current Behavior

Currently generated projects do not have `.editorconfig` and need to be created manually.

### 🤔 Expected Behavior

A new generated project should contain `.editorconfig` with sensible defaults.

### 💁 Possible Solution 

Generate `.editorconfig` :)

**Comment by ranyitz** [comment]
@netanelgilad Totally agree.
