### ISSUE TITLE
add assert/upgrade command to support upgrades for generated files

### ISSUE THREAD

**Issue by netanelgilad** [wix/yoshi#536]
# 🙋 Feature Request

### 😯 Current Behavior

Currently, once the project has been generated, the generated files will never be updated even if we add a new feature to the generators. Currently users can only upgrade the `yoshi` package to get new features in the commands themselves.

### 🤔 Expected Behavior

We can add a new command to `assert`/`upgrade` the current project to the new status of the generators. An example of this is that a new version of the generators comes out that now support lint-staged. The new command will make sure to add the `lint-staged` part to the `package.json` if it doesn't exist there.

### 💁 Possible Solution 

We should discuss this idea in more detail but here are a few points to talk about:
* We need to save the type of the project that was generated so that the new command would know what it needs to assert/upgrade in this project.
* We need to think how to handle conflicts. Since the users can change any part of the generated files, we may find that we want to assert a file/section only to find that it has been changed by the user. So we need to decide if we instruct the users to think of those files/sections as auto-generated and please don't touch (maybe by adding a comment) or we can take the safer route and always resolve conflicts with the version provided by the user.

### 🔦 Context 

The purpose of this issue is to support easier migration between version and let users enjoy new features without having to configure them manually after the first generation of the project.

**Comment by ranyitz** [comment]
@netanelgilad Currently, the generators use templates, which means we don't have a notion of features. Also, we try to create features under the interface of the following commands:

`yoshi build`
`yoshi start`
`yoshi test`
`yoshi lint`

Building the generators out of features like you suggest, will create an overhead in development, building, and reasoning for the sake of installing stuff like `lint-stage` automatically. The manual equivalent is not hard to do by developers.

I also think that the "merge" is going to be hard, in a way that is not going to justify such work.

If we want to control something (e.g. lint staged) we should put it under a facade in a way that the users could change it only under our configuration. (So we'll be able to upgrade their code without the need to face merging)

**Comment by netanelgilad** [comment]
basing the generators on features is an implementation detail, and we don't have to go that way if we think that that is not the best way. We can still implement it in a copy-paste way or whatever. 
We should discuss the way to implement it, and maybe we'll find the the golden way or maybe not, but IMO the usefulness of this feature is definitely worth the discussion :)

**Comment by ranyitz** [comment]
@netanelgilad Let me explain myself.

I think that the high level problem definitely worth a discussion, a specific feature might narrow us to specific constraints.

IMHO the high level problem here, is that we are adding features to the generators (out of yoshi's facade) which only get to the hands of new users.

Now, there are multiple ways to approach this problem.

You've suggested to add a command that helps with the migration process. I think that being able to do so will require us to face a merge between the user's code and our new features.

I'm suggesting to list the features that we currently have outside of yoshi, and that we should try and insert them into yoshi facad, so we could update them though normal upgrade to yoshi versions.

**Comment by netanelgilad** [comment]
@ranyitz @ronami @yairhaimo Do you think we should keep this issue up for discussion?
