### ISSUE TITLE
Add e2e tests for generators local development

### ISSUE THREAD

**Issue by ronami** [wix/yoshi#546]
# 🐛 Bug Report

### 😯 Current Behavior

Currently, on our e2e tests, we only test that running `npm build`/`npm test` work correctly. If something breaks local development we don't know about it.

### 🤔 Expected Behavior

We're going to make changes to local development and we should be able to know (when we make a PR) that we didn't break local development.

### 💁 Possible Solution 

We can add an e2e test (`create-yoshi-app`) that will run `npm start` and poll requests to `http://localhost:3000`. Once it returns a 200 request, match it against the previous snapshot.

**Comment by ranyitz** [comment]
We should definitely do this.
