### ISSUE TITLE
Show served files from yoshi's development server (local cdn)

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#547]
# 🙋 Feature Request
Being able to browse served files from our cdn (local development server)

### 😯 Current Behavior

The user needs to create the full url on his own, he might do a mistake.

### 🤔 Expected Behavior

When heading to the server port, yoshi should list the possible served files, so it will be easier to identify what/where they are.

### 💁 Possible Solution

We can look at [serve](https://github.com/zeit/serve) as an inspiration.

![image](https://user-images.githubusercontent.com/11733036/44775082-6810e700-ab7d-11e8-905c-6c31e005e334.png)

**Comment by amitdahan** [comment]
Should this list webpack's in-memory representation of its build result, or list the project's `dist` or `dist/statics` directories?
Or maybe a mix?

**Comment by ranyitz** [comment]
I think the best experience is to have all of them.

For example, consider the following files:

`/app.bundle.js` -> file content
`/assets/image.png` ->  image content

The expected behavior:

`/assets` -> link to `image.png`
`/` -> link to the `assets` directory and a link to `app.bundle.js`

I'll accept a PR that solves only one of them, as this is better than what we currently have.

**Comment by amitdahan** [comment]
From what I’ve seen from the code, it seems the default static files server is serving from /dist/statics
So I’m assuming you meant statics instead of assets?

**Comment by ranyitz** [comment]
@amitdahan It was just an example to demonstrate the general idea. In our case the assets directory is placed here -> `${projectDir}/dist/statics/assets` but served on `localhost:${PORT}/assets`.

The user should see only the files that served from the dev server. For this feature, we don't really care about their filesystem path, but it could be a cool feature to see it when you hover 😄

**Comment by ranyitz** [comment]
@shahata brought up [serve-index](https://github.com/expressjs/serve-index) as a solution for the static files, which works great for our static assets.

I've checked it and it's easy to integrate with our express server.

> Serves pages that contain directory listings for a given path.

The only problem is that it looks for file system paths only, and will not show the bundles that being served from memory.
____________________

Few things we can do from here:
1. Search for something that already does that (I couldn't find one)
2. Try to [persist files](https://github.com/webpack/webpack-dev-middleware#writetodisk), but it seems to be an overkill for this feature.
3. Add a feature in `serve-index` which enables us to add custom files (and then add Webpack bundles/chunks) - We can always start with a fork.
4. Write a custom solution that incorporates file listing for Webpack bundles/chunks (served from memory).

____________________

What do you think?

**Comment by shahata** [comment]
I think it is a good idea to persist the files regardless of this feature.

**Comment by shahata** [comment]
It's also the most easy solution

**Comment by ranyitz** [comment]
Duplicated, Let's continue the discussion on #753
