### ISSUE TITLE
Real error is swallowed when trying to load mocha-setup.js and it fails due to missing dependant module

### ISSUE THREAD

**Issue by ob1** [wix/yoshi#56]
In `yoshi/lib/setup/mocha-setup.js`, the path for `mocha-setup.js` is computed and then optionally-loaded via `tryRequire` which swallows `MODULE_NOT_FOUND` errors - even if they were generated from missing dependant modules.

cc @ronami

**Comment by tqmukas** [comment]
`tryRequire` does not swallow `MODULE_NOT_FOUND` errors:
https://github.com/wix/yoshi/blob/master/yoshi/lib/utils.js#L34
https://github.com/wix/yoshi/blob/589f62101684327eb022547c2cf807bac7056c4c/yoshi/config/test-setup.js#L16

Please reopen if it still happens.
