### ISSUE TITLE
Yoshi basic app reduce build time

### ISSUE THREAD

**Issue by yaelz** [wix/yoshi#567]
# 🙋 Feature Request

### 😯 Current Behavior

Running a "hello world" Yoshi app build takes ~3 minutes.

### 🤔 Expected Behavior

I expect it should take less than that :)

### 💁 Possible Solution 

Haven't thought of it yet, need to get into your code. Just wanted to draw your attention to it and check if you're on it..?

**Comment by yairhaimo** [comment]
Im guessing you mean in the CI, right?
That includes the `npm install` time which can take over a minute.
We'll look into it. Of course, if you have any other information you are more than welcomed to share.

**Comment by yaelz** [comment]
Yes, I meant in the CI.
You're right, "npm install" takes a lot of the time. "npm WARN deprecated" phase takes about 40 seconds. Maybe those packages should be checked out?

![image](https://user-images.githubusercontent.com/8150588/45415936-6ff57e80-b687-11e8-8696-15427e43c23d.png)

Also the Docker build step takes one minute. I suppose there's nothing we can do about that?
