### ISSUE TITLE
[babel-preset-yoshi] does not support dynamic imports for server only project

### ISSUE THREAD

**Issue by astrauka** [wix/yoshi#568]
# 🐛 Bug Report

### 😯 Current Behavior

Create a new server only project and use dynamic import there:
```
import(file).then(...)
```

Build the project and run it, you will get an error that `import is undefined`.

### 🤔 Expected Behavior

Babel should replace dynamic imports with require statements for node.

### 💁 Possible Solution

https://github.com/wix/yoshi/blob/dea717719c1a15af9846805d08a4789d976f0bc3/packages/babel-preset-yoshi/index.js

```
diff --git a/packages/babel-preset-yoshi/index.js b/packages/babel-preset-yoshi/index.js
index f96751a..bc84965 100644
--- a/packages/babel-preset-yoshi/index.js
+++ b/packages/babel-preset-yoshi/index.js
@@ -15,14 +15,14 @@ const normaliseOptions = opts => {
 
 module.exports = function(api, opts = {}) {
   const options = normaliseOptions(opts);
+  const modules = options.modules || process.env.IN_WEBPACK ? false : 'commonjs';
 
   return {
     presets: [
       [
         require('babel-preset-env').default,
         {
-          modules:
-            options.modules || process.env.IN_WEBPACK ? false : 'commonjs',
+          modules,
           // Display targets to compile for.
           debug: options.debug,
           // Always use destructuring b/c of import/export support.
@@ -65,7 +65,7 @@ module.exports = function(api, opts = {}) {
       require('babel-plugin-transform-decorators'),
       // Transform dynamic import in test environment,
       // in all other cases Webpack will handle the transformation.
-      isTest
+      (isTest || modules === 'commonjs')
         ? require('babel-plugin-dynamic-import-node').default // https://github.com/airbnb/babel-plugin-dynamic-import-node/issues/27
         : require('babel-plugin-syntax-dynamic-import'),
       // Current Node and new browsers (in development environment) already implement it so
```

### 🌍 Your Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
    npm: 6.3.0 - ~/.nvm/versions/node/v8.9.4/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 60.0.2
    Safari: 11.1.2
  npmPackages:
    yoshi: ^3.0.0 => 3.10.1 

 Yoshi config
{
  "hmr": "auto"
}
```

**Comment by ranyitz** [comment]
@astrauka Thanks for opening this issue! Good point 👍 

I think that getting a runtime error here is really bad and we should fix it.
The only situation that we would like to use the `syntax` plugin is for webpack environment, so I would change this condition to something like:

```js
(inWebpack)
     ? require('babel-plugin-syntax-dynamic-import')
     : require('babel-plugin-dynamic-import-node').default,
```

Would you send a PR that fixes it?

**Comment by astrauka** [comment]
@ranyitz could you allow others to create PRs in the repo? Now getting this on push:
```
ERROR: Permission to wix/yoshi.git denied to astrauka.   
fatal: Could not read from remote repository.            

Please make sure you have the correct access rights      
and the repository exists. 
```

Not willing to create a fork :(

**Comment by ranyitz** [comment]
@astrauka Everybody can create PRs using the [fork flow](https://guides.github.com/activities/forking/). It's a pretty standard way to manage OSS projects in a way that enables a group of maintainers to manage sourcecode/tags/issues etc. It should be fairly easy to do and I'm willing to help with that if needed.

**Comment by astrauka** [comment]
@ranyitz I can create a branch for wix-style-react which is also OSS. I have no permissions to push to master there. That's the experience I want to have with yoshi. I see no security issue with having that.

**Comment by ranyitz** [comment]
@astrauka This issue is about supporting dynamic imports for server only projects.

> That's the experience I want to have with yoshi

You can feel free to open a different issue regarding yoshi's contribution experience.
