### ISSUE TITLE
Update "typescript" version in peer dependencies of yoshi-helpers

### ISSUE THREAD

**Issue by nktssh** [wix/yoshi#578]
# 🐛 Bug Report

### 😯 Current Behavior

`
npm WARN yoshi-helpers@3.10.1 requires a peer of typescript@^2.0.0 but none is installed. You must install peer dependencies yourself.
`

### 🤔 Expected Behavior

Should give no warnings

### 🔦 Context 

Spotted it here:
http://tc.dev.wixpress.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=69142853&_focus=751

### 💁 Possible Solution 
Update peer version – we have `typescript@^3.0.0` and all is fine

### 👣 Steps to Reproduce 
`npm i` in yoshi project with `typescript@^3.0.0` as dependency

### 🌍 Your Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
    Yarn: 1.2.1 - ~/.yarn/bin/yarn
    npm: 6.4.0 - ~/.nvm/versions/node/v8.9.4/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 69.0.3497.92
    Firefox: 61.0.2
    Safari: 11.1.2
  npmPackages:
    yoshi: ^3.5.0 => 3.10.1 

 Yoshi config
{
  "universalProject": true,
  "separateCss": "prod",
  "entry": [
    "react-hot-loader/patch",
    "./client/client.tsx"
  ],
  "servers": {
    "cdn": {
      "port": 3200,
      "dir": "dist/statics",
      "ssl": false
    }
  },
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM",
    "immutable": "Immutable",
    "draft-js": {
      "root": "Draft",
      "commonjs2": "@wix/draft-js",
      "commonjs": "@wix/draft-js",
      "amd": "@wix/draft-js",
      "umd": "@wix/draft-js",
      "var": "Draft"
    },
    "@wix/draft-js": {
      "root": "Draft",
      "commonjs2": "@wix/draft-js",
      "commonjs": "@wix/draft-js",
      "amd": "@wix/draft-js",
      "umd": "@wix/draft-js",
      "var": "Draft"
    }
  }
}
```

**Comment by ranyitz** [comment]
@nktssh Thanks for opening this issue, it looks like a mistake, I think `>=2.0.0` should do the trick.

Do you want to open a PR?

**Comment by nktssh** [comment]
@ranyitz sure, will do!
But I'm not sure that it's ok to allow all future versions. Maybe, it worth to use something like 
`^2.0.0 || ^3.0.0` ?

**Comment by ranyitz** [comment]
Good point. Thanks!
