### ISSUE TITLE
Restore ability to generate webpack stats file

### ISSUE THREAD

**Issue by ronenst** [wix/yoshi#583]
# 🙋 Feature Request

### 😯 Current Behavior
Since version `3.11.0` Yoshi stopped generating the `target/webpack.stats.json` file for performance reasons and will now only creates the file if the `--analyze` flag is set, since that was it's intended purpose.

In PR: https://github.com/wix/yoshi/pull/565

### 🤔 Expected Behavior
Add the ability to generate the stat files (both debug and production versions).

### 💁 Possible Solution 
Add a `--stats` or `--with-stats` or `--generate-stats` or `--profile` or `--with-profile` flag which will generate the files in the expected place.

This would also allow extending the flag in the future to take a filename template as the value of the flag. That is:
`yoshi build --stats file.json` 
Could generate `file.stats.json` and `file.min.stats.json`

### 🔦 Context 
This breaks anyone using the [business manager auditor](https://github.com/wix-private/business-manager-auditor) tool which relies on this file to check that unnecessary globally provided files are not bundled.

The `--analyze` flag can't be used in this instance since the auditor runs unattended and the analyzer doesn't halt.

In addition I have found it useful on occasion to use the non-minified version of the stats file when using [other third party tools](https://github.com/wix/yoshi/blob/master/docs/faq/WEBPACK-ANALYZE.md) to analyze the bundle, but now there is no way to generate one.

**Comment by ranyitz** [comment]
Thanks @ronenst for opening this issue!

I agree that the static creation of the stats file can be useful and should be controllable.

`--stats` seems to be a good name for it, but I'm open for suggestions.

PRs welcome!
