### ISSUE TITLE
Can't commit fresh app (generated by `create-yoshi-app`)

### ISSUE THREAD

**Issue by sidoruk-sv** [wix/yoshi#598]
# 🐛 Bug Report

Can't commit apps that are generated by `create-yoshi-app`, tried templates for `fullstack` (and `universal`), Babel (and Typescript). Also tried run that on Node.js 10.11 - error is the same.

### 😯 Current Behavior

Fresh install of project created by `create-yoshi-app` can't be committed (pre-commit hooks failed).
```sh
$ git add .
$ git commit -m "initial commit"

Found '/Users/serhiis/projects/example-app/.nvmrc' with version <8.9.1>
Now using node v8.9.1 (npm v5.5.1)
Found '/Users/serhiis/projects/example-app/.nvmrc' with version <8.9.1>
Now using node v8.9.1 (npm v5.5.1)
husky > npm run -s precommit (node v8.9.1)

 ❯ Running tasks for *.{js,ts,tsx,scss,less}
   ✖ yoshi lint
✖ "yoshi lint" found some errors. Please fix them and try committing again.
running tslint on /Users/serhiis/projects/example-app/test/server/server.spec.ts,/Users/serhiis/projects/example-app/test/helpers/i18n.mock.ts,/Users/serhiis/projects/example-app/test/environment.ts,/Users/serhiis/projects/example-app/test/e2e/app.spec.ts,/Users/serhiis/projects/example-app/src/test-types.d.ts,/Users/serhiis/projects/example-app/src/server.ts,/Users/serhiis/projects/example-app/src/i18n.ts,/Users/serhiis/projects/example-app/src/external-types.d.ts,/Users/serhiis/projects/example-app/src/components/App/index.ts,/Users/serhiis/projects/example-app/src/components/App/App.tsx,/Users/serhiis/projects/example-app/src/components/App/App.spec.tsx,/Users/serhiis/projects/example-app/src/client.tsx
/Users/serhiis/projects/example-app/src/test-types.d.ts:7:9
ERROR: 7:9  prettier  Delete `·`

/Users/serhiis/projects/example-app/src/components/App/App.spec.tsx:2:9
ERROR: 2:9    prettier  Replace `mount` with `·mount·`
ERROR: 3:9    prettier  Replace `I18nextProvider` with `·I18nextProvider·`
ERROR: 15:13  prettier  Insert `·`


Warning: The 'await-promise' rule requires type information.
Warning: The 'no-floating-promises' rule requires type information.
Warning: The 'no-for-in-array' rule requires type information.
Warning: The 'restrict-plus-operands' rule requires type information.
Warning: The 'use-default-type-parameter' rule requires type information.
Warning: The 'deprecation' rule requires type information.
Warning: The 'prefer-readonly' rule requires type information.
Warning: The 'no-unnecessary-qualifier' rule requires type information.
tslint exited with 4 errors (4 fixable)

husky > pre-commit hook failed (add --no-verify to bypass)
```

### 🤔 Expected Behavior

Fresh install of generated app is able to be committed.

### 💻 Code Sample

Can't provide repository, cause fresh app can't be committed.

### 🌍 Your Environment

```sh
  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0.2
    Safari: 12.0
  npmPackages:
    yoshi: ^3.0.0 => 3.11.0

 Yoshi config
{
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM"
  },
  "hmr": "auto"
}
```

**Comment by splintor** [comment]
I run into this as well as part of my onboarding [Zero to Production](https://github.com/wix-private/fed-handbook/blob/master/ZERO_TO_PRODUCTION.md).

**Comment by ranyitz** [comment]
Thanks @sidoruk-sv & @splintor!

When running `npx yoshi lint` it passes, but when `lint-staged` runs `yoshi lint <...staged-files>` during commit hook it finds more files (which was not linted during `yoshi lint`) and fails.

This is a bug that indicates some important problems to fix, I'll elaborate.

1. There is a differential between the way we are running `yoshi lint` (without arguments) and `yoshi lint ./file/path.ts`. The first is using `tsconfig.json` to [determine which files to run on](https://palantir.github.io/tslint/usage/type-checking/), the second is using pattern/s.

3. `d.ts` files are not getting linted using `yoshi lint` despite them being specified in the `tsconfig.files` array.

4. `spec.ts[x]` are not getting linted and/or type checked on newly generated projects.

### What's next?

1. We should always lint using `tsconfig.json` and only filter the files specified using the pattern. We may throw a warning if a file was specified in the pattern but not in the tsconfig.

2. `d.ts` files should be linted when using `yoshi lint`.

3. Add test files to the `include` section of the `tsconfig.json` in our templates.
