### ISSUE TITLE
externalUnprocessedModules doesn't support linked modules

### ISSUE THREAD

**Issue by roymiloh** [wix/yoshi#60]
We've encountered this problem before and it emerged recently again.

Symlink modules are passed with their original path [here](https://github.com/wix/yoshi/blob/master/yoshi/config/project.js#L49), so they don't have a `node_modules` prefix.

Remove `node_modules` is naive.

**Comment by sdoomz** [comment]
@roymiloh  I've also faced the same issue, it makes local development very painful because I'm not able to import local npm package from the outside of the project's root.
any updates for this? or maybe known workaround?
