### ISSUE TITLE
add package-lock.json to generators

### ISSUE THREAD

**Issue by netanelgilad** [wix/yoshi#625]
# 🙋 Feature Request

### 😯 Current Behavior

`package-lock.json` is git ignored.

### 🤔 Expected Behavior

`package-lock.json` would be generated by `create-yoshi-app` for faster installs and it should not be git ignored (users will be able to add to `.gitignore` if they choose to(.

### 🔦 Context 

[Similar issue on CRA](https://github.com/facebook/create-react-app/pull/5270) and also as a best practice that we want to integrate.

**Comment by yairhaimo** [comment]
What about libraries that are developed by the same team?
I guess they would want them to be on `latest` all the time (in most cases) and `package-lock.json` would be a hassle in that case.

**Comment by netanelgilad** [comment]
Maybe they will just remove the package.lock if they don't want it? The idea we talked about was to make the initial `npm install` faster by generating the lock file when creating the project (before `npm install`) and then `npm install` would be faster, and a user can opt out by removing the `package-lock.json`. 

It could be something that we add in a guide, but currently `package-lock.json` is created when running `npm install` and it is gitignored, so you get inconsistencies between developer environments. 

The other option is to add to `.npmrc` file to the generated project, and make sure that `package-lock.json` is not generated at all.

**Comment by yairhaimo** [comment]
Won't generating a lock file when creating a project take the same time too (resolving the correct version and all)?

**Comment by netanelgilad** [comment]
Yeah, I meant generating by `create-yoshi-app` and not by npm (at the same time we are writing `package.json`). So when `npm install` runs it will already have the resolutions. That is what `create-react-app` does.

**Comment by ranyitz** [comment]
@netanelgilad I think that adding the `.npmrc` with the `package-lock = false` options make sense for the current behavior.

If we want to change that and start putting lock files (because we think that everyone should use them) we can do that instead.

If we want to speed up installs by publishing the lock files in the templates themselves (Like create react app does) this would be great but can be a bit harder, so I think it makes sense to separate it to a different issue/pr.

**Comment by ranyitz** [comment]
PRs welcome to add `.npmrc` with `package-lock = false` option to the templates.

**Comment by cowchimp** [comment]
Resolved by #953 and #957.
