### ISSUE TITLE
create-yoshi-app: installed dependencies are not according to `.nvmrc` file

### ISSUE THREAD

**Issue by shlomitc** [wix/yoshi#631]
# 🐛 Bug Report
While using `create-yoshi-app`, it automatically installs dependencies with wrong node version.

### 😯 Current Behavior
Installs the dependencies according to the currently used node version (usually system)

### 🤔 Expected Behavior
Install the dependencies according to the `.nvmrc` file (version 8)

### 🔦 Context 

none

### 💁 Possible Solution

read the `.nvmrc` file and run `nvm install && nvm use` first.

### 👣 Steps to Reproduce 

Just generate a new project.

### 💻 Code Sample

none

### 🌍 Your Environment

latest

**Comment by ranyitz** [comment]
After discussing with @netanelgilad and @ronami we think that it will be best to let the user know that his current node version and the intended `.nvmrc` version is different (in a major version).

If that's the case, we'll prompt and ask the user if he wants to continue or cancel the operation.

We need to explain that if you cancel and want to use the specific node version you need to change your node version to be the same as the `.nvmrc` one.
