### ISSUE TITLE
karma config: duplicated browsers

### ISSUE THREAD

**Issue by eddierl** [wix/yoshi#642]
# 🐛 Bug Report

### 😯 Current Behavior

there are two chrome headless browsers running for karma

### 🤔 Expected Behavior

run only one chrome headless driver
### 🔦 Context 

we use chrome headless browser in karma by setting in karma.conf:
`browsers: ['ChromeHeadless']` 

yoshi@3 merge the configuration and the result is
`browsers: [ 'ChromeHeadless', 'ChromeHeadless' ]`
 and then it starts two browsers
```
[karma]: Karma v2.0.5 server started at http://0.0.0.0:9876/
[launcher]: Launching browsers ChromeHeadless, ChromeHeadless with unlimited concurrency
[launcher]: Starting browser ChromeHeadless
[launcher]: Starting browser ChromeHeadless
```

### 💁 Possible Solution 

looks like it's caused by the `customizer`, I don't know what was it purpose.
https://github.com/wix/yoshi/blob/master/packages/yoshi/config/karma.conf.js#L32-L39

### 👣 Steps to Reproduce 

create a yoshi project that using karma
config browsers in karma.conf
run tests

### 💻 Code Sample

...

### 🌍 Your Environment
yoshi@3

**Comment by ranyitz** [comment]
@eddierl I know it's not a perfect solution, but you can specify `yoshi.browsers` instead. In Yoshi's configuration.

see the following line:
https://github.com/wix/yoshi/blob/512602b3f92d0dbc28c2de0ab344d1ee9fb9af8e/packages/yoshi/config/karma.conf.js#L11

Can you please check that and let me know if it solves it?

**Comment by eddierl** [comment]
thanks @ranyitz
`projectConfig` is the content of `karma.conf`, no?

**Comment by eddierl** [comment]
@ranyitz , currently I only did your solution on the `browsers` field, since that's the bug.

I guess it's better not to load mocha when using jasmine for example, but it doesn't break things(which makes it also harder to test the way the tests are written😄)

wdyt?
