### ISSUE TITLE
Verify package tree for multiple versions of the same package

### ISSUE THREAD

**Issue by ronami** [wix/yoshi#650]
# 🙋 Feature Request

For some dependencies (Webpack, ESLint, Jest) having multiple versions installed are likely to break project setup with errors that are hard to understand. We can verify that there is only one version of each of these and fail with a clear error otherwise.

See [create-react-app's](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/scripts/utils/verifyPackageTree.js#L18) implementation as an example.

**Comment by ranyitz** [comment]
Currently https://github.com/wix-private/sled is opening us to a world where there are two versions of `webpack`, `jest` and more.

I'm not sure if we can work on this feature as it will break many project which uses sled.

**Comment by ranyitz** [comment]
[As we've seen before](https://wix.slack.com/archives/CAL591CDV/p1585153368015700?thread_ts=1585142509.011400&cid=CAL591CDV). Multiple versions of webpack can lead to `hmr` stop working. This is not necessarily a result of yoshi's code, so it won't be possible to see in tests, but the user may use a package that brings webpack in a different version.

For the hmr case, what we really want to check is that `webpack` is not installed under `yoshi-common` while there is another instance of webpack on the root.

Maybe we can also update the logic in webpack & the runtime to always take the instance from `yoshi-common`.

I'm adding it here as a reference to the future.

**Comment by illBeRoy** [comment]
How about we run a short check to test for `node_modules/webpack` existing and being version `4`? :)

**Comment by illBeRoy** [comment]
This is important now more than ever, with `sled` introducing `webpack@5` and essentially breaking builds as version 5 occupies `node_modules` instead of 4... :)

**Comment by ranyitz** [comment]
> For the hmr case, what we really want to check is that webpack is not installed under yoshi-common while there is another instance of webpack on the root.

I agree.

We should check that the version on the root is the same version as yoshi's version.

PRs welcome.

Prior art - https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/scripts/utils/verifyPackageTree.js#L19

**Comment by amitdahan** [comment]
What's our stance on how we should handle this? 

1. Do we print a warning and carry on as usual? (potentially broken) or do we break and allow an opt-out like [CRA did](https://github.com/facebook/create-react-app/blob/edc671eeea6b7d26ac3f1eb2050e50f75cf9ad5d/packages/react-scripts/scripts/build.js#L27-L29)?

2. Which packages do we care to "guard"? `webpack` & `webpack-dev-server` comes to mind. Any else?

3. CRA went with a full screen, highly detailing error. Not sure we should be as extreme.

**Comment by yurynix** [comment]
At the moment, I've pushed a hack to temporarily fix it and move forward.
https://github.com/wix-private/sled/pull/485 this installs webpack@5 on sled's postinstall hook

**Comment by ranyitz** [comment]
@amitdahan 

1. As this may lead to a potential breakage with things which are not immediately clear (Like HMR stop working) I would prefer throwing an error, and enable opt-out for extreme cases (like CRA did)

2. I would start with `webpack` as this is something we encounter all over and it would be a good remedy for those cases.

3. It should be clear enough so people won't miss it.

________________

@yurynix, thanks for updating. Another possible solution would be to [pkg](https://github.com/zeit/pkg#readme) sled, which would create a different dependencies tree for seld. (which can of-course lead to a longer install time, but it needs to be checked) Or considering using `webpack@4` which is provided by yoshi and will be deduped for users in their node_modules tree.

**Comment by amitdahan** [comment]
So to summarize - we look for `webpack` instances in the root, and see if they match yoshi's `webpack` dependency?
CRA climbs all the way up to `/`, but covering project root sounds like it could be a very minimal effort and would cover the cases we've experienced yet.
Wdyt?

**Comment by ranyitz** [comment]
Sound good to me, please keep note that having 2 instances of webpack (even it's of the same version may cause a bug with `HMR`)

meaning, if we have the following, it's still problematic:
```
node_modules
├── webpack@4.0.0
└── yoshi-common
    └── node_modules
        └── webpack@4.0.0
```

We need that the version on the root would be the version specified in the range of `yoshi-common`. There can't be 2 different instances.

**Comment by amitdahan** [comment]
Just to clarify, the scenario you described isn't possible right?
So there's no way there'd be a `webpack` version that satisfies `yoshi-common` anywhere above it, but also in its own `node_modules`, right? (except maybe outside the project dir?)

**Comment by ranyitz** [comment]
I've updated to be more realistic.

`yoshi-common` requests a specific version of webpack, let's say `webpack: 4.1.6`.

The user (or another package that the user brings) request `webpack: ^4.2.0`.

In this case you'll get two versions of webpack in your node_modules and `hmr` wouldn't work.

**Comment by amitdahan** [comment]
> and hmr wouldn't work

Or worse! 🙀


K, got it.
