### ISSUE TITLE
Generated projects should come with react 16

### ISSUE THREAD

**Issue by netanelgilad** [wix/yoshi#651]
# 🙋 Feature Request

### 😯 Current Behavior

Generated projects come with react 15

### 🤔 Expected Behavior

Generated projects come with react 16

### 💁 Possible Solution 

upgrade dependencies

### 🔦 Context 

Because of progress.. :)

**Comment by ranyitz** [comment]
I would love to upgrade the react version, there are some really awesome features available only > 16. Unfortunately I think that our official component library [not yet supports it](https://github.com/wix/wix-style-react/blob/master/package.json#L106-L107).

@shlomitc I've seen there is an [open issue](https://github.com/wix/wix-style-react/issues/2313) about it. Is there a time est?

**Comment by shlomitc** [comment]
Hey. No time estimation yet but I assume it can take a few months.
We're allowing users to try using it in React 16 and letting us know for broken components.

**Comment by yairhaimo** [comment]
@shlomitc any new information on this? Is it just one component that is blocking us?
If it's just one component that is blocking this upgrade it needs to be solved in the scope of the component. Projects that use that component should find a workaround, a fix or use another component. This single component shouldn't block all other projects and newly created projects.
Thoughts?

**Comment by shlomitc** [comment]
Users have started migrating their projects in the past month and we didn’t hear complains other then those who mentioned in the issue, however I don’t think they are blockers.

I think it’s time to upgrade the generators and we will fix according to users feedback.

**Comment by ronami** [comment]
Closed in #1096.
