### ISSUE TITLE
add `index-dev` concept to the Fullstack templates.

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#657]
# 🙋 Feature Request

### 😯 Current Behavior
When a new fullstack project is generated, yoshi runs `index.js` file when the user run `yoshi start`.

After the user needs to add experiments, rpc etc... He/She will need to add [`--entry-point`](https://wix.github.io/yoshi/docs/api/cli#start) to the start command with a different file, and add a mock server for those services (or the app won't work in development).

This is not easy to find, some people end up with a non functional `start` experience, and some find other conventions and weird solutions.

### 🤔 Expected Behavior

The user create a new project and already has an `index-dev.js` file configured, so adding `experiments`/`rpc` becomes a simple task.

### 💁 Possible Solution

The first step would be to add `--entry-point` & `index-dev.js` to the Fullstack templates.

The second step would be to remove the `--entry-point` configuration (A breaking change, should be in a major version) and make it a default behavior.

### 🔦 Context

Regardless of the question if we need to bring experiment/rpc by default for our users, we definitely should create a unified way of running the server on development.

While client projects use the `--entry-point` feature for a `fake-server` and fullstack project use it to bootstrap the environment, it is still an opt-in feature.

I think that we can aim towards making it the default behavior.

**Comment by ronami** [comment]
I don't think we should wait to Yoshi v4 for this, I think it can be merged to master.
