### ISSUE TITLE
SplitChunks should work by default both for dynamic imports and multiple entries

### ISSUE THREAD

**Issue by yairhaimo** [wix/yoshi#658]
# 🙋 Feature Request

### 😯 Current Behavior

SplitChunks is currently an opt-in feature (https://wix.github.io/yoshi/docs/api/configuration#splitchunks).
You can either pass a configuration object that will passthrough to webpack or set it to `true` in order to receive Yoshi's default configuration.
Yoshi's default configuration creates a new bundle called `commons.bundle.js` that consists of all common code between chunks.
There are several issues with this:
1. The user needs to enter this new chunk manually in their html
2. If the application has multiple entrypoints with different html files the user will need to enter this new chunk manually to each html file
3. Dynamic imports will load this common chunk even if some of them need only part of the common code resulting in wasteful loading
4. If some of the common code is common between the application and a dynamic import, the application will load all of it at app startup. This will result in losing some of the performance advantage of lazy loading the dynamic import (because the common chunk was already loaded).

### 🤔 Expected Behavior

Yoshi should split common code to different chunks and manage it behind the scenes in a way that it will work for all of the above cases with no user intervention.

### 💁 Possible Solution 

Yoshi should split the common chunks to multiple chunks and not only `commons.bundle.js`. This way the dynamic imports will provide the performance boost we expect.

For the html files we can use the version 4 of [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) which knows how to inject the correct chunks to the correct html files according to the dependency graph. Right now the plugin needs to be configured which entrypoint chunk goes to which html file (and it will infer which additional common chunks will be added automatically). Yoshi can have a convention where the chunk name will go automatically to a similar named html file unless configured differently by the user.

### 🔦 Context 

Code Splitting is one of the best courses of action we can take in order improve the loading time of applications.

**Comment by ronami** [comment]
Relevant: #1090.
