### ISSUE TITLE
Remove Barely Used Configuration Options

### ISSUE THREAD

**Issue by yairhaimo** [wix/yoshi#659]
# 🙋 Feature Request

### 😯 Current Behavior

Yoshi has many configuration options where some of them are rarely used.

### 🤔 Expected Behavior

Yoshi should only retain the configuration options that are used by most of its users.

### 💁 Possible Solution 

Research and understand which options are rarely used. 
Remove these options and help the few users that actively use them to migrate to a new solution.

### 🔦 Context 

Less configuration options eventually result in higher product quality.

**Comment by ranyitz** [comment]
I strongly agree, and I want to add [this](https://github.com/prettier/prettier/issues/40#issue-199895633) for further reading.
