### ISSUE TITLE
Add documentation for pom.xml file

### ISSUE THREAD

**Issue by sidoruk-sv** [wix/yoshi#690]
Can someone explain what is pom.xml file for, and what the role of each item in it?

For example:
What does `organization` field info used?
Where is the complete list of organizations?
and
How can I determine correct organization for my project?

**Comment by netanelgilad** [comment]
The existing [documentation for the `pom.xml`](https://github.com/wix-private/fed-handbook/blob/master/WORKING_WITH_GENERATORS.md#pomxml) exists on [`fed-handbook`](https://github.com/wix-private/fed-handbook) repo. Also in the [ZERO TO PRODUCTION](https://github.com/wix-private/fed-handbook/blob/master/ZERO_TO_PRODUCTION.md#create-a-local-project) guide there is an explanation on the questions during a new project generation, including the organization.

We should try to make the documentation clearer and easier to find. How did you first encounter the `pom.xml` and the orgranization? Did you try the zero-to-prod and it wasn't clear enough? Did you look in the fed handbook? Did you maybe try to search in [yoshi's website](https://wix.github.io/yoshi) and didn't find an answer?

@ranyitz I think maybe the best/fastest solution would be to add an FAQ section to yoshi's website which would be searchable, and could then refer to the right documentation.

**Comment by sidoruk-sv** [comment]
Yes, I saw that information there, but for now, the more people I ask, the more I understand, that teammates don't know what is `organization` key for, and what key should be used for (or even: do we need to change some keys after teams reorganizations?)

Is this information used only for “meta-project information” or is any infrastructure using it?

Plus: I think it is better to add info about origins of pom.xml - https://maven.apache.org/pom.html (Maven for FEDs is not usual tool).

**Comment by ranyitz** [comment]
@netanelgilad I agree. We can add an FAQ section on Yoshi's website as we are providing this information in our templates and asking for it when a new app is created.

Maybe we should just enrich the getting started guide - https://wix.github.io/yoshi/docs/getting-started/create-app with the relevant information about what needs to be filled and why.

And regarding the files that we create for each project, I think it makes sense to add another **getting-started** sub guide that explains the contents of a generated project.
