### ISSUE TITLE
Stabilize server bundle feature and add to create-yoshi-app templates

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#704]
Bundling the server should be a stable feature on yoshi@4

**Comment by ronami** [comment]
Some progress: #826, #777.

**Comment by yairhaimo** [comment]
Opt in to the server bundle feature should be like this:
```json
"yoshi": {
  "projectType": "app"
}
```

We can change this at a later date (before we release yoshi 4) but it shouldn't be a blocker right now.
