### ISSUE TITLE
Internal: isTypescriptProject should not require tsconfig

### ISSUE THREAD

**Issue by netanelgilad** [wix/yoshi#728]
Wasn't sure where to start the discussion, so opened an issue.

https://github.com/wix/yoshi/blob/58e58cf445e8e7f8228bb17c6ee1c02da68a64fb/packages/yoshi-helpers/queries.js#L56-L57

Why are we trying to require `tsconfig.json` and not just checking for its existence? I just encountered and error where `tsconfig.json` has malformed JSON, and because of that `yoshi` fails. We should not fail, and Typescript is the one that should output the error IMO. We should decide a project is a typescript project just by the existence of a `tsconfig.json`.

@ranyitz @ronami What do you think?

**Comment by ranyitz** [comment]
Agree, PRs welcome
