### ISSUE TITLE
adding .npmrc file to templates

### ISSUE THREAD

**Issue by shilomangam** [wix/yoshi#729]
# 🙋 Feature Request
Yo guys, 
WDUT about adding `.npmrc` file to templates?
the `.npmrc` will contain the following:
```
registry=http://npm.dev.wixpress.com
```

### 😯 Current Behavior
Currently we're defining the npm registry on npm global configurations, IMHO it should be defined for each project separately, like `.nvmrc`.

...

### 🤔 Expected Behavior
npm install will use the project settings. 

...

### 💁 Possible Solution 
I will add it to the templates :)

...

### 🔦 Context 

...

**Comment by shilomangam** [comment]
never mind, its an open source project

**Comment by shilomangam** [comment]
after a short talk with @ranyitz, it still relevant.
please share your thoughts!

**Comment by ranyitz** [comment]
@shilomangam Sound good to me.

@yairhaimo thoughts?

**Comment by yairhaimo** [comment]
We're going to remove Wix's npm registry soon so I dont think its a big issue

**Comment by shilomangam** [comment]
You won.
