### ISSUE TITLE
New versions of prettier break project when linting

### ISSUE THREAD

**Issue by netanelgilad** [wix/yoshi#744]
# 🐛 Bug Report

### 😯 Current Behavior

When `prettier` releases a new version and change the way the format some code, our projects get broken in CI because lint not fails with errors from `prettier`. We depend on `prettier` with `^` so we get new minors from `prettier` automatically, and minors in `prettier` can change the formatting rules (this isn't a breaking change for `prettier` because they are just a formatter, but it is a breaking change for us because we use eslint, and emit an errors on prettier issues).

### 🤔 Expected Behavior

Projects builds should not fail because of new `prettier` versions.

### 🔦 Context 

Release 1.15 of `prettier` caused a lot of project build to fail today.

### 💁 Possible Solution 

Two possible solutions:
1. Make prettier errors into warning instead of errors. That way we can keep getting minor updates from `prettier` without failing.
2. Pin `prettier` version to only patches with a `~`.
@ronami @ranyitz @yanivefraim @roymiloh Thoughts?

**Comment by ranyitz** [comment]
+1 for making prettier errors into warnings, I'll explain why:

> Strict & balanced - Add non-fixable rules only if they will help to find bugs

This is taken from our blog post - [yoshi 3 release](https://wix.github.io/yoshi/blog/2018/06/3/yoshi-3#lint)

I don't think that prettier help finding bugs in our code and failing the build because of them is not a balanced approach.
