### ISSUE TITLE
Health - clean local file changes after running Yoshi generator's e2e test

### ISSUE THREAD

**Issue by yanivefraim** [wix/yoshi#757]
# 🐛 Bug Report

### 👣 Steps to Reproduce 

1. Run Yoshi generator's e2e tests (`npm run e2e`)
2. `git status`

We now have changes to local files:

<img width="762" alt="screen shot 2018-11-11 at 22 30 30" src="https://user-images.githubusercontent.com/1336186/48317923-778ec080-e601-11e8-9364-cac4d9dec2ba.png">

### 🤔 Expected Behavior

There shouldn't be any local changes after running `npm run e2e`

### 💁 Possible Solution 

We should clean after e2e tests finishes

**Comment by ronami** [comment]
I'm not sure how easy it would be as `lerna publish` makes a lot of changes to every `package.json`. #759 can help a lot with running it locally though.

**Comment by Schniz** [comment]
maybe we should copy them to a temp directory and make all the work there?
I'm not sure that cleaning the changes is a good thing - what if I did some changes or I have some file I'm working on which is untracked? I don't expect `e2e` to manipulate any of my files
