### ISSUE TITLE
lerna bootstrap -- hoist crashes yoshi

### ISSUE THREAD

**Issue by amiryonatan** [wix/yoshi#763]
# 🐛 Bug Report

### 😯 Current Behavior

We are trying to use `lerna bootstrap` with flag `--hoist` to optimize the setup of the monorepo.
When we do that, yoshi crashes.
You can look at the log here:
http://pullrequest-tc.dev.wixpress.com/viewLog.html?buildId=1098107&buildTypeId=Onboarding_AdiClient_AdiClientAll&tab=buildLog

...

### 🤔 Expected Behavior

`lerna boostrap --hoist` should work!
...

Link for the PR with --hoist that is failing:
https://github.com/wix-private/adi-client/pull/200/files

TC log of failure:
http://pullrequest-tc.dev.wixpress.com/viewLog.html?buildId=1098107&buildTypeId=Onboarding_AdiClient_AdiClientAll&tab=buildLog

Issue persists locally as well.

**Comment by ranyitz** [comment]
@amiryonatan Thanks for opening the issue.

`lerna boostrap --hoist` is an optimization for faster installation of a monorepo managed by lerna.

> Use caution when enabling this feature, as certain configurations can cause problems.

From [lerna's docs](https://github.com/lerna/lerna/blob/master/doc/hoist.md#lerna-hoisting)

_____

> Unfortunately, some tooling does not follow the module resolution spec closely, and instead assumes or requires that dependencies are present specificially in the local node_modules directory. To work around this, it is possible to symlink packages from their hoisted top-level location, to individual package node_modules directory. Lerna does not yet do this automatically, and it is recommended instead to work with tool maintainers to migrate to more compatible patterns.

It may be Yoshi or one of the underlying tools, but it needs investigation.

**Comment by amiryonatan** [comment]
Seems unrelated to yoshi
