### ISSUE TITLE
Yoshi is configured to retry for every failing test

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#779]
# 🐛 Bug Report

### 😯 Current Behavior
When you run tests locally, yoshi retries and run the test twice in case of a failing test.

### 🤔 Expected Behavior

Locally the test needs to run once.

### 🔦 Context 

The retries is a feature to reduce CI flakiness.

### 💁 Possible Solution

Add a test script that configures mocha to runs with retries only on CI.

**Comment by yurynix** [comment]
Solved in #782
