### ISSUE TITLE
Improve testing infrastructure

### ISSUE THREAD

**Issue by ronami** [wix/yoshi#785]
The intent of this issue is to suggest a change to how our tests are currently organized. It aims to make it easier to add tests to a new package, understand easier where a new test should be added, and group tests with the same nature (unit, e2e).

Currently, we have 3 types of tests across the monorepo:

* __E2E tests for a new project generated with `create-yoshi-app`__: These tests generate a new project, install dependencies, then build and test each project.
* __E2E tests for Yoshi (that incorporates testing most of the packages in the monorepo)__: Those are tests that create a few complex projects that cover a lot of different edge-cases, build, run, and test that everything is working.
* __Unit tests for various packages (currently split between Mocha and Jest)__: Each package can have its own unit tests, nothing too fancy.

Our CI runs those tests with 4 different checks. That creates a few problems:

* It is not immediately clear where a new test should be added.
* When creating a new package, you have to setup testing infra for it.
* It makes sense to run all unit tests together instead of running them in several checks on CI.

After discussing with @ranyitz, we suggest those changes to improve the testing infra:

* We can start by moving `yoshi-configs` tests to Yoshi's E2E tests. The nature of those tests are E2E tests. They test Yoshi and related packages and not only `yoshi-configs`.
* We can then move `eslint-config-yoshi-base`, `tslint-config-yoshi-base` and `yoshi-helpers` unit tests to use Jest instead of Mocha.
* Once all unit tests are being run with Jest, we should make sure they're all under the same glob: `__tests__` at each package root.
* Then, combine all unit tests to a single Jest run at the root of the monorepo.
* Eventually, change CI settings accordingly (ask for @ranyitz's help).

In the future, we can also:

* Move Yoshi's E2E tests to the root directory, run them with Jest, and improve them, see #777.
* Also move the template E2E tests to the root of the repo, and run them with Jest once https://github.com/facebook/jest/issues/6616 is closed.

**Comment by Schniz** [comment]
Are we sure that we want to have one single run with Jest in CI? I think splitting it to multiple packages can be beneficial:

* `yoshi: e2e`
* `yoshi: unit`
* `create-yoshi-app: e2e`
...

I think it can leverage more machines, therefore more cores and run more tests in parallel. wdyt? a single `jest` can also be used locally, but what about CI?
