### ISSUE TITLE
Change create-yoshi-app templates to work with the public npm registry

### ISSUE THREAD

**Issue by netanelgilad** [wix/yoshi#797]
# 🙋 Feature Request

### 😯 Current Behavior

Project templates used by `create-yoshi-app` use private wix dependencies without using the `@wix` which means they depend on the private npm registry.

### 🤔 Expected Behavior

Templates should bring wix private dependencies from the `@wix` scope on the public npm registry, and should install correctly when configured against the public npm registry.

### 🔦 Context

This would help new project work against the public npm registry as part of the move to remove the private npm registry.

**Comment by matveyok** [comment]
@ronami what do you thing about this? looks simple and very important.

**Comment by yairhaimo** [comment]
Staying with the internal Artifactory for the time being.
