### ISSUE TITLE
add some basic generators

### ISSUE THREAD

**Issue by shahata** [wix/yoshi#8]
generator can be modular, but eventually user should only need to run one generator. preferably, even if we use `yo`, user should simply run `yoshi new` which will run `yo yoshi` or something similar internally.

when generating we should have some general questions (author, package name, etc.), then user should choose between options:
* Fullstack
* Universal
* Client
* Node Library
* Server

In case of Client project, choose framework (otherwise, use react):
* React
* Angular 1
* Angular 2

Then user should choose transpiler:
* Babel
* TypeScript

Probably node code, we are not going to transpile by default, need to discuss

**Comment by yanivefraim** [comment]
+ docs

**Comment by ronami** [comment]
@shahata closing as this is far far away for now. We will re-open when it's relevant again.
