### ISSUE TITLE
Build and deploy the website on PRs

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#800]
# 🙋 Feature Request

### 😯 Current Behavior

When someone is doing a PR to the website/docs, there is no live example to see.

### 🤔 Expected Behavior

The website can be previewed from the PR. (A comment with a link?)

### 💁 Possible Solution

Use something like https://surge.sh/ to deploy a temporary site with the changes from the PR and post a link as a comment.

### 🔦 Context

It's easier and faster to review PRs that way, which should speed up the work on the documentation.

### ⚙️ Nice to have

It would be very nice if it would run only if there was a change to the website.

(We can check if there was a change in the website/docs directories using GIT and run the publish + comment only then)

**Comment by ranyitz** [comment]
I've seen https://github.com/wix/surge-github-autorelease around, @odedcagan @shilomangam perhaps you can help?

**Comment by shilomangam** [comment]
I can assist with this, will try to do it till the weekend.

**Comment by ranyitz** [comment]
@shilomangam Awesome, thanks!

**Comment by saarkuriel** [comment]
Work done so far:
PR #950 has the basic setup for this. It deploys the website to surge.sh for every PR.
What's left:
* Notifying in the PR that the deployment has succeeded with a link to surge.sh
* Running this job only when docs were changed (check the diff in the commit and if docs were changed - deploy the site)

@ranyitz @ronami

**Comment by nktssh** [comment]
For notifying I think one of suitable approaches is to create Github app which will be listen to webhook: 
> **Check runs**
> Check run is created, requested, rerequested, or completed.

and if Travis check is completed and there are changes in `docs/` or `website/` folder - post a comment with link. Link should be created manually in the same way Travis does it.

cc @ranyitz @ronami

**Comment by ranyitz** [comment]
@nktssh Thanks! I think that once we do that, we may consider adding the surge release process to the same place, so after it finishes the release it will notify the user using a comment/status check.

**Comment by vozhekhovskyi** [comment]
Hi @ranyitz ,
I and @brumeregan would like to help with this task (I mean `Notifying in the PR...`), but seems we need permissions to change repo settings.
So is it possible to provide us with appropriate permissions?

**Comment by ranyitz** [comment]
Hey @vozhekhovskyi That's great that you are taking this!

If it's ok, I prefer that you'll specify what needs to be changed and someone from the Yoshi team will make those changes (@yavorsky can you help?)

**Comment by yavorsky** [comment]
@ranyitz I can, but I don't have permissions also.
