### ISSUE TITLE
Upgrade to Lerna 3

### ISSUE THREAD

**Issue by ronami** [wix/yoshi#819]
### Summary

Pretty straight-forward, will help with #818.

**Comment by ranyitz** [comment]
@ronami it seems that stalebot marked this issue as stale even though we had the `help wanted` tag. I've seen it's happening in many other PRs but here I'm quite sure that it marked it despite our configuration.

Should we try flipping it back into emojis? (instead of `:pinned:` for example)

**Comment by ronami** [comment]
> @ronami it seems that stalebot marked this issue as stale even though we had the `help wanted` tag. I've seen it's happening in many other PRs but here I'm quite sure that it marked it despite our configuration.
> 
> Should we try flipping it back into emojis? (instead of `:pinned:` for example)

I noticed it too. It didn't work with emojis either. We definitely need to look into it, it starts getting annoying. 👍

**Comment by ronami** [comment]
Closed in #1400.
