### ISSUE TITLE
refactor: use `terminate` instead of `killSpawnProcessAndHisChildren`

### ISSUE THREAD

**Issue by yanivefraim** [wix/yoshi#846]
# 🙋 Feature Request

### 😯 Current Behavior
We use `killSpawnProcessAndHisChildren` all over in order to kill a process and its children

### 💁 Possible Solution 
We should try moving to [terminate](https://github.com/dwyl/terminate)

**Comment by yairhaimo** [comment]
Is there any functional difference between the two?
