### ISSUE TITLE
SeparateCss should not show warning when set to true

### ISSUE THREAD

**Issue by aarnoldaas** [wix/yoshi#847]
# 🐛 Bug Report

### 😯 Current Behavior
We have this message/warning:
configuration/separateCss should be one of these:
   "prod" | false
   Field Description: Whether to separate the bundle for css files from the main js bundle.
But then I pass 
separateCss: true
it works as expected.

### 🤔 Expected Behavior
configuration/separateCss should be one of these:
"prod" | false | true

**Comment by ranyitz** [comment]
@aarnoldaas Thanks for opening this issue, PRs welcome.

**Comment by cowchimp** [comment]
Fixed by #963
