### ISSUE TITLE
Add an option to disable PropTypes removal in Babel

### ISSUE THREAD

**Issue by yardnsm** [wix/yoshi#852]
# 🙋 Feature Request

### 😯 Current Behavior

There is an [effort](https://github.com/wix/wix-style-react/pull/2493) to migrate `wix-style-react` to `yoshi` 3. One of the changes in `yoshi` 3 is the addition of `babel-plugin-transform-react-remove-prop-types`.

This plugin is great for React application, but is not suitable for component libraries as the library's consumers won't receive PropTypes warning in their console (since the PropTypes, y'know, will be removed).

We can set the `ignoreReact` option to `true` in order to disable this babel plugin, but this option is very generic. More React-related babel plugins (that we might need in WSR) could be added to Yoshi, and by setting this option we won't receive those.

https://github.com/wix/yoshi/blob/b66f226ad8edcd347d89dd5426b6551028146f51/packages/babel-preset-yoshi/index.js#L80-L86

### 🤔 Expected Behavior

Yoshi users should be able to disable this specific plugin.

### 💁 Possible Solution 

Adding another, more specific option to disable this plugin. Maybe `removePropTypes` with a default value of `true`.

### 🔦 Context 

Check out https://github.com/wix/wix-style-react/pull/2493#discussion_r236065662

BTW I loved the emojis.

**Comment by ranyitz** [comment]
@yardnsm I agree that this is a problem.

Some thoughts:

1. The ideal solution would be to supply both `dev` and `prod` components. By having `NODE_ENV=development` we'll get the `prop-types` and then with `NODE_ENV=production` they will be omitted. This would be applicable to any production optimization.

2. Using the `ignoreReact` option won't work as you'll need [`babel-preset-react`](https://github.com/wix/yoshi/blob/b66f226ad8edcd347d89dd5426b6551028146f51/packages/babel-preset-yoshi/index.js#L37-L43) and we also agree that this is a hack.

3. You can use yoshi 3 with a `babel-preset-env` + `babel-preset-react`, which should work for now.

**Comment by hepiyellow** [comment]
@ranyitz 
About `1.` do you mean that our `dist` folder would include both `prod` and `dev` sub-folders?

**Comment by yardnsm** [comment]
@hepiyellow 

In *option 3*, I thing @ranyitz meant to use the `ignoreReact` options **and** add the `react` preset in out babel config.

```json
"babel": {
	"presets": [
		["yoshi", {
			"ignoreReact": true
		}],
		"react"
	]
}
```

**Comment by hepiyellow** [comment]
I've tried this:
```
"babel": {
    "presets": [
      ["yoshi", {
        "ignoreReact": true
      }],
      "react"
    ],
```

And it seems to keep the propTypes.

**Comment by yardnsm** [comment]
We managed to solve this in https://github.com/wix/wix-style-react/commit/f5731aa4608418333661563323a0c8e5841012bd. Closing.
