### ISSUE TITLE
`cosmiconfig` should not look for config out of project folder

### ISSUE THREAD

**Issue by argshook** [wix/yoshi#854]
# 🙋 Feature Request

### 😯 Current Behavior

running `yoshi lint` can yield unexpected results if user has `stylelintrc` or similar in home folder

### 🤔 Expected Behavior

`yoshi lint` should not care about configurations outside project folder

### 💁 Possible Solution 

when running `yoshi lint` yoshi first checks what kind of linters it should use and in turn calls `shouldRunStylelint` https://github.com/wix/yoshi/blob/master/packages/yoshi-helpers/queries.js#L44-L48

it uses `cosmiconfig` which abstracts config file resolution. it's great but by default it climbs up file tree until it reaches home folder. this can yield unexpected `lint` results.

possible solution could be using `stopDir` setting for `cosmiconfig` https://github.com/davidtheclark/cosmiconfig#stopdir

i see this as a bug but it may be intentional :man_shrugging: 

### 🔦 Context 

found this by accident. added `.stylelintrc` to my home folder expecting only my text editor to use it and got surprised by `yoshi lint` giving me many errors without code changes

**Comment by ronami** [comment]
I'm not sure how easy it would be to define the project directory. One approach is that we can stop when we find either `. stylelintrc` file __or__ a `package.json` and treat that as the root directory. We can probably do the same for our own config.

**Comment by ranyitz** [comment]
@argshook closing, please reopen if still relevant.
