### ISSUE TITLE
Making jest-yoshi preset configurable

### ISSUE THREAD

**Issue by bodia-uz** [wix/yoshi#861]
# 🙋 Feature Request

Jest has a lot of configuration options, but when using `jest-yoshi-preset` we only allowed a few of them.

# 💭 Thoughts

We can look at the approach presented in CRA - https://github.com/facebook/create-react-app/blob/49e258b4a6d04fb7e3542d7a060c6dcad4093564/packages/react-scripts/scripts/utils/createJestConfig.js#L72-L81
Which is, to whitelist a specific set of configuration options, that we know won't break the usage in the preset.

While it makes sense to control which options are whitelisted from the preset maintenance point of view, It really limiting the users.

It means that if I want to add coverage reports, my options are to ask yoshi maintainers to add a specific configuration option. Usually, when encountering of this kind of problems, I'm minded to create a project related feature and not to find the best API for everyone.

As a result, instead of using `jest-preset-yoshi`, I configured the environments myself, in a custom way ([example](https://github.com/wix-private/vmaf/blob/4b81d6aecb5f3141678ebc4298335ddcd7b203b2/vmaf-client/jest.config.js)).

I prefer to use `jest-preset-yoshi` instead of my own config, so I'll get updates.

### 🔦 Context 

These are the specific things that I needed to configiure in my project:
1. Disable `diagnostics` from `ts-jest`- It's an opinionated matter, that I prefer to run typechecking in precommit instead of during tests - https://kulshekhar.github.io/ts-jest/user/config/diagnostics
2. `collectCoverage`/`collectCoverageFrom`/`CoverageReports` - I want coverage reports and i need to configure them separatly for each project.
3. `testEnvironment`: [`enzyme`](https://github.com/FormidableLabs/enzyme-matchers/tree/master/packages/jest-environment-enzyme) instead of `jsdom`
4. `testEnvironmnetOptions: { "enzymeAdapter": "react16" }`

### 💁 Possible Solution

In order to create a predictable API we can use the following convention:

```js
{
  options:{
    // will be passed to the global config
    collectCoverage: true
  },
  component: {
    options: { 
      // will be passed to the component project config
      testEnvironment: 'enzyme'
      testEnvironmentOptions: {
        enzymeAdapter: 'react16'
      },
      setupTestFrameworkScriptFile: 'jest-enzyme'
    }
  },
  bootstrap: {
    options: {
      // will be passed to the bootstrap project config
    }
  },
  puppeteer: {
    options: {
      // will be passed to the puppeteer project config
    }
  }
}

```

**Comment by yakirn** [comment]
@ronami @ranyitz I think this is a good idea that we can all benefit from. Specifically in our case opting out from `ts-jest diagnostics` will have a very positive effect on dev-ex. Any chance to reopen this?

**Comment by ranyitz** [comment]
@yakirn I agree, This is an important issue that should be back on the discussion table.

**Comment by muteor** [comment]
We too could do with this so we can migrate from protractor.

In our case the blocking part is we have a custom `moduleNameMapper` to deal with some thirdparty files:

`"^!!raw-loader": "<rootDir>/__mocks__/fileMock.js"`

**Comment by ranyitz** [comment]
@muteor Can you open a dedicated issue for protractor and explain the problem and what should be fixed?

**Comment by muteor** [comment]
@ranyitz my problem isn't protractor, its more that I need to customize the preset because we started using jest way before the preset was created. The aim is to be able to use the nice parts of the preset, like the puppeteer setup etc but keep our main test suite working.

This is a typical setup for our projects: https://github.com/wix-private/da-frontend/blob/master/projects/da-browse/package.json#L34

**Comment by ranyitz** [comment]
@muteor Ok, so you want to extend the `moduleNameMapper` of a specific environment. 

_______

being able to extend the default configuration (Add keys to an object in this case) should be a guideline for the PR that will fix this issue.

**Comment by yanivefraim** [comment]
Just a few comments:

- We do not really need global config overrides, since they just work (for example, adding a `"collectCoverage": true` to your package.json's  `jest` will just work (it will override a `collectCoverage` in `jest-yoshi-preset` global config, if there is one).
- For project specific config (`specs/e2e`) - I don't think we want (or can) add those directly to our `jest` config in `package.json`. One option is to add it to `yoshi` entry, something like:

```
// package.json
{
  "yoshi": {
      ...
      jestConfigOverrides: {
        ...
      }
  }
}
```

I must say that I don't really like this option. Suggestions / thoughts?

**Comment by yakirn** [comment]
We must have a config somewhere... What is it that you don't like? It being in `package.json` or nested under `yoshi` key?
Maybe we can add it to `jesst-yoshi.config.js` instead?

**Comment by ranyitz** [comment]
Agree with @yakirn `jest-yoshi.config.js` would be a good way to go for now.

Later on, in the future, it would hopefully be [united with `yoshi.config.js`](https://github.com/wix/yoshi/issues/1429)

__________________

Some things have changed over the course of the past year.

Now we have two environments:

`spec` (for jsdom tests)
`e2e` (for puppeteer tests)

Now I see the config like this:

```js
server: {
	command: 'node dev/server.js',
	port: 3100,
},
puppeteer: {
	devtools: false,
},
// the spec project options
spec: {
	globals: {
      "__DEV__": true
    }
},
// the e2e project options
e2e: {
	globals: {
	  foo: "bar"
	}
}
```

**Comment by yakirn** [comment]
@ranyitz Maybe we should nest it under `jest`. Otherwise it could be confusing for ppl that are not familiar with the tools (jest/puppeteer). Something like this:
```
server: {
...
},
jest: {
    // we can also add a default config that will be applied to all
    default: {
         "collectCoverage": false
    },
    // the spec project options
    spec: {
        globals: {
            "__DEV__": true
       }
    },
    // the e2e project options
    e2e: {
	globals: {
	    foo: "bar"
	}
    }
}

**Comment by ranyitz** [comment]
@yakirn We are already in the context of jest (e.g. `jest-yoshi.config.js`).

**Comment by yakirn** [comment]
Oh right right 😓
