### ISSUE TITLE
Enable adding generated sources directories to wallaby config

### ISSUE THREAD

**Issue by splintor** [wix/yoshi#863]
# 🙋 Feature Request

### 😯 Current Behavior
When we generate sources (e.g. proto files using https://github.com/wix-platform/wix-node-platform/tree/master/rpc/wix-proto-codegen) and the generated sources are not under `./src`, wallaby fails to import files from the generated directory, because it is not in wallaby config's `files` array.

### 🤔 Expected Behavior

provide a way to tell wallaby that some directories need to be included in the `files` list. Maybe enable a general way to tweak wallaby config (e.g. add `debug: true`)

### 💁 Possible Solution 

change `wallaby.js` to be:
```
module.exports = wallaby => {
  const config = require('yoshi/config/wallaby-jest')(wallaby);
  config.files.push({ pattern: 'proto/**', instrument: true });
  return config;
}
```

**Comment by Schniz** [comment]
Is it bad to generate the sources in `src`?

**Comment by splintor** [comment]
We (and probably other teams too) would prefer not to put our generated sources under `src`, as it might lead to confusion. The convention is that `src` is for source code we write, not machines.
I think it would be best if wallaby configuration also included sources from `generated/**` in case a team wants to put their generated sources under `generated` and not under `src`.

What do you think? Do you want me to send a PR?

**Comment by splintor** [comment]
Any chance of this being handled?
