### ISSUE TITLE
`create-yoshi-app` should skip assembly

### ISSUE THREAD

**Issue by mastertheblaster** [wix/yoshi#870]
# 🙋 Feature Request

IMHO we should add the following code to our generators:

```xml
    <properties>
        <shouldSkipAssembly>false</shouldSkipAssembly>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <skipAssembly>${shouldSkipAssembly}</skipAssembly>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

### 😯 Current Behavior

It's not being added.

### 🤔 Expected Behavior

To be added.

### 🔦 Context

It's due a fact that a single repo might contain both scala and client code.

**Comment by ranyitz** [comment]
@mastertheblaster I'm not sure that I understand. Can you explain what is the problem that this feature solves?

**Comment by ronami** [comment]
@mastertheblaster is this still relevant? Can you add some info on this?

**Comment by mastertheblaster** [comment]
Lets close it. Seems it's related to our mono repo (containing scala + client code). Didn't see any issues for other developers.
