### ISSUE TITLE
Autocomplete organization in create-yoshi-app

### ISSUE THREAD

**Issue by Schniz** [wix/yoshi#876]
# 🙋 Feature Request

### 😯 Current Behavior
the `organization` part in the prompt is `text`. People can have typos, we can call the same organization with different names (`infra` vs `infrastructure` vs `fed-infra`)

### 🤔 Expected Behavior
Choosing from a list of companies

### 💁 Possible Solution 

Using [prompts `autocomplete`](https://github.com/terkelg/prompts#autocompletemessage-choices-initial-suggest-limit-style) with a list of predefined organizations

### 🔦 Context 

Can be later on help with adding sentry automatically (`team === organization`, `project === package.json#name`)

**Comment by sidoruk-sv** [comment]
@Schniz as I understand correctly:
`FYI - organization within the pom is no longer needed`, seems like organizations can be cleaned from all yoshi templates.
(`#velocity-infra` Slack channel message at `Dec 11th at 10:28`)

**Comment by ranyitz** [comment]
@sidoruk-sv That's wonderful!
Can you open an issue about it (with a link to the explanation) and we'll close this one??

**Comment by ranyitz** [comment]
@sidoruk-sv @yairhaimo @Schniz I still don't understand whether we need the `organization` field or not. If we need it, let's understand why and if not, let's remove it.

**Comment by Schniz** [comment]
[Here's some context in Slack](https://wix.slack.com/archives/CAQSD5B8Q/p1544516916042100), also: [another thread about Yoshi there!](https://wix.slack.com/archives/CAQSD5B8Q/p1547116178102600)

**Comment by ranyitz** [comment]
@Schniz Still confuses me - https://wix.slack.com/archives/CAQSD5B8Q/p1547116441103000?thread_ts=1547116178.102600&cid=CAQSD5B8Q

Maybe we should just remove the organization field and see what happens.

**Comment by ranyitz** [comment]
Continue on #1334
