### ISSUE TITLE
could not exec create-yoshi-app

### ISSUE THREAD

**Issue by gugu-lee** [wix/yoshi#878]
# 🐛 Bug Report

### 😯 i exec 'npx create-yoshi-app my-app',

the result is : 
npx: installed 187 in 6.234s
You should be authenticated to Wix's private registry
Run the following command and try again:

  npm config set registry http://npm.dev.wixpress.com
 
then i exec ' npm config set registry http://npm.dev.wixpress.com' ,but the network is not connected.
i ping the npm.dev.wixpress.com, not any response.

### 🤔 Expected Behavior

...

### 🔦 Context 

...

### 💁 Possible Solution 

...

### 💻 Code Sample

...

### 🌍 Your Environment
OS : linux

```
// PASTE HERE
```

**Comment by yairhaimo** [comment]
Currently the `create-yoshi-app` only works for Wix employees.
We're planning a publicly available generator but we do not have one at this time.
I understand that it's not stated anywhere in the documentation and that it's confusing.
We'll address that also.

While the `create-yoshi-app` utility is not publicly accessible, `yoshi` itself is.
You can use `yoshi` in your `package.json` scripts the same way the generator templates do:
```
  "scripts": {
    "start": "yoshi start",
    "pretest": "yoshi build",
    "test": "yoshi test --jest",
    "posttest": "yoshi lint",
    "release": "yoshi release"
  },
```

You can browse the different `yoshi` configuration options in the documentation:
https://wix.github.io/yoshi/docs/api/configuration

Closing the issue. I'll reopen if relevant.

**Comment by gugu-lee** [comment]
ok ,thank you.
