### ISSUE TITLE
How to create yoshi app out of Wix?

### ISSUE THREAD

**Issue by adavidof** [wix/yoshi#879]
# 🐛 Bug Report

### 😯 Current Behavior
To create yoshi app I should change registry:
`npm config set registry http://npm.dev.wixpress.com`

...

### 🤔 Expected Behavior
If I want to create the app - just create it for me.

...

### 🔦 Context 
How can I create the yoshi app out of the wix-private?

...

### 👣 Steps to Reproduce 
1. Change global registry to default(`https://registry.npmjs.org`)
2. Create app:
```bash
npx create-yoshi-app app
```
3. Select Full stack and TS

### 🌍 Your Environment
```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
  Binaries:
    Node: 11.3.0 - ~/.nvm/versions/node/v11.3.0/bin/node
    Yarn: Not Found
    npm: 6.4.1 - ~/.nvm/versions/node/v11.3.0/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 71.0.3578.80
    Firefox: 62.0.2
    Safari: 12.0.2
  npmPackages:
    @storybook/core: Not Found
    @storybook/react: Not Found
    babel-preset-yoshi:  3.17.0 
    eslint-config-yoshi:  3.21.0 
    eslint-config-yoshi-base:  3.21.0 
    jest-environment-yoshi-bootstrap:  3.22.4 
    jest-environment-yoshi-puppeteer:  3.22.4 
    jest-yoshi-preset: ^3.5.0 => 3.22.4 
    storybook: Not Found
    tslint-config-yoshi:  3.21.0 
    tslint-config-yoshi-base:  3.21.0 
    typescript: ~3.0.1 => 3.0.3 
    webpack:  4.27.1 
    yoshi-config:  3.22.4 
    yoshi-helpers:  3.22.4 
    yoshi-runtime:  1.0.41 

 Yoshi config
{
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM"
  },
  "hmr": "auto"
}
```

**Comment by adavidof** [comment]
I can't use the full stack app with `wix-private` or `wix-platform` out of wix.
Why I should remove them manually from yoshi project after app was created?

**Comment by adavidof** [comment]
Yoshi team, could you please help?

**Comment by yairhaimo** [comment]
Right now `create-yoshi-app` only supports internal applications.
You have two options if you want to use it for an external project:
1. Use `create-yoshi-app` and delete any internal code/packages
2. Create a new project manually and use `yoshi` in the npm scripts (start/build/test/lint)

We're looking into creating an opensource generator but it wont be in the near future.
