### ISSUE TITLE
could not start on Linux

### ISSUE THREAD

**Issue by gugu-lee** [wix/yoshi#885]
# 🐛 Bug Report

### 😯 Current Behavior

i create project on windows and it execute ok.
i deploy it on linux . when i start my project ,it's  error.
error message is  : 
** 
 @wix/client@1.0.0 start /opt/provider/client
> yoshi start

/opt/provider/client/node_modules/yoshi/bin/yoshi-cli.js:37
  )
  ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10) 
**

in the yoshi-cli.js the code is ： 

 **24 prog
     25   .command('test')
     26   .description('Run unit tests and e2e tests if exists')
     27   .option('--mocha', 'Run unit tests with Mocha')
     28   .option('--jasmine', 'Run unit tests with Jasmine')
     29   .option('--karma', 'Run unit tests with Karma')
     30   .option('--jest', 'Run tests with Jest')
     31   .option('--protractor', 'Run e2e tests with Protractor')
     32   .option('--debug', 'Allow test debugging')
     33   .option('--coverage', 'Collect and output code coverage')
     34   .option(
     35     '--debug-brk',
     36     "Allow test debugging, process won't start until debugger will be attached",
     37   )
     38   .option(
     39     '-w, --watch',
     40     'Run tests on watch mode (mocha, jasmine, jest, karma)',
     41   )**

### 🤔 Expected Behavior

...

### 🔦 Context 

...

### 💁 Possible Solution 

...

### 💻 Code Sample

...

### 🌍 Your Environment

```
yoshi：  3.22.4
// PASTE HERE
```

**Comment by ranyitz** [comment]
@gugu-lee I don't think that Linux is the problem here.

My guess would be NodeJS version.

The feature that you lack (trailing commas in function calls) is [available since version 8.2.1 of Node](https://node.green/#ES2017-features-trailing-commas-in-function-syntax)

Can you please check the version of Node which runs on the Linux machine?

**Comment by gugu-lee** [comment]
yes,thank u
