### ISSUE TITLE
Move server project template to jest (instead of mocha)

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#899]
# 🙋 Feature Request

### 😯 Current Behavior

New generated project are using Mocha

### 🤔 Expected Behavior

New Projects should use Jest instead of mocha

### 💁 Possible Solution

Move the generators to use Jest instead of mocha (similarly to fullstack template)

### 🔦 Context

I just moved my server project from mocha to Jest. More and more people are asking for it, let's move it in the generators themselves.

These are the changes from my pull request (move from mocha to jest in a typescript server project) - https://github.com/wix-private/performance-stats/commit/52856556ea7aa2aa107dd24cc5e778e6636a652f for a reference

**Comment by dmfilipenko** [comment]
https://github.com/wix/yoshi/pull/1248 try to fix

**Comment by ranyitz** [comment]
Continue on https://github.com/wix/yoshi/pull/1289

**Comment by ranyitz** [comment]
We're not sure that this is the right way to go. When we'll work on `yoshi-server-flow` we'll try to understand what is the best test runner to work with for this case. For now, closing
