### ISSUE TITLE
Restart the server on `index.ejs` file changes

### ISSUE THREAD

**Issue by shlomitc** [wix/yoshi#900]
# 🙋 Feature Request

### 😯 Current Behavior
After generating a fullstack project and running `npm start`, a common pattern is adding link tags to the `ejs` file (for example fonts). As `yoshi` doesn't restart the server, the same `ejs` file is being served, thus looks like nothing happend.
This is a bit confusing for new users...

### 🤔 Expected Behavior
effect immediately and not require to stop `npm start`

### 💁 Possible Solution 
Restart the server and maybe reload the browser page

### 🔦 Context 
I gave a `FED for BED` workshop, and they didn't understand why it didn't have any effect when adding the fonts link tag

**Comment by yairhaimo** [comment]
Solved as part of the new Yoshi 4 AppFlow
