### ISSUE TITLE
Ignore some typescript errors on local dev build

### ISSUE THREAD

**Issue by eranshabi** [wix/yoshi#91]
`.tsconfig` let you toggle some compiler options which are more lint like, and you don't want them to disturb you during development:

- noUnusedLocals
- noUnusedParameters
- noImplicitReturns
- noFallthroughCasesInSwitch

There should be a feature to ignore errors from those options on local serve (or turning those options off before serve)

**Comment by ranyitz** [comment]
It will be confusing to have errors only on production.

If there is a general solution for typescript in the community (different rules on dev vs prod) we can open this again.

Closing for now.
