### ISSUE TITLE
Add a way to serve the application just like in production (yoshi serve)

### ISSUE THREAD

**Issue by ranyitz** [wix/yoshi#914]
# 🙋 Feature Request

### 😯 Current Behavior

Emulating production is difficult, there are multiple steps required, which are not necessarily known to the user.

### 🤔 Expected Behavior

There is a simple command, that serves the application just like in production.

### 💁 Possible Solution
Implement `yoshi serve` command.

The command serves the bundled application (from `dist/statics/`) similarly to the CDN in production. If the bundle is not there, it will show a message that `yoshi build` needs to be run.

### 🔦 Context 

There are multiple requests for such feature, that enables testing things just like in production, which `yoshi start --production` does not provide.

**Comment by Schniz** [comment]
This is crucial for us as well, when testing performance for Yoshi apps. I'd like to do `yoshi build && yoshi serve`, and then I won't have any traces of development mode like HMR

**Comment by moshfeu** [comment]
Still no updates? :(

**Comment by ranyitz** [comment]
Help wanted and PRs welcome 😃

**Comment by Schniz** [comment]
Maybe I'll have time for it tomorrow
because I need it too :D

cc @cowchimp

**Comment by Schniz** [comment]
I have written our own, stripped down `yoshi serve`:

* run `yoshi build`
* if `index-dev.js` is found = fullstack project:
  * `env <YOSHI_BOOTSTRAP_ARGUMENTS> node index-dev.js`
* else if `dev/server.js` is found = client project:
  * `env <YOSHI_BOOTSTRAP_ARGUMENTS> node dist/server.js`
* else
  * fail 😄 

This is what @ranyitz [have replied](https://github.com/wix-private/perfer/pull/11#issuecomment-488648739):

> I want to add that I agree, and something like that will work great as a Yoshi feature.
>
> Our only problems are with the --entry-point/--server options.
>
> We may be able to find those [by] parsing package.json's scripts.start and extracting the option (I don't believe that I'm saying this). (It's a bit better than creating a convention we don't really respect (index-dev.js/dev/server.js))
>
> If we do something like that for the sake of zero config, we should also show a deprecation warning that suggests that the user need to switch from using --entry-point to a config option.

**Comment by Schniz** [comment]
I'm filling the blanks here. This feature is _harder_ and _hackier_ (is that a word?) than the simple case I thought it would be.

There are more open questions:

* I'm not sure that I want to implement it for Yoshi 3, and it would make Perfer's preset for Yoshi compat with Yoshi 4 only. Is it a good thing? cc @yairhaimo 
* We need to test it against multiple templates: `{client,server}{,-typescript}`. @ronami how do you think we should approach it?
* PARSING IS SUPER DUPER HACKY. But can also kinda work. I still don't know what `yoshi start` does because it works

**Comment by Schniz** [comment]
Together with #1476 this issue makes perfect sense 😄 

I thought about it yesterday: what would you say about adding a new package to the monorepo called `yoshi-cmd-serve` or something like that, so it would also work on older `yoshi`s?

Context: I need it for Perfer, and we currently solve serving "production-like" Yoshi 1-4 apps in [our `perfer-preset-yoshi` package](https://github.com/wix-private/perfer/tree/master/packages/perfer-preset-yoshi). Adding a `serve` command to Yoshi 4/5 won't be enough, and I don't think we should add new feature for older versions. That being said, a `yoshi-cmd-serve` can use `yoshi serve` for newer Yoshi versions (4.X+), or use the "hacky" way we introduced for older versions (1-3).

**Comment by yanivefraim** [comment]
What is the status of this one?

**Comment by ranyitz** [comment]
The status is that this issue is not solved yet. I would like to have a `yoshi serve` command as it makes the following API:

`test` - Running the tests runner
`lint` - Running the linter
`start` - Running a development server (should probably be called `dev`...)
`build` - Build your app for production
`serve` - Serve your app just like in production (should probably be called `start`...)

For being able to serve older yoshi applications which is a different concern (being able to use something that acts like yoshi serve for older versions) we can create another solution, but I don't want it to affect Yoshi's future API.

This issue is up for grabs.

**Comment by moshfeu** [comment]
For now, if anyone need that, I use `nodemon` to track changes and trigger the build.

Something like that:

```
nodemon --watch src --exec "yarn build"
```

**Comment by ranyitz** [comment]
This is closed on #1980
