### ISSUE TITLE
yoshi is not work on IE11?

### ISSUE THREAD

**Issue by gugu-lee** [wix/yoshi#928]
# 🐛 Bug Report

### 😯 Current Behavior
i dev my project and test it .
but my client is use IE11, when he open my app,the broswer is blank .

...

### 🤔 Expected Behavior

...

### 🔦 Context 

...

### 💁 Possible Solution 

...

### 💻 Code Sample

...

### 🌍 Your Environment

my packge.json is 

{
 
  "scripts": {
    "start": "yoshi start ",
    "precommit": "lint-staged",
    "pretest": "yoshi build ",
    "test": "yoshi test --jest",
    "posttest": "yoshi lint",
    "release": "yoshi release"
  },
  "devDependencies": {
    "enzyme": "~2.9.0",
    "express": "^4.16.4",
    "express-session": "~1.15.0",
    "husky": "~0.14.0",
    "jest-yoshi-preset": "^3.5.0",
    "lint-staged": "^7.2.2",
    "puppeteer": "^1.1.0",
    "react-test-renderer": "~15.6.0",
    "velocity": "~0.7.0",
    "webpack": "^4.28.4",
    "webpack-cli": "^3.2.1",
    "yoshi": "^3.25.1",
    "yoshi-style-dependencies": "^3.0.0"
  },
  "dependencies": {
    "axios": "^0.16.2",
    "i18next": "^11.6.0",
    "ng2-cookies": "^1.0.12",
    "node-sass": "^4.11.0",
    "prop-types": "~15.6.0",
    "react": "15.6.1",
    "react-dom": "15.6.1",
    "react-event-timeline": "^1.6.2",
    "react-i18next": "^7.11.0",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "store": "^2.0.12",
    "validator": "^10.10.0",
    "wix-style-react": "^5.23.0"
  },
  "lint-staged": {
    "*.{js,scss,less}": "yoshi lint"
  },
  "yoshi": {
    "externals": {
      "react": "React",
      "react-dom": "ReactDOM",
      "separateCss": "prod"
    },
    "hmr": "auto",
    "splitChunks": true
  },
  "babel": {
    "presets": [
      "yoshi"
    ]
  },
  "eslintConfig": {
    "extends": "yoshi"
  }
}

// PASTE HERE
```

**Comment by gugu-lee** [comment]
![default](https://user-images.githubusercontent.com/6067910/51456844-1108ea00-1d8a-11e9-819b-056093c423b4.png)

**Comment by yairhaimo** [comment]
Yoshi currently transpiles down to IE11 level so your app **should** work.
Could you run the app in dev mode (`npm start`) and open it in IE11 and see if it works and/or get a better error message?

Two other, unrelated notes:
- You don't need to have webpack in your `devDependencies`, yoshi will install it. Moreover, it will collide with yoshi's webpack if the versions are not aligned.
- You defined `"separateCss": "prod"` as part of your `externals` definition. It should be at the top level `yoshi` configuration.

**Comment by gugu-lee** [comment]
yes i run (npm start), my IE11 is blank page when i open the url. 
but now my ie11 dev tool is not avlidate ,so i  have not more error message.
so i submit the screen shot by edge.

**Comment by yairhaimo** [comment]
Can you try to git bisect the issue?

**Comment by gugu-lee** [comment]
now ,i find it not work if it has some code like blow.

```
function text(children, style) {
  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100px',
        background: '#F0F4F7',
        ...style,
      }}
    >
      <Text>{children}</Text>
    </div>
  );
}
```

**Comment by gugu-lee** [comment]
i compare the diffence for it ,
when have not this function ,the app.bundle.js ls like blow.
![2](https://user-images.githubusercontent.com/6067910/51471712-71138680-1db2-11e9-982e-9ddd4ffb0673.png)

when have the function  ,it like 

![3](https://user-images.githubusercontent.com/6067910/51471792-aa4bf680-1db2-11e9-9933-e030d05da02b.png)

pls attention to the red rectangle,it have a **"use strict";"**

also use the 
`text=()=>{}` 

it also wrong in IE and edge.

**Comment by yairhaimo** [comment]
`use strict` is a valid syntax in IE11.
Your screenshot didnt show the `text` arrow function (or I missed it).
Can you please create a small reproduction of the problem?

**Comment by gugu-lee** [comment]
this is my project url.

https://github.com/gugu-lee/test-ie11

**Comment by gugu-lee** [comment]
oh, now  i give up the yoshi and wix-story-style .my client is require IE11 and wix do not support.
very bad.

**Comment by gugu-lee** [comment]
GREATE!!!,
i resolve the wix in IE11.
but i have a new problem , in IE11 axios is require '@babel/polyfill' ，how config this in the yoshi .like in webpack .

**Comment by gugu-lee** [comment]
@yairhaimo
