### ISSUE TITLE
By default, Yoshi lint only fails on TC

### ISSUE THREAD

**Issue by IgnotasWix** [wix/yoshi#93]
After this commit (https://github.com/wix/yoshi/commit/ef4483c71b1678b37cef19d15d82ce2d0bd5ff07) lint no longer fails when running it on a development machine and only fails during builds on TC. For our team in particular, this wastes a lot of time, because when the build seems to be passing locally and the code is pushed, it takes TC 10 minutes until it fails with a lint error.

I think the lint tool failing when errors are present is the expected behaviour regardless of the environment that it's running in. If there is a need to not make it fail, the lint should take an extra option for this instead of having this behaviour by default.

**Comment by roymiloh** [comment]
[Reverted](https://github.com/wix/yoshi/commit/98f0e3e54e4b5cda57fe84953afa820cd179a9dd), thanks.
