### ISSUE TITLE
Mocha test with webpack externals

### ISSUE THREAD

**Issue by sarareisner** [wix/yoshi#96]
I'm trying to write a mocha test with yoshi test, but it fails because mocha can not load module that is defined in my webpack external.

**Comment by roymiloh** [comment]
@sarareisner External modules should be installed and `import`ed ordinarily (Webpack just doesn't care where they come from while it's bundling), so I'm not sure why it's happening. Can you please elaborate?

**Comment by sarareisner** [comment]
I have a project that I want to bundle with yoshi. as I understood yoshi has webpack from itself and I cant add configuration to the webpack. in my project in the webpack.config I have externals     
externals: {
        react: 'React',
        'react-dom': 'ReactDOM',
        lodash: '_',
        jquery: '$',
        Wix: 'Wix',
        'editor-ui-lib': 'UI'
    },
how do I remove them witout getting the error: cant find module ?

**Comment by yanivefraim** [comment]
@sarareisner - if I understand correct, you need a way to configure your externals with Yoshi? You can do it by adding 'externals' to 'yoshi' key, in package.json. Something like:

```json
"yoshi": {
    "externals": {
      "react": "React"
    }
  }
```

**Comment by ronami** [comment]
On top of what @yanivefraim said, you should have these dependencies as `devDependencies` in your `package.json`.

Closing, please re-open if it's still relevant.
