### ISSUE TITLE
yoshi lint is not fixing issues in lint-staged

### ISSUE THREAD

**Issue by yakirn** [wix/yoshi#968]
# 🐛 Bug Report

### 😯 Current Behavior

`create-yoshi-app` is creating a project with `lint-staged` configured to run `yoshi lint` on all commited files. linter is running on the committed files but no errors are reported.
Running `npx yoshi lint` after committing is showing the errors correctly

### 🤔 Expected Behavior

- Linter should fix autofixable errors, and block the commit if there are non fixable errors.
- Running `npx yoshi lint` immediately after a committing successfully should yield 0 errors/warnings

### 🔦 Context 

Linting and fixing only files that have changed in the commit phase, in opposed to linting all files in the build phase, enables us to incrementally adopt rules and change / update our linter with minimal effort, while maintaining our critical code base "linted".

### 💁 Possible Solution 

this used to work, I tried this as well:
```
  "lint-staged": {
    "linters": {
      "*.{js,ts,tsx,scss,less}": "yoshi lint --fix=true"
    },
    "ignore": [
      "**/*.d.ts"
    ]
  }
```
but no success 🤷🏻‍♂️.

### 👣 Steps to Reproduce 

1. run `create-yoshi-app` and select a typescript client project.
2. create an initial commit
3. go to any TS file and enter some redundant spaces somewhere
4. make another valid change (change the value of a string or something)
5. `npx yoshi lint` will show your error
6. git commit will succeed without autofixing

### 🌍 Your Environment

```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
    Yarn: 1.1.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.9.4/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 72.0.3626.81
    Firefox: 63.0.3
    Safari: 12.0.3
  npmPackages:
    @storybook/core: Not Found
    @storybook/react: Not Found
    babel-preset-yoshi:  3.17.0 
    eslint-config-yoshi:  3.25.1 
    eslint-config-yoshi-base:  3.25.1 
    jest-environment-yoshi-bootstrap:  3.26.0 
    jest-environment-yoshi-puppeteer:  3.26.0 
    jest-yoshi-preset: ^3.5.0 => 3.28.0 
    storybook: Not Found
    tslint-config-yoshi:  3.26.0 
    tslint-config-yoshi-base:  3.26.0 
    typescript: ~3.0.1 => 3.0.3 
    webpack:  4.28.4 
    yoshi-config:  3.23.0 
    yoshi-helpers:  3.26.0 
    yoshi-runtime:  1.0.42 

 Yoshi config
{
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM"
  },
  "hmr": "auto"
}
```

**Comment by ranyitz** [comment]
@yakirn Two things:

> * go to any TS file and enter some redundant spaces somewhere
1. This is a prettier **warning** (in oppose to **error**) which means it won't fail your build, and that's the wanted behavior from our point of view. Prettier team release breaking changes on minor versions, they say that formatting should not break your build. I agree with that.

![image](https://user-images.githubusercontent.com/11733036/52535335-c90c3000-2d55-11e9-9f58-1112e812560c.png)

Therefore lint-stage is passing despite the fact there's a warning.

2. If you're working with `--fix=true` you can also [use `git add`](https://github.com/okonet/lint-staged#automatically-fix-code-style-with---fix-and-add-to-commit) which will include the prettier changes in the commit.

I'm not using it personally as I'm more into IDE autofixing my code as I write it, but that's an opinionated matter.

Let me know if there are any questions bugs left here.

**Comment by yakirn** [comment]
Ah `"git add"` is what I was missing, thanks @ranyitz !
