### ISSUE TITLE
Proposal: ability to debug node proccess

### ISSUE THREAD

**Issue by TomasRup** [wix/yoshi#97]
As a developer I would like to debug a node process haste starts, i.e. —inspector=PORT could be passed.

Maybe a more generic feature would be better: to pass any parameters to the node process that you want.

**Comment by ronami** [comment]
@hadar111, was it closed in #264?

**Comment by ranyitz** [comment]
Available on [v2.3.0](https://github.com/wix/yoshi/blob/master/CHANGELOG.md#230-may-9-2018)
