### ISSUE TITLE
Upstream dependencies should not break Yoshi

### ISSUE THREAD

**Issue by cowchimp** [wix/yoshi#980]
# 🙋 Feature Request

Right now if an upstream dependency of Yoshi is updated and they didn't respect semver and introduced breaking changes, then Yoshi builds break.

### 🤔 Expected Behavior

Expected behavior is not immediately clear here.
Obviously there's no way to know if the latest changes are going to break you or not, so we need to decide if we rather be up-to-date and get latest updates automatically, or manually pull and verify latest changes.

### 💁 Possible Solution 

Need to research further. First want to check if we can agree on the pain.
Would need to check if having a `npm-shrinkwrap.json` helps, and what are the disadvantages.
Can also maybe consider having two separate builds where the master build that effects other users uses some lockfile, but there's an automatic other branch that pulls latest deps and gives you feedback about whether the build passes, and gives you a one-click option to turn that state into a lockfile that will affect master.

### 🔦 Context 

Context is a lot of cases in the last few days where upstream changes broke things and brought in noise.

**Comment by ronami** [comment]
We're now using Renovate that helps with it. Please re-open if it's still relevant. Closing
