### ISSUE TITLE
SSL Port is not visible when running with `npm start -- --ssl`

### ISSUE THREAD

**Issue by morsh** [wix/yoshi#989]
# 🐛 Bug Report

When running with `npm start -- --ssl` the ssl port is not visible in the console, after being speified in:

package.json:
```
"yoshi": {
    "servers": {
      "cdn": {
        "port": 3111,
        "dir": "dist/statics"
      }
    }
```

### 🤔 Expected Behavior

Show ssl port in console

### 🔦 Context 

...

### 💁 Possible Solution 

...

### 💻 Code Sample

...

### 🌍 Your Environment

yoshi 3.0.0

**Comment by ranyitz** [comment]
@morsh thanks for opening this issue.

![image](https://user-images.githubusercontent.com/11733036/53099849-565a3c00-352f-11e9-9251-9c8b5477ae6f.png)

I've just checked this use case, and it seems to **show the port**.
It would be better though, to give A link the direct the user to the full CDN server path (`webpack-dev-server`), or in your case - `https://localhost:3111/`

PR welcome to change it so it would be nicer and clearer!

**Comment by ranyitz** [comment]
Fixed on https://github.com/wix/yoshi/pull/1282
