### ISSUE TITLE
entry points

### ISSUE THREAD

**Issue by sarareisner** [wix/yoshi#99]
I need to define entry point to app.
I did it like this:
  "yoshi": {
    "entry": {
      "settings": "./src/settings/index"
    }
  },
when I run yoshi stat it fails:
return chunk.isInitial() || chunk.parents.length === 0;
TypeError: chunk.isInitial is not a function

**Comment by maxaon** [comment]
@sarareisner Yo should not add root path. If your file is under `./src/settings/index.js`, it should be 
```json
  "yoshi": {
    "entry": {
      "settings": "./settings/index"
    }
  },
```

**Comment by yanivefraim** [comment]
Closing. Please reopen if something is still not clear
